Feat  eligibility module
betagouv/service-national-universel pull request #1050
Opened 2022-01-04 17:21 UTC by SpookyUmi

Fixes #1043

2022-01-05 10:40 UTC, tangimds reviewed
Pourquoi on n'utilise pas le design des modales existantes ?

2022-01-05 10:43 UTC, tangimds reviewed
la vue sur téléphone n'est pas hyper clean (le radio button est coupé et ya un petit scroll)
j'ai testé sur format iphone 5

<img width="347" alt="Screenshot 2022-01-05 at 11 43 09" src="https://user-images.githubusercontent.com/33058720/148204631-d7acf46c-995c-4888-ab0b-f74c7011d7ba.png">

2022-01-05 10:47 UTC, tangimds requested changes

2022-01-05 10:47 UTC, tangimds commented on app/src/scenes/inscription/components/eligibilityModal.js
> +                    subTitle="Au format : AAAA/MM/JJ"
il faudrait que le format soit français : JJ/MM/AAAA

2022-01-05 10:47 UTC, tangimds commented on app/src/scenes/inscription/components/eligibilityModal.js
> +                    placeholder="Renseignez votre adresse"
pourquoi on ne demande pas uniquement le code postal ? ou le departement (parmi la liste de département que nous avons)
Ca eviterait des erreurs

2022-01-05 10:47 UTC, tangimds commented on app/src/components/Note.js
> +          </a>
il faudrait l'ouvrir dans un nouvel onglet

2022-01-05 15:23 UTC, tangimds approved these changes
juste le console log a enlever et on est bon !
pour la liste des classes, je suppose que c'est parce que ce sont que ceux la qui sont bloquants. mais l'idée est de tous les mettre je pense. sinon ca va générer du support

dailleurs en relisant, la classe et le departement ne servent a rien dans ce contexte parce que dans tous les cas, juillet ne dépend que de la date de naissance (donc meme si ce sont des dom-tom en 3eme par exemple, ils sont eligible a juillet)
bref, on verra par la suite

2022-01-05 15:23 UTC, tangimds commented on app/src/scenes/inscription/components/eligibilityModal.js
> +const levels = [
pourquoi on ne met pas tout ca ?
```            { label: "3ème", value: "3eme" },
            { label: "2nd", value: "2nd" },
            { label: "1ère", value: "1ere" },
            { label: "1ère année CAP", value: "1ere CAP" },
            { label: "Terminale", value: "Terminale" },
            { label: "Terminale CAP", value: "Terminale CAP" },
            { label: "SEGPA", value: "SEGPA" },
            { label: "Classe relais", value: "Classe relais" },
            { label: "Autre", value: "Autre" },

2022-01-05 15:23 UTC, tangimds commented on app/src/scenes/inscription/components/eligibilityModal.js
> +  }, []);
```suggestion
```

2022-01-06 09:45 UTC, tangimds requested changes

2022-01-06 09:45 UTC, tangimds commented on app/src/scenes/inscription/components/eligibilityModal.js
> +                  if (!ok) return console.log("Une erreur s'est produite lors de la création de ce ticket :", translate(code));
```suggestion
                  if (!ok) return console.log("Une erreur s'est produite lors de la vérification d'éligibilité :", translate(code));
```

2022-01-06 09:45 UTC, tangimds commented on app/src/scenes/inscription/components/eligibilityModal.js
> +                  {isEligible && display ? (
proposition: on a la liste des possibilités, peut être qu'on peut les afficher ? (a faire potentiellement plus tard dans une autre pr)

2022-01-06 09:45 UTC, tangimds commented on app/src/scenes/inscription/components/eligibilityModal.js
> +                      link="https://inscription.snu.gouv.fr/inscription/profil"
mettre l'url base dispo dans `src/config` ?

2022-01-06 09:45 UTC, tangimds commented on app/src/scenes/inscription/components/eligibilityModal.js
> +                      link="https://support.snu.gouv.fr/help/fr-fr/16-comprendre-le-snu/7-les-autres-formes-d-engagement"
mettre l'url base dispo dans `src/config` ?

2022-01-06 09:45 UTC, tangimds commented on api/src/controllers/cohort-session.js
> +    schoolLevel: Joi.string(),
si on ne cochait pas la case, ca plantait (sans message d'erreur d'ailleurs)
```suggestion
    schoolLevel: Joi.string().allow(null, ""),
```

2022-01-06 09:45 UTC, tangimds commented on app/src/scenes/inscription/components/eligibilityModal.js
> +                  console.log(e);
ajouter un `toastr` ici pour les erreurs

2022-01-06 09:45 UTC, tangimds commented on api/src/controllers/cohort-session.js
> +    },
il faudrait enlever ca aussi, on mettre un date de fin d'inscription et filter dessus tout le temps

2022-01-06 10:51 UTC, SpookyUmi commented on app/src/scenes/inscription/components/eligibilityModal.js
> +                  {isEligible && display ? (
Yes je peux faire ca juste après avoir merge cette PR !

2022-01-06 10:52 UTC, SpookyUmi commented on api/src/controllers/cohort-session.js
> +    },
Pas sûr d'avoir compris ce que tu veux faire ici ? 
Mais dans tous les cas oui il faut enlever ou modifier vu que ce séjour est fermé

2022-01-06 11:03 UTC, SpookyUmi commented on api/src/controllers/cohort-session.js
> +    },
Ok si pardon je pense que j'ai compris

2022-01-06 13:08 UTC, tangimds approved these changes
zepartii
jme pose la question sur les dates de fin pour les séjours de juin et juillet.
t'as mis au feeling ou ce sont des dates officielles ?

dailleurs c'est cool ce que tu as fait, je pense qu'il faudrait le mettre dans l'autre route aussi, pour que ca ne les propose pas dynamiquement. Parceque pour cette session, j'ai viré fevrier a la main mais c'est pas ouf comme méthode --'
le seul pb ce serait avec les fuseaux horaires (on se base sur le fuseau du serveur quoi, pas du client)

2022-01-06 13:19 UTC, merged