fix(admin): restrict head center access
betagouv/service-national-universel pull request #1182
Opened 2022-02-01 13:49 UTC by SpookyUmi

Fixes #1178

2022-02-01 16:25 UTC, tangimds requested changes
en tant qu'admin, je ne vois aucune sessions :(
<img width="1299" alt="Screenshot 2022-02-01 at 17 21 06" src="https://user-images.githubusercontent.com/33058720/152007630-01369ca1-ac18-4d99-b2de-90e131f10c13.png">

2022-02-01 16:25 UTC, tangimds commented on admin/src/scenes/centers/view/Nav.js
> +          {user.role !== "head_center" ? (
apres reflexion, je pense quil vaut mieux partir sur une white list qu'une black list. qu'en penses-tu ?
on a eu plusieurs fois le scénario ou on oublie que ya ce sujet la et ducoup un role a accès a des infos
```suggestion
          {[ROLES.ADMIN, ROLES.REFERENT_REGION, ROLES.REFERENT_DEPARTMENT].includes(user.role) ? (
```

2022-02-01 16:25 UTC, tangimds commented on admin/src/scenes/centers/view/index.js
> +  console.log(user);
```suggestion
```

2022-02-01 16:25 UTC, tangimds commented on admin/src/scenes/centers/view/index.js
> +      console.log("CENTER", centerResponse.data);
```suggestion
```

2022-02-01 16:25 UTC, tangimds commented on admin/src/scenes/centers/view/index.js
> +      setAvailableCohorts(allSessions.data.filter((session) => session.headCenterId === user._id).map((session) => session.cohort));
ne filtrer que si c'est nécessaire maybe ?

2022-02-01 16:27 UTC, SpookyUmi commented on admin/src/scenes/centers/view/index.js
> +      setAvailableCohorts(allSessions.data.filter((session) => session.headCenterId === user._id).map((session) => session.cohort));
Oui en effet ><

2022-02-02 10:55 UTC, tangimds commented on admin/src/scenes/centers/view/Nav.js
> +  const visibleCohorts = [ROLES.ADMIN, ROLES.REFERENT_REGION, ROLES.REFERENT_DEPARTMENT].includes(user.role) ? center.cohorts : cohorts;
on ne pourrait pas mettre ca avant, c'est car la on a un filtre et une gestion des cohortes eclatée entre deux fichier `index` et `Nav` ?
c'est a ca que je faisait référence dans mon précédent commentaire "ne filtrer que si besoin"

2022-02-03 10:01 UTC, lucienklein approved these changes

2022-02-03 10:22 UTC, merged