Tailwind-setup
betagouv/service-national-universel pull request #1255
Opened 2022-02-15 10:45 UTC by HugoKessler

initial tailwind setup + drawer;
run npx tailwindcss -i ./src/index.css -o ./src/tailwindcss.css --watch while developping

2022-02-15 16:37 UTC, SpookyUmi commented
> npx tailwindcss -i ./src/index.css -o ./src/tailwindcss.css --watch while developping

Cette commande n'a pas lieu d'être ici car on a déjà un build tool qui run le projet (contexte React+webpack), Tailwind va donc tourner quand on lance `npm run dev`

2022-02-15 16:57 UTC, SpookyUmi commented
<img width="281" alt="Screenshot 2022-02-15 at 17 51 58" src="https://user-images.githubusercontent.com/62291986/154110129-e73c9f42-f4b2-4333-835a-2d907f884aa8.png">
Petit écart ici entre le drawer et le header

2022-02-15 16:58 UTC, SpookyUmi commented
<img width="567" alt="Screenshot 2022-02-15 at 17 52 56" src="https://user-images.githubusercontent.com/62291986/154110548-50ebf3f6-102c-456b-b90f-8b8aca4bbf99.png">
Attention au reset des styles (preflight de Tailwind), ici on a les `h2` et `h3` qui ont été reset 😬

2022-02-15 16:59 UTC, SpookyUmi commented
<img width="838" alt="Screenshot 2022-02-15 at 17 56 53" src="https://user-images.githubusercontent.com/62291986/154110797-91a7a224-f174-47c6-80a1-2fc93935d7a8.png">
Partie un peu + tricky, mais en plus petite résolution le drawer reste alors qu'il devrait disparaître. À voir si c'est voulu @tangimds ?

2022-02-16 08:39 UTC, HugoKessler commented
> > npx tailwindcss -i ./src/index.css -o ./src/tailwindcss.css --watch while developping
> 
> Cette commande n'a pas lieu d'être ici car on a déjà un build tool qui run le projet (contexte React+webpack), Tailwind va donc tourner quand on lance `npm run dev` Cf cette page de la doc : https://tailwindcss.com/docs/guides/nextjs --> l'exemple est en Next mais c'est similaire dans notre cas

Oui, si c'est juste pour lancer le projet aucun souci sans cette commande. Mais pour que le fichier de style tailwind se mette à jour en cas de changement c'est nécessaire. J'avais mis cette commande car en théorie je ne vais pas être le seul à développer sur tailwind.

2022-02-16 09:18 UTC, SpookyUmi commented
> > > npx tailwindcss -i ./src/index.css -o ./src/tailwindcss.css --watch while developping
> > 
> > 
> > Cette commande n'a pas lieu d'être ici car on a déjà un build tool qui run le projet (contexte React+webpack), Tailwind va donc tourner quand on lance `npm run dev` Cf cette page de la doc : https://tailwindcss.com/docs/guides/nextjs --> l'exemple est en Next mais c'est similaire dans notre cas
> 
> Oui, si c'est juste pour lancer le projet aucun souci sans cette commande. Mais pour que le fichier de style tailwind se mette à jour en cas de changement c'est nécessaire. J'avais mis cette commande car en théorie je ne vais pas être le seul à développer sur tailwind.

Si c'est intégré au build tool, ca s'exécute avec le build tool (tu as pas besoin de lancer PostCSS, Eslint, Prettier, commitlint, Husky, SASS dans 10 onglets différents par exemple)
- Tailwind va pas être présent dans un seul fichier index, mais dans tous les composants, donc de manière générale faut le compiler dans chaque fichier
- Un `npm run dev` va pas juste lancer le serveur (s'il est bien configuré) mais aussi bundle chaque morceau de Tailwind à la volée (grâce à JIT), en fonction de comment c'est utilisé dans le projet

2022-02-17 09:57 UTC, SpookyUmi requested changes
<img width="254" alt="Screenshot 2022-02-17 at 10 55 56" src="https://user-images.githubusercontent.com/62291986/154451309-ff1a876e-08a0-433f-b09d-866d254692a5.png">
Ici quand le drawer est ouvert on peut changer l'icone, mettre une croix à la place du burger :)

2022-02-17 09:57 UTC, SpookyUmi commented on admin/tailwind.config.js
> +  mode: "jit",
```suggestion

```
Plus besoin de cette ligne, Tailwind le fait par défaut :) 
Cf : https://tailwindcss.com/docs/upgrade-guide#migrating-to-the-jit-engine

2022-02-17 09:57 UTC, SpookyUmi commented on admin/tailwind.config.js
> +  content: ['./src/**/*.js'],
```suggestion
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
```

2022-02-18 10:41 UTC, SpookyUmi approved these changes

2022-02-18 10:42 UTC, SpookyUmi commented
@HugoKessler  c'est good ! Plus qu'à résoudre le conflit (demande à Tangi de checker avec toi, je ne saurais pas te dire quel changement appliquer dans le cas présent) et tu peux merge :)

2022-02-21 09:12 UTC, merged