fix(api): validate status is forbidden
betagouv/service-national-universel pull request #1258
Opened 2022-02-16 10:33 UTC by SpookyUmi

Fixes #1247
Je n'ai pas encore vérifié si ca ne pétait rien dans l'inscription et autre, mais voilà mon idée de base
Le async await est peut être pas judicieux ici d'ailleurs

2022-02-16 10:47 UTC, tangimds reviewed
je n'ai pas testé, mais voici mes retours a la leture 👇 

ps : certains tests ne passent plus

2022-02-16 10:47 UTC, tangimds commented on api/src/controllers/young/index.js
> +    if (newYoung[status] === "VALIDATED") {
erreur de conceptoin, mais le status `VALIDATED` pour la phase 1 est `DONE` --'

2022-02-16 10:47 UTC, tangimds commented on api/src/controllers/young/index.js
> +    const canYoungUpdateStatus = await canUpdateSeveralStatus(value, res);
effectivement le `await/async` n'est pas nécessaire :)

2022-02-16 10:47 UTC, tangimds commented on api/src/controllers/young/index.js
> +    const canYoungUpdateStatus = await canUpdateSeveralStatus(value, res);
pourquoi tu passes 2 arguments alors que la fonction n'en a qu'un dans sa sginature ?

2022-02-16 12:59 UTC, SpookyUmi commented on api/src/controllers/young/index.js
> +    const canYoungUpdateStatus = await canUpdateSeveralStatus(value, res);
C'était un test que j'ai oublié d'enlever ˆˆ

2022-02-18 16:15 UTC, tangimds commented on api/src/__tests__/young.test.js
> +    it.only("should remove places when sending to cohesion center", async () => {
faut l'enlever ca par contre :)
```suggestion
    it("should remove places when sending to cohesion center", async () => {
```

2022-02-18 16:15 UTC, tangimds commented on lib/index.js
> +function canUpdateStatus(newYoung, oldYoung) {
pour ce genre de fucniton, j'aime bien rendre explicite les params, au moins on ne peut pas inverser/se tromper.
du style xxx({actor, target})

2022-02-18 16:16 UTC, tangimds commented on lib/index.js
> +  if (!allStatus.filter((s) => newYoung[s] !== oldYoung[s]).length) return true;
ducoup FYI
```suggestion
  if (!allStatus.some((s) => newYoung[s] !== oldYoung[s])) return true;
```

2022-02-18 16:20 UTC, tangimds commented on lib/index.js
> +  return !authorized;
mmmh je crois que c'est encore a l'envers non ?

`authorized` est a `true` si l'un des champs est en train d'être modifié vers `VALIDATED`
pour rester logique dans la nomenclature j'aurais mis ca
```suggestion
  const notAuthorized = youngStatus || youngStatusPhase1 || youngStatusPhase2 || youngStatusPhase3 || youngStatusMilitaryPrepFiles || youngStatusPhase2Contract;

  return !notAuthorized;
```

2022-02-18 16:22 UTC, tangimds requested changes
quelques changements avant ?
tu as pu tester si le formulaire d'inscription & co marche encore ?

2022-02-22 15:30 UTC, merged