HugoKessler/issue1251
betagouv/service-national-universel pull request #1268
Opened 2022-02-21 09:14 UTC by HugoKessler

2022-02-22 17:02 UTC, tangimds commented
j'ai push des modifs comme un cochon.
jte laisse remettre clean comme le screenshot ci dessous :
![Screenshot 2022-02-22 at 18 01 58](https://user-images.githubusercontent.com/33058720/155181501-486efd3c-4618-4672-8290-f7d722c151ea.png)

2022-02-23 08:33 UTC, tangimds commented
je regarde pour changer la route api, il faut la mettre dans le controller young
`/young/:id/change-cohort/:newCohort`

2022-02-23 14:07 UTC, HugoKessler commented
> je regarde pour changer la route api, il faut la mettre dans le controller young `/young/:id/change-cohort/:newCohort`

Done

2022-02-23 20:50 UTC, tangimds requested changes
Je t'ai laissé quelques retours + quelques propositions.
hesites pas si quelque chose n'est pas clair :)

2022-02-23 20:50 UTC, tangimds commented on app/src/scenes/phase1/changeSejour.js
> +      await api.put("/young", { cohort: newSejour });
on peut le faire en un seul call a l'api. beaucoup plus performant et moins gourmant
```suggestion
      await api.put("/young", { cohort: newSejour, cohortChangeReason: motif });
```

2022-02-23 20:50 UTC, tangimds commented on app/src/scenes/phase1/changeSejour.js
> +      toastr.success("Cohorte modifiée avec succès");
on peut meme renotifier pour quelle cohorte il a changer ?

2022-02-23 20:50 UTC, tangimds commented on api/src/controllers/young/index.js
> +    // await updateApplicationsWithYoungOrMission({ young, newYoung: value });
on peut virer
```suggestion
```

2022-02-23 20:50 UTC, tangimds commented on api/src/controllers/young/index.js
> +router.put("/:id/change-cohort/:newCohort", passport.authenticate("young", { session: false, failWithError: true }), async (req, res) => {
on peut ne pas spécifier la cohorte directement dans la route, on peut la passer dans le body (avec le reste des infos d'ailleurs)
```suggestion
router.put("/:id/change-cohort", passport.authenticate("young", { session: false, failWithError: true }), async (req, res) => {
```

2022-02-23 20:50 UTC, tangimds commented on api/src/controllers/young/index.js
> +    young.set(value);
on ne vérifie pas ce qu'on va mettre à jour, on fait confiance aveuglément au front. C'est pas bon 😬 

ce qu'on peut faire c'est destructurer le `value`, récupérer les properties qu'on veut récuperer (`cohort`, `cohortChangeReason`, `cohortDetailedChangeReason`) et les injecter dans le young -> on a le contrôle.

2022-02-23 20:50 UTC, tangimds commented on api/src/controllers/cohort-session.js
> +
on ne met pas en waiting list dans une session en particulier, donc l'`id` ne fait pas de sens ici.
par contre, on peut effectivement faire une route pour "mettre le jeune en liste d'attente".
Ce n'est pas une vraie liste d'attente, c'est juste le status du jeune qui est `WAITING_LIST`

(on peut en rediscuter)

2022-02-23 20:50 UTC, tangimds commented on app/src/scenes/phase1/changeSejour.js
> +      await api.put("/young/" + young._id + "/change-cohort/" + newSejour, { cohort: newSejour });
on peut le faire en un seul call (avec la nouvelle route proposée plus haute)
(1 seul call api, a seul call a la db)
```suggestion
      await api.put("/young/" + young._id + "/change-cohort", { cohortChangeReason: motif, cohortDetailedChangeReason: messageTextArea, cohort: newSejour });
```

2022-02-23 20:50 UTC, tangimds commented on app/src/scenes/phase1/changeSejour.js
> +  };
ah, tu passais l'id du jeune ? pourquoi ? je ne comprends pas la route

2022-02-23 20:50 UTC, tangimds commented on app/src/scenes/phase1/changeSejour.js
> +                    <a href="https:support.snu.gouv.fr/base-de-connaissance/suis-je-eligible-a-un-sejour-de-cohesion-en-2022-1" style={{ color: "#5145cc" }}>
```suggestion
                    <a href="https:support.snu.gouv.fr/base-de-connaissance/suis-je-eligible-a-un-sejour-de-cohesion-en-2022-1" style={{ color: "#5145cc" }} target="_blank" rel="noreferrer">
```

2022-02-23 20:50 UTC, tangimds commented on app/src/scenes/phase1/changeSejour.js
> +        const { ok, code, data } = await api.post("/cohort-session/eligibility/2022", {
tu n'utilises pas `ok` et `code` ?

2022-02-23 20:50 UTC, tangimds commented on app/src/scenes/phase1/changeSejour.js
> +  const [isEligible, setIsElegible] = useState(false);
si on set a `false` par defaut.
le temps de chargement montre une info erronée -> https://www.loom.com/share/d2a55c90f5c64dd299f34ad78603c0c2

ce n'est pas que le volontaire n'est pas éligible, c'est qu'on ne le sait pas encore.

il faudrait pouvoir mettre un loader tant que le call line 36 n'est pas executée et traitée

2022-02-24 16:01 UTC, HugoKessler commented on app/src/scenes/phase1/changeSejour.js
> +  const [isEligible, setIsElegible] = useState(false);
All done

2022-02-25 09:53 UTC, tangimds commented on api/src/controllers/young/index.js
> +    if (!young) return res.status(404).send({ ok: false, code: ERRORS.NOT_FOUND });
il faudrait mettre cette ligne avant de vouloir acceder a cette variable (line 474 et 476)
la mettre juste apres le find, pour stopper si il n'est pas trouvé

2022-02-25 09:53 UTC, tangimds commented on api/src/controllers/young/index.js
> +      young.set({ cohort: value.cohort, cohortChangeReason: value.cohortChangeReason, cohortDetailedChangeReason: value.cohortDetailedChangeReason, statusPhase1: "WAITING_LIST" });
C'est le status global qu'il faut mettre en. waiting list... pas logique, je sais :(
```suggestion
      young.set({ cohort: value.cohort, cohortChangeReason: value.cohortChangeReason, cohortDetailedChangeReason: value.cohortDetailedChangeReason, status: "WAITING_LIST" });
```

2022-02-25 09:53 UTC, tangimds commented on api/src/controllers/young/index.js
> +    if (req.body.isFull === true) {
en fait, la on donne la main au front, les gens peuvent trigger telle ou telle condition comme il veulent (depuis postman par exemple)
ici, ce n'est pas tres grave, car il trigger une action qui n'est pas en leur faveur, mais potentiellement faire le calcul de si c'est full ou non ici aussi. c'est n'est pas le front qui le dicte, c'est nous qui le calculons

2022-02-25 09:53 UTC, tangimds commented on api/src/controllers/young/index.js
> +    }
si on ne change pas les attributes `sessionPhase1Id` du jeune, la mis a jour de la session ne fera rien car on n'a pas cassé la liaison entre le volontaire et la session

2022-02-25 09:53 UTC, tangimds commented on app/src/scenes/phase1/changeSejour.js
> +        if (obj.goal === true && obj.goal === newSejour) return obj.sejour === newSejour;
je ne comprends pas cette ligne ?
`=== Boolean` et `=== String` ?

2022-02-25 09:58 UTC, tangimds commented
@HugoKessler et ya des confilts à résoudre 😬

2022-02-25 16:23 UTC, tangimds reviewed
ya toujours des conflits :(

2022-02-25 16:23 UTC, tangimds commented on api/src/controllers/young/index.js
> +    young.set({ sessionPhase1Id: "" });
peut etre supprimer le `meetingPointId` aussi ?
```suggestion
    young.set({ sessionPhase1Id: undefined });
```

2022-03-04 12:59 UTC, merged