refactor(security): refactor inscription done
betagouv/service-national-universel pull request #1462
Opened 2022-04-11 08:37 UTC by hlecourt

2022-04-14 09:07 UTC, tangimds reviewed
j'ai pas testé mais voici qq retours sur le code

2022-04-14 09:07 UTC, tangimds commented on api/src/controllers/young/inscription.js
> +router.put("/save/:type", passport.authenticate("young", { session: false, failWithError: true }), async (req, res) => {
j'aurais plutot fait une autre route perso.
mais sinon on peut rendre le parametre optionnel :
`/save`
`/save/correction`

```suggestion
router.put("/save/:type?", passport.authenticate("young", { session: false, failWithError: true }), async (req, res) => {
```

2022-04-14 09:07 UTC, tangimds commented on app/src/components/form/FormFooter.js
> -import { saveYoung } from "../../scenes/inscription/utils";
on peut supprimer cette fonction ducoup ?

2022-04-14 09:07 UTC, tangimds commented on app/src/components/form/FormFooter.js
> +    const { ok, code, data: young } = await api.put(`/young/inscription/save/normal`, values);
pourquoi pas laisser `data` ?

`young` est déjà defini au scope du composant. en soit, ca va marcher mais pas dingue d'avoir deux variables nommées pareils si "proches"

2022-04-14 09:07 UTC, tangimds commented on app/src/components/form/FormFooter.js
> +    const { ok, code, data: young } = await api.put(`/young/inscription/save/normal`, values);
c'était deja le cas avant, mais je trouve ca moche en fait mdr

2022-04-21 13:43 UTC, rap2hpoutre requested changes
Merci encore une fois pour tout ce travail !

Peut-être que j'ai mal compris mais j'ai l'impression qu'on défait partiellement ce qu'on a fait dans le reste des PR, si je comprends bien on dit : 

> On vérifie très précisément à chaque étape ce qu'on peut envoyer MAIS avec la requête du bouton "save" on peut toujours envoyer ce qu'on veut.

Une sorte de backdoor si je comprends bien.

Est-ce qu'on n'aurait pas dû plutôt étendre les routes qui existent pour autoriser un save partiel mais cohérent ?

2022-04-21 13:43 UTC, rap2hpoutre commented on api/src/utils/validator.js
> +      email: Joi.string().allow(null, ""),
```suggestion
      email: Joi.string().lowercase().trim().email().allow(null, ""),
```

Plus globalement pourquoi on remettrait pas tous les contrôles qu'on a mis ailleurs ?

2022-04-22 14:33 UTC, rap2hpoutre reviewed
En cliquant sur continuer sur cette page : 
> "schoolCountry" must be [false]

<img width="1060" alt="Capture d’écran 2022-04-22 à 16 32 20" src="https://user-images.githubusercontent.com/1575946/164735620-ae7fc4f8-e648-48dd-9989-319e0739cafd.png">

En bonus ce serait pas mal de mettre un toastr quand on a cliqué sur enregistrer pour savoir que tout s'est bien passé.

2022-04-22 14:42 UTC, rap2hpoutre approved these changes
EN dehors des deux petites remarques, je valide !

2022-04-25 14:13 UTC, rap2hpoutre approved these changes
🎉

2022-04-25 14:13 UTC, rap2hpoutre commented on app/src/scenes/inscription/Create/stepCoordonnees.js
> +
```suggestion
```

2022-04-25 14:34 UTC, merged