feat(admin): floating help button
betagouv/service-national-universel pull request #1474
Opened 2022-04-12 20:27 UTC by tangimds

2022-04-13 07:29 UTC, hlecourt requested changes

2022-04-13 07:29 UTC, hlecourt commented on admin/src/components/HelpButton.js
> +        {(LISTE_LIEN_AIDE_PAR_ROLE[user.role] || []).map((e) => (
Le rôle à la connexion est pas défini ça fait tout peter !

2022-04-13 07:34 UTC, hlecourt commented on admin/src/components/HelpButton.js
> +        {(LISTE_LIEN_AIDE_PAR_ROLE[user.role] || []).map((e) => (
<img width="230" alt="image" src="https://user-images.githubusercontent.com/50077368/163124096-7b4395aa-c66d-42e5-8a44-c4c52116ef80.png">
Petit soucis aussi niveau UI

2022-04-21 09:48 UTC, hlecourt commented
En attente du nouveau design du Drawer

2022-11-04 15:36 UTC, tangimds commented
legacy

2022-11-04 15:36 UTC, closed without merging