Refacto(admin): phase 1 style admin
betagouv/service-national-universel pull request #1498
Opened 2022-04-22 13:56 UTC by SpookyUmi

2022-04-25 10:06 UTC, tangimds requested changes
les boutons ne sont pas les mêmes, les ombres ne sont pas les mêmes ?
<img width="715" alt="Screenshot 2022-04-25 at 11 42 26" src="https://user-images.githubusercontent.com/33058720/165063957-3516538b-debc-45d0-abce-0409dbbdcbf6.png">

il y a un espace sous le footer des modales
<img width="546" alt="Screenshot 2022-04-25 at 11 45 16" src="https://user-images.githubusercontent.com/33058720/165064408-7fe5ffc3-ce99-46f4-8c03-fe951ad31a0b.png">


le calpin est vide si il n y a pas de document renseigné (pas prio)
<img width="348" alt="Screenshot 2022-04-25 at 11 54 50" src="https://user-images.githubusercontent.com/33058720/165066195-e8f5ad40-88b2-4436-b613-d763228d93d8.png">

2022-04-25 10:06 UTC, tangimds commented on api/src/zammad-migration/ticketScriptForMetabase.js
> -require("dotenv").config({ path: "../../.env-staging" });
pourquoi ce fichier est dans cette PR ?

2022-04-25 10:06 UTC, tangimds commented on admin/src/components/buttons/ModalButton.js
> +export default function ModalButton({ primary, newPrimary, secondary, loading, children, disabled, ...rest }) {
je pensais qu'on ne passait pas au bleu tout de suite ?
la on va avoir des endroits en violet, d'autre en bleu, c'est pas très clean

2022-04-25 10:06 UTC, tangimds commented on admin/src/scenes/volontaires/components/DocumentPhase1.js
> +      value: "RECIEVED",
```suggestion
      value: "RECEIVED",
```

2022-04-25 10:06 UTC, tangimds commented on admin/src/scenes/volontaires/components/ButtonPlain.js
> +export default function ButtonPlain({ bgColor = "bg-blue-600 text-white", children, onClick }) {
pourquoi appeler `bgColor` si il y a plein d'autre className ?
```suggestion
export default function ButtonPlain({ bgColor = "bg-blue-600 text-white", children, onClick }) {
```

2022-04-25 10:06 UTC, tangimds commented on admin/src/scenes/volontaires/components/DocumentPhase1.js
> +            bgColor="bg-white border-2 border-blue-600 text-blue-600"
2px de border c'est venere non ? je crois que le `border` est surchargé par reactstrap
```suggestion
            bgColor="bg-white border-[1px] border-blue-600 text-blue-600"
```

2022-04-25 10:06 UTC, tangimds commented on admin/src/scenes/volontaires/components/FileCard.js
> +import React from "react";
ce fichier est utilisé ?

2022-04-25 10:06 UTC, tangimds commented on admin/src/scenes/volontaires/view/phase1.js
> +  const [cohesionCenter, setCohesionCenter] = useState({ name: "yolo" });
```suggestion
  const [cohesionCenter, setCohesionCenter] = useState();
```

2022-04-25 10:06 UTC, tangimds commented on admin/src/scenes/volontaires/view/phase1.js
> +
```suggestion
```

2022-04-25 10:06 UTC, tangimds commented on admin/src/scenes/volontaires/view/phase1.js
> +                        tw=""
?

2022-04-25 10:06 UTC, tangimds commented on admin/src/scenes/volontaires/components/DocumentPhase1.js
> +const ScrollSection = styled.section`
non utilisée ?

2022-04-25 10:06 UTC, tangimds commented on admin/src/scenes/volontaires/components/DocumentPhase1.js
> +const Option = styled.option`
pourquoi ?

2022-04-25 10:07 UTC, SpookyUmi commented on admin/src/scenes/volontaires/components/DocumentPhase1.js
> +      value: "RECIEVED",
Il doit être typo partout car il était déjà écrit comme ca, donc risky de le change là.

2022-04-25 10:08 UTC, SpookyUmi commented on admin/src/scenes/volontaires/components/DocumentPhase1.js
> +            bgColor="bg-white border-2 border-blue-600 text-blue-600"
Si on met juste `border`, on ne peut pas appliquer de couleur dessus.

2022-04-25 10:08 UTC, SpookyUmi commented on admin/src/scenes/volontaires/components/ButtonPlain.js
> +export default function ButtonPlain({ bgColor = "bg-blue-600 text-white", children, onClick }) {
je change

2022-04-25 10:09 UTC, SpookyUmi commented on admin/src/components/buttons/ModalButton.js
> +export default function ModalButton({ primary, newPrimary, secondary, loading, children, disabled, ...rest }) {
J'ai cru comprendre l'inverse mais je peux rollback du coup

2022-04-25 10:10 UTC, SpookyUmi commented on api/src/zammad-migration/ticketScriptForMetabase.js
> -require("dotenv").config({ path: "../../.env-staging" });
J'ai fait tourner le script pour Metabase dans la semaine, j'ai fait qques modifs mais je les ai push là, sorry, c'est très critique ?

2022-04-25 10:13 UTC, SpookyUmi commented
> les boutons ne sont pas les mêmes, les ombres ne sont pas les mêmes ? <img alt="Screenshot 2022-04-25 at 11 42 26" width="715" src="https://user-images.githubusercontent.com/33058720/165063957-3516538b-debc-45d0-abce-0409dbbdcbf6.png">
> 
> il y a un espace sous le footer des modales <img alt="Screenshot 2022-04-25 at 11 45 16" width="546" src="https://user-images.githubusercontent.com/33058720/165064408-7fe5ffc3-ce99-46f4-8c03-fe951ad31a0b.png">
> 
> le calpin est vide si il n y a pas de document renseigné (pas prio) <img alt="Screenshot 2022-04-25 at 11 54 50" width="348" src="https://user-images.githubusercontent.com/33058720/165066195-e8f5ad40-88b2-4436-b613-d763228d93d8.png">

J'ai expliqué pourquoi déjà, justement pour que vous soyez prévenus, donc je réexplique : 
Il y a certains boutons (comme le LoadingButton et autres) qui sont utilisés partout, donc tant qu'il n'y a pas une modif générale du design c'est touchy de les modifier totalement maintenant. Donc à moins de créer plusieurs autres boutons qui vont juste répéter ce que font déjà certains components, pour l'instant ce n'est pas parfait.

2022-04-25 10:49 UTC, SpookyUmi commented on admin/src/scenes/volontaires/components/DocumentPhase1.js
> +const Option = styled.option`
C'était quand j'essayais des choses pour appliquer du style sur les options

2022-04-28 09:50 UTC, tangimds commented on api/src/zammad-migration/ticketScriptForMetabase.js
> -require("dotenv").config({ path: "../../.env-staging" });
non
sur une PR de 20 fichiers, a +1000 lignes modifiées c'est un peu galère si on a des fichiers en trop en plus.

2022-04-28 09:58 UTC, tangimds reviewed
il reste une typo [ici](https://github.com/betagouv/service-national-universel/pull/1498/files#diff-8743df6c3b1bae9c3368b2c44dfb409d023dd718d9fd42c38b858931b2c6951fL75)

je ne sais pas si ca vient de cette pr, l'ux des select est cassée ?
<img width="716" alt="Screenshot 2022-04-28 at 11 58 46" src="https://user-images.githubusercontent.com/33058720/165728158-52cc5491-5660-4451-9f70-8957f059bfde.png">

2022-04-28 10:02 UTC, tangimds commented
> le calpin est vide si il n y a pas de document renseigné (pas prio)
si il n y a aucun fichier d'upload, il n y a pas de fichier sur le bloc note.
je n'avais meme pas vu avant que Nina me le montre... donc bon pour l'instant c'est clairement pas grave du tout

2022-04-28 10:03 UTC, tangimds commented
les boutons sont comme ca chez moi, c'est pareil de ton côté ?
<img width="764" alt="Screenshot 2022-04-28 at 11 49 08" src="https://user-images.githubusercontent.com/33058720/165728958-daa33785-1ff3-47f6-bb21-0ea54f79d899.png">

2022-04-28 12:22 UTC, SpookyUmi commented on api/src/zammad-migration/ticketScriptForMetabase.js
> -require("dotenv").config({ path: "../../.env-staging" });
Yes je comprends, je ferai gaffe

2022-05-02 09:44 UTC, merged