feat(admin) : Export des volontaires par ligne de transport / lieu de rassemblement
betagouv/service-national-universel pull request #1560
Opened 2022-05-13 08:57 UTC by hlecourt

https://www.notion.so/jeveuxaider/VOLONTAIRE-Export-des-volontaires-par-ligne-de-transport-lieu-de-rassemblement-cd631c820bd74b97870ef1874e3733d7

2022-05-17 17:37 UTC, tangimds requested changes
je ne reçois pas le mail, il est bien activé sur sendinblue ?

2022-05-17 17:37 UTC, tangimds commented on admin/src/assets/icons/ClipboardList.js
> +      fill="#9CA3AF"
il faudrait rajouter les viewBox et les color
```suggestion
      fill="currentColor"
```

pour tous les svg qu'on importe, ils seront plus facilement réutilisables

2022-05-17 17:37 UTC, tangimds commented on admin/src/scenes/centers/components/modals/ModalExportMail.js
> +      setEmails([...emails, value]);
remarque pas critique
```suggestion
      setEmails((prev)=> [...prev, value]);
```

2022-05-17 17:37 UTC, tangimds commented on admin/src/scenes/centers/components/modals/ModalExportMail.js
> +            disabled={isLoading || !emails.length}
le `disabled:cursor-wait` + `disabled={!emails.length}`
fait que le cursor load par défaut à l'ouverture de la modale

2022-05-17 17:37 UTC, tangimds commented on admin/src/scenes/centers/components/modals/ModalExportMail.js
> +    await onSubmit(emails);
je me suis pris une `onSubmit is not a function`

2022-05-17 17:37 UTC, tangimds commented on admin/src/scenes/centers/youngs/index.js
> +    await toXLSX(`young_pointage_${dayjs().format("YYYY-MM-DD_HH[h]mm[m]ss[s]")}.xlsx`, csv);
il faudrait mettre un nom français --'

2022-05-17 17:37 UTC, tangimds commented on admin/src/scenes/centers/youngs/index.js
> +  console.log(centerId);
```suggestion
```

2022-05-17 17:37 UTC, tangimds commented on admin/src/scenes/centers/youngs/index.js
> +}
on est obligé de mettre tout ça la ?

2022-05-17 17:37 UTC, tangimds commented on admin/src/scenes/session-phase1/index.js
> +    (async () => {
un early return si le token n'set pas défini ?

2022-05-17 17:37 UTC, tangimds commented on admin/src/scenes/centers/components/modals/ModalExportMail.js
> +                    <div className="flex flex-row items-center">
key

2022-05-17 17:37 UTC, tangimds commented on admin/src/scenes/centers/components/modals/ModalExportMail.js
> +    await onSubmit(emails);
mais je viens de réessayer et c'est ok... étrange

2022-05-17 17:37 UTC, tangimds commented on api/src/controllers/meeting-point.js
> +router.get("/center/:id", passport.authenticate("referent", { session: false, failWithError: true }), async (req, res) => {
je l'aurais peut etre mis dans le controller cohesion-center
`get /cohesion-center/:id/meeting-points

2022-05-17 17:37 UTC, tangimds commented on api/src/controllers/meeting-point.js
> +    const center = await CohesionCenterModel.findById(req.user.cohesionCenterId);
mmmh je ne comprends pas ?
la route est ouverte au `young` et on prend son `cohesionCenterId` ?
les jeunes n'ont pas de `cohesionCenterId`, ils auront un `sessionPhase1Id`

2022-05-17 17:37 UTC, tangimds commented on api/src/controllers/session-phase1.js
> +      for (const young of youngs) {
au lieu de boucler ici, tu peux directement selectionner dans mongoose
```javascript
const youngs = await YoungModel.find({ sessionPhase1Id: sessionPhase1._id }).select({ "firstName": 1, "lastName": 1, ....});
```

2022-05-18 13:16 UTC, hlecourt commented
> je ne reçois pas le mail, il est bien activé sur sendinblue ?

Je l'ai activé

2022-05-18 13:48 UTC, tangimds approved these changes

2022-05-18 13:56 UTC, merged