Block-suppression-volontaires_UX
betagouv/service-national-universel pull request #1614
Opened 2022-06-22 13:11 UTC by naustra

https://www.notion.so/jeveuxaider/Centre-bloquer-suppression-d-un-centre-sessions-si-des-volontaires-sont-affect-s-c7576bc0b56844969974d9f06ee40c54

UX fini sauf si on le revoie encore plus en profondeur.

Manque le fait d'empêcher les suppressions de sessions si il y a des volontaires dessus.

2022-06-22 15:19 UTC, naustra commented
C'est fini pour moi !

2022-06-23 08:19 UTC, hlecourt requested changes
Des petits fix a apporter niveau UI mais ca marche bien ! Let's go 💪

2022-06-23 08:19 UTC, hlecourt commented on admin/src/scenes/centers/edit.js
> +                                    <span className="font-weight-bold">{values[cohort]?.placesTotal - values[cohort]?.placesLeft || "Aucuns"}</span> jeunes sont affectés dans ce
1 jeunes sont affectés dans ce centre pour ce séjour.
Aucuns jeunes sont affectés dans ce centre pour ce séjour.

C'est pas clean

2022-06-23 08:19 UTC, hlecourt commented on admin/src/scenes/centers/edit.js
> +                                    <span className="font-weight-bold">{values[cohort]?.placesTotal - values[cohort]?.placesLeft || "Aucuns"}</span> jeunes sont affectés dans ce
Genre il y a X jeune(s) ...

2022-06-23 08:19 UTC, hlecourt commented on admin/src/scenes/centers/edit.js
> +                                      <DropdownItem onClick={() => handleChangeCohort(o)} className="dropdown-item" key={i}>
```suggestion
                                      <DropdownItem onClick={() => handleChangeCohort(o)} className="text-sm" key={i}>
```

2022-06-23 08:19 UTC, hlecourt commented on admin/src/scenes/centers/edit.js
> +                                  <div className="mb-2">
```suggestion
                                  <div className="mb-2 text-gray-500">
```

2022-06-23 08:19 UTC, hlecourt commented on admin/src/scenes/centers/edit.js
> +                                    <span className="font-weight-bold">{values[cohort]?.placesTotal - values[cohort]?.placesLeft || "Aucuns"}</span> jeunes sont affectés dans ce
```suggestion
                                   {values[cohort]?.placesTotal - values[cohort]?.placesLeft || "Aucuns"} jeunes sont affectés dans ce
```

2022-06-23 08:41 UTC, naustra commented on admin/src/scenes/centers/edit.js
> +                                      <DropdownItem onClick={() => handleChangeCohort(o)} className="dropdown-item" key={i}>
Tu veux que j'enleve dropdown-item ?
C'est utilisé partout avec.

2022-06-23 09:13 UTC, naustra commented
Pourquoi ces commits tangimds ?

2022-06-23 11:43 UTC, naustra reviewed
done

2022-06-23 13:55 UTC, hlecourt commented
http://localhost:8082/centre/609bebb20c1cc9a888ae8fbf/edit
Impossible de supprimer la session de juillet alors qu'il y a personne dessus

2022-06-24 07:27 UTC, hlecourt approved these changes
Let's merge it 🎉

2022-06-24 07:29 UTC, merged