feat(app): ouverture des écrans phase 2 à la consultation pendant le séjour
betagouv/service-national-universel pull request #1617
Opened 2022-06-23 13:50 UTC by hlecourt

https://www.notion.so/jeveuxaider/Phase-2-ouverture-des-crans-la-consultation-pendant-le-s-jour-891b3a20ea07475a907a37686dd850b8

2022-06-23 14:45 UTC, tangimds requested changes

2022-06-23 14:45 UTC, tangimds commented on app/src/scenes/missions/components/ApplyModal.js
> +      return toastr.error("Oups, une erreur est survenue lors de la candidature");
t'as fais des changements ou t'as rajouté un `try{}catch{}` ?

2022-06-23 14:45 UTC, tangimds commented on app/src/scenes/missions/components/ApplyModal.js
> +      return toastr.error("Oups, une erreur est survenue lors de la candidature");
ya le `onCancel`

2022-06-23 14:45 UTC, tangimds commented on lib/roles.js
> +function canApplyToPhase2(young) {
le nom de la fonction porte a confusion
si elle retourne `true` c'est que le user ne peut PAS candidater

soit on change la condition, soit le nom de la fonction (je changerais la condition)

2022-06-23 14:48 UTC, hlecourt commented on app/src/scenes/missions/components/ApplyModal.js
> +      return toastr.error("Oups, une erreur est survenue lors de la candidature");
Rajouter le try catch et onCancel

2022-06-27 14:51 UTC, tangimds reviewed
petite question ?
je n'ai pas test

2022-06-27 14:51 UTC, tangimds commented on lib/roles.js
> +const COHESION_STAY_END = {
pourquoi tu l'ajoutes ici ?
on l'a deja la https://github.com/betagouv/service-national-universel/blob/396366eacccdeeec980cc0cba22de1c86451fd5f/lib/constants.js#L383

2022-06-28 07:08 UTC, merged