feat(app, admin): Masquer la mission pour suspendre les candidatures
betagouv/service-national-universel pull request #1630
Opened 2022-06-28 11:36 UTC by laurestph

2022-06-28 21:53 UTC, naustra commented
Cette mission : 62baef5b5ee6fc1b59955c97 n'est pas toggleable en visible/cachée.
Je ne sais pas si c'est normal quand on est en attente de correction ou on devrait pouvoir le faire.

2022-06-28 22:11 UTC, naustra requested changes

2022-06-28 22:11 UTC, pierre-lebihan commented on admin/src/scenes/missions/edit.js
> +        console.log(values);
console log

2022-06-28 22:11 UTC, pierre-lebihan commented on api/src/models/mission.js
> +    enum: ["VISIBLE", "HIDE"],
HIDDEN ?

2022-06-28 22:11 UTC, pierre-lebihan commented on api/src/models/mission.js
> +    type: String,
Ajoute Default VISIBLE ici et enlève le "|| VISIBLE" de admin

2022-06-28 22:11 UTC, naustra commented on admin/src/scenes/missions/edit.js
> +                    {defaultValue ? (
N'affiche carrément pas le bloc si le status n'est pas validé plutôt.
Pas besoin de mettre if defaultValue pour moi car on affiche le loader sinon.
A vérifier si il n'y a pas de cas bizarre avec isNew

2022-06-29 08:25 UTC, laurestph commented on admin/src/scenes/missions/edit.js
> +                    {defaultValue ? (
Ça permet de cacher cette partie lors de l'edition car c'est mis a visible de base  (et faut que la mission soit valide pour que les jeunes puissent la voir)

2022-06-29 09:28 UTC, pierre-lebihan commented on admin/src/scenes/missions/edit.js
> +                    {defaultValue ? (
[  if ((!defaultValue && !isNew) || !structure) return <Loader />;](https://github.com/betagouv/service-national-universel/blob/c0f957ff1626681a04c877c51febfac297401c8e/admin/src/scenes/missions/edit.js#L132)

Je pense que la condition mission validée seule suffit à la place.

2022-06-29 10:05 UTC, naustra approved these changes
C'est bon !

2022-07-01 12:23 UTC, naustra commented
A merge lundi

2022-07-04 10:30 UTC, merged