add MAINTENANCE env variable
betagouv/service-national-universel pull request #1648
Opened 2022-07-05 07:30 UTC by nicobret

2022-07-05 10:03 UTC, naustra requested changes

2022-07-05 10:03 UTC, pierre-lebihan commented on admin/src/scenes/auth/signin.js
> +                    Un nombre important de connexion sur la plateforme impacte son bon fonctionnement. Nous faisons notre possible pour rétablir la situation.
Change le texte par un truc plus passe partout. 
Le site est actuellement en maintenance suite à un problème technique sur la plateforme. Nous faisons notre possible pour rétablir la situation.

2022-07-05 10:03 UTC, pierre-lebihan commented on app/src/config.js
> +let maintenance = false;
Essaie const maintenance = process?.env?.MAINTENANCE ? true : false
On essaiera de la set en Staging après

2022-07-05 10:29 UTC, nicobret commented on admin/src/scenes/auth/signin.js
> +                    Un nombre important de connexion sur la plateforme impacte son bon fonctionnement. Nous faisons notre possible pour rétablir la situation.
Done.

2022-07-05 10:29 UTC, nicobret commented on app/src/config.js
> +let maintenance = false;
Même avec les points d'interrogation ça plante... Je continue à chercher.

2022-07-05 11:56 UTC, naustra commented on app/src/config.js
> +let maintenance = false;
Ah ok, je regarde

2022-07-06 14:00 UTC, tangimds commented on app/src/config.js
> +let maintenance = false;
il n y a pas d'env dans nos app react

2022-07-06 14:17 UTC, nicobret commented on app/src/config.js
> +let maintenance = false;
comment on fait du coup pour passer l'app en mode maintenance ?

2022-07-07 07:38 UTC, naustra commented on app/src/config.js
> +let maintenance = false;
On testera sur le staging

2022-07-07 12:36 UTC, merged