use validatedAt for phases 2 & 3
betagouv/service-national-universel pull request #1659
Opened 2022-07-08 10:48 UTC by nicobret

2022-07-08 11:41 UTC, naustra requested changes

2022-07-08 11:41 UTC, naustra commented on api/src/templates/certificate/index.js
> +    // On vire tout ça ?
Oui

2022-07-08 11:41 UTC, naustra commented on api/src/templates/certificate/index.js
> +  let d = young.statusPhase2ValidatedAt || young.statusPhase2UpdatedAt;
Vire updatedat

2022-07-08 11:41 UTC, naustra commented on api/src/templates/certificate/index.js
> +  if (!d) d = new Date();
if (!d) error, on continue pas

2022-07-08 14:43 UTC, tangimds requested changes
les tests ne passent pas

2022-07-08 14:56 UTC, naustra commented
Vire getCertificateTemplate si pas utilisé 
Et il faut plus utiliser DATE.NOW() en phase1 non plus. La date de fin à la place.

2022-07-08 14:57 UTC, naustra requested changes

2022-07-08 14:57 UTC, naustra commented on api/src/templates/certificate/index.js
> +  if (!d) return console.error("Pas de date de validation");
Utilise throw "Un nom utile d'erreur" plutôt
Et fait le pour la phase 2 aussi

2022-07-08 15:33 UTC, nicobret commented on api/src/templates/certificate/index.js
> +  if (!d) return console.error("Pas de date de validation");
ok

2022-07-08 17:05 UTC, nicobret commented
> Vire getCertificateTemplate si pas utilisé
C'est encore utilisé pour la génération du diplôme du snu.

> Et il faut plus utiliser DATE.NOW() en phase1 non plus. La date de fin à la place.
Date de fin =  END_DATE_PHASE1 ou bien COHESION_STAY_END ?

2022-07-09 12:52 UTC, naustra commented
> > Vire getCertificateTemplate si pas utilisé
> 
> C'est encore utilisé pour la génération du diplôme du snu.
> 
> > Et il faut plus utiliser DATE.NOW() en phase1 non plus. La date de fin à la place.
> 
> Ok. Pour la date de fin je prends END_DATE_PHASE1 ou bien COHESION_STAY_END ?

Effectivement, mais vu le code, utilise la même logique que pour la phase 2. Si phase 2 finie => SNU validé

2022-07-09 12:59 UTC, naustra commented
> END_DATE_PHASE1
END_DATE_PHASE1

2022-07-10 19:16 UTC, naustra approved these changes

2022-07-10 19:17 UTC, naustra commented
Ça a l'air bien. Je regarde le soucis avec les tests.

2022-07-11 07:17 UTC, merged