Televersement pj etape1
betagouv/service-national-universel pull request #1661
Opened 2022-07-08 14:07 UTC by laurestph

2022-07-11 09:12 UTC, hlecourt requested changes

2022-07-11 09:12 UTC, hlecourt commented on api/src/controllers/application.js
> +router.post("/:id/notify/:template/:documentType/:multipleDocument", passport.authenticate(["referent", "young"], { session: false, failWithError: true }), async (req, res) => {
J'aurais mis ca dans le body pas dans le header

2022-07-11 09:12 UTC, hlecourt commented on api/src/controllers/application.js
> +        const emailTo2 = [{ name: referent.youngFirstName + "fer", lastName: referent.youngLastName, email: "laure@selego.co" }];
Alors c'est pas a toi qu'on envoie les mail + attention au firstname

2022-07-11 09:12 UTC, hlecourt commented on api/src/controllers/application.js
> +      { force: true },
`
```suggestion
```

2022-07-11 09:12 UTC, hlecourt commented on api/src/controllers/application.js
> +          { force: true },
```suggestion
```

2022-07-11 09:12 UTC, hlecourt commented on api/src/controllers/application.js
> +    let cc = isYoung(req.user) ? getCcOfYoung({ template, young }) : "";
```suggestion
    let cc = isYoung(req.user) ? getCcOfYoung({ template, young }) : [];
```

2022-07-11 09:12 UTC, hlecourt commented on api/src/controllers/application.js
> +    if (req.user.role === "young" && req.user._id.toString() !== young?._id.toString()) return res.status(403).send({ ok: false, code: ERRORS.OPERATION_UNAUTHORIZED });
user.role === young n'existe pas, tu voulais verifier quoi ?

2022-07-11 09:12 UTC, hlecourt commented on api/src/controllers/referent.js
> +router.get("/youngFile/:youngId/application/:key/:fileName", passport.authenticate("referent", { session: false, failWithError: true }), async (req, res) => {
Je pense pas que tu te servent de celle la, tu peux la delete

2022-07-11 09:28 UTC, hlecourt commented
Revoir UI niveau jeune voir doc PM

2022-07-11 12:18 UTC, laurestph commented on api/src/controllers/application.js
> +router.post("/:id/notify/:template/:documentType/:multipleDocument", passport.authenticate(["referent", "young"], { session: false, failWithError: true }), async (req, res) => {
yes

2022-07-11 14:11 UTC, hlecourt requested changes

2022-07-11 14:11 UTC, hlecourt commented on api/src/controllers/application.js
> +          type_document: `${multipleDocument === "true" ? translateAddFilesPhase2(type) : translateAddFilePhase2(type)}`,
Revoir la logique des mails jeunes ou ref ou les deux

2022-07-11 14:11 UTC, hlecourt commented on app/src/scenes/missions/components/ModalPJ.js
> +                          //console.log("ferihn", file[0].name);
```suggestion
```

2022-07-11 14:11 UTC, hlecourt commented on lib/constants.js
Enlever la dupli

2022-07-12 07:58 UTC, hlecourt approved these changes
Let's goooooo 🎉

2022-07-12 08:17 UTC, merged