Telechargement contrat
betagouv/service-national-universel pull request #1671
Opened 2022-07-12 15:33 UTC by laurestph

https://www.notion.so/jeveuxaider/c2db10733d2042bf9ca99031085f4e33?v=8230fc34ef204b8fb2450af0c098df59&p=5e31703583fe430dbd49bed5705320c8

2022-07-13 13:45 UTC, nicobret commented on app/src/scenes/missions/viewDesktop.js
>  import { AiOutlineClockCircle } from "react-icons/ai";
import de AiOutlineClockCircle en double

2022-07-13 13:56 UTC, nicobret commented on app/src/scenes/missions/viewDesktop.js
>  import { AiOutlineClockCircle } from "react-icons/ai";
Téléchargement du contrat ok.
Peut-être à améliorer : mettre le curseur en mode hover sur le bouton de téléchargement.

2022-07-14 15:13 UTC, tangimds requested changes
le bloc de contact et le bloc de contract sont collés. pas bon (desktop et mobile)
<img width="374" alt="Screenshot 2022-07-14 at 17 11 29" src="https://user-images.githubusercontent.com/33058720/179015901-d507f005-5f00-422e-bd15-56af26d6b7f2.png">

est ce qu'on pourrait le mettre sur une seule ligne ?
<img width="137" alt="Screenshot 2022-07-14 at 17 12 13" src="https://user-images.githubusercontent.com/33058720/179016093-c7bd1ea6-806a-4a30-8913-10b2d3eba925.png">

2022-07-14 15:13 UTC, tangimds commented on app/src/components/drawer/item.js
> +  //console.log(status);
```suggestion
```

2022-07-14 15:13 UTC, tangimds commented on app/src/scenes/missions/viewDesktop.js
> +                <div className="bg-blue-600 rounded-xl px-2 py-1 flex items-center text-white text-xs " onClick={() => setOpenContractDropdown(!openContractDropdown)}>
cursor-pointer

2022-07-14 15:13 UTC, tangimds commented on app/src/scenes/missions/viewDesktop.js
> +                <div className="bg-blue-600 rounded-xl px-2 py-1 flex items-center text-white text-xs " onClick={() => setOpenContractDropdown(!openContractDropdown)}>
(c'est dailleurs le cas aussi pour les pieces jointes)

2022-07-14 15:13 UTC, tangimds commented on app/src/scenes/missions/viewDesktop.js
> +                <div className="bg-blue-600 rounded-xl px-2 py-1 flex items-center text-white text-xs " onClick={() => setOpenContractDropdown(!openContractDropdown)}>
le bouton est aussi trop etriqué, rajouter du padding (comme le figma)

2022-07-17 12:36 UTC, naustra requested changes
Pourquoi t'as rajouté 3 fichiers différents avec la voiture ?

2022-07-17 13:48 UTC, naustra commented
J'ai fix l'histoire de la voiture c'est bon.

2022-07-17 13:51 UTC, naustra commented
Par contre, le truc de laure. Ça marche pas bien sur mobile : 
<img width="595" alt="CleanShot 2022-07-17 at 15 47 51@2x" src="https://user-images.githubusercontent.com/11462919/179401538-02593bda-f5ee-48b0-a9a8-e091f4d21528.png">
Le en-attente est mis sur le seul ou c'est bon.
Sur Ipad, ça marche pas terrible non plus.

2022-07-17 14:30 UTC, naustra commented
Envoi par mail ne marche pas en local => cc is missing lorsque l'on essaie (Send in Blue n'est pas sync avec le staging, c'est peut être normal)

2022-07-17 14:31 UTC, naustra requested changes

2022-07-17 14:31 UTC, pierre-lebihan commented on app/src/scenes/phase2/desktop/Validated.js
> +/* import Car from "../../../assets/icons/car"; */
Clean stp

2022-07-17 14:31 UTC, pierre-lebihan commented on app/src/scenes/phase2/desktop/Validated.js
> +        {/* <div className="text-xl leading-7 font-bold text-center lg:!text-left mt-10 lg:!mt-0">Mes attestations</div> */}
Clean !

2022-07-17 14:31 UTC, pierre-lebihan commented on app/src/scenes/phase2/mobile/Validated.js
> +        {/* <div className="text-lg leading-7 font-bold text-left">Mes attestations</div> */}
Clean

2022-07-17 14:31 UTC, pierre-lebihan commented on app/src/scenes/phase2/mobile/Validated.js
> +              <strong>{young.firstName},</strong> vous avez validé votre Phase 2&nbsp;!
Obligé ?

2022-07-18 08:06 UTC, nicobret commented on app/src/scenes/phase2/desktop/Validated.js
> +        {/* <div className="text-xl leading-7 font-bold text-center lg:!text-left mt-10 lg:!mt-0">Mes attestations</div> */}
ok

2022-07-18 08:07 UTC, nicobret commented on app/src/scenes/phase2/mobile/Validated.js
> +              <strong>{young.firstName},</strong> vous avez validé votre Phase 2&nbsp;!
Oui, sinon, avec certains prénoms, le "!" se retrouve tout seul sur la 3e ligne (moche).

2022-07-18 08:08 UTC, nicobret commented on app/src/scenes/missions/viewDesktop.js
> +                <div className="bg-blue-600 rounded-xl px-2 py-1 flex items-center text-white text-xs " onClick={() => setOpenContractDropdown(!openContractDropdown)}>
Done.

2022-07-18 08:09 UTC, nicobret commented on app/src/scenes/phase2/desktop/Validated.js
> +/* import Car from "../../../assets/icons/car"; */
Tu l'as fait je crois.

2022-07-18 12:58 UTC, naustra reviewed
Corrigé bug si jeune est adulte

2022-07-19 08:26 UTC, merged