écran annulation de candidature
betagouv/service-national-universel pull request #1680
Opened 2022-07-20 15:08 UTC by nicobret

2022-07-21 13:02 UTC, tangimds requested changes

2022-07-21 13:02 UTC, tangimds commented on app/src/scenes/missions/viewMobile.js
> +    !loading;
?

2022-07-21 13:08 UTC, nicobret commented on app/src/scenes/missions/viewMobile.js
> +    !loading;
J'aurais dû le laisser directement dans le onClick ?

2022-07-22 06:35 UTC, nicobret commented on app/src/scenes/missions/viewMobile.js
> +    !loading;
Oui en fait ça n'avait pas de sens, j'ai modifié.

2022-07-22 09:55 UTC, tangimds requested changes

2022-07-22 09:55 UTC, tangimds commented on app/src/scenes/missions/viewDesktop.js
> +                  !loading &&
pouquoi ne pas en faire un bouton et le disabled quand `loading` est true ?

2022-07-22 09:55 UTC, tangimds commented on app/src/scenes/missions/viewDesktop.js
> +          }}
si on `await` pas, le bouton n'est pas desactivé, et il peut cliquer plusieurs fois dessus (notamment si il a un réseau faible)

2022-07-22 09:55 UTC, tangimds commented on app/src/scenes/missions/viewDesktop.js
> +    updateApplication(APPLICATION_STATUS.CANCEL);
une triste histoire de nomenclature qui traine je pense, donc on ne va pas corriger ici
mais la fonctoin devrait s'appeler `updateApplicationStatus`

idem : `cancelApp` -> `cancelApplication`

2022-07-22 12:38 UTC, nicobret commented on app/src/scenes/missions/viewDesktop.js
> +                  !loading &&
yes

2022-07-22 13:44 UTC, nicobret commented on app/src/scenes/missions/viewDesktop.js
> +          }}
J'await où ?
onConfirm={ async () => { await cancelModal?.onConfirm(); setCancelModal(...) }} ?

2022-07-22 13:44 UTC, nicobret commented on app/src/scenes/missions/viewDesktop.js
> +    updateApplication(APPLICATION_STATUS.CANCEL);
C'est changé, c'était vite fait. Et j'ai viré les fonctions cancelApp et cancelMission, ces étapes ne servant je pense à rien.

2022-07-25 13:39 UTC, tangimds requested changes

2022-07-25 13:39 UTC, tangimds commented on app/src/scenes/missions/viewDesktop.js
> +    updateApplication(APPLICATION_STATUS.CANCEL);
je les vois tujours moi, normal ?

2022-07-25 13:39 UTC, tangimds commented on app/src/scenes/missions/viewDesktop.js
> +          }}
oui

2022-07-25 13:39 UTC, tangimds commented on app/src/scenes/missions/viewDesktop.js
> +          }}
test

2022-07-25 13:39 UTC, tangimds commented on app/src/scenes/missions/viewDesktop.js
> +                  !loading &&
pourquoi le `!loading` est la ?

2022-07-25 13:40 UTC, nicobret commented on app/src/scenes/missions/viewDesktop.js
> +    updateApplication(APPLICATION_STATUS.CANCEL);
oui j'ai pas re push

2022-07-25 14:31 UTC, nicobret commented on app/src/scenes/missions/viewDesktop.js
> +          }}
Ok.

2022-07-25 14:31 UTC, nicobret commented on app/src/scenes/missions/viewDesktop.js
> +    updateApplication(APPLICATION_STATUS.CANCEL);
Bizarre, il me semblait avoir push. J'ai fait un nouveau commit en incluant les mêmes changements à la page mobile.

2022-07-25 14:32 UTC, nicobret commented on app/src/scenes/missions/viewDesktop.js
> +                  !loading &&
Je l'ai viré.

2022-07-26 13:24 UTC, tangimds approved these changes
lets go ! gg

2022-07-26 13:26 UTC, merged