Feat(admin): limiter le nombre de candidatures en attente
betagouv/service-national-universel pull request #1700
Opened 2022-07-27 08:37 UTC by nicobret

https://www.notion.so/jeveuxaider/Phase-2-limitation-des-candidatures-au-niveau-de-la-mission-aae79ce9855e465abbac0796e6ad7c98

2022-07-29 08:03 UTC, tangimds requested changes
1. on ne fait pas la différence entre une mission fermée à la main et une mission fermée parce qu'il y a trop de candidatures ?
2. l'onglet s'appelle pas candidatures ?
<img width="643" alt="Screenshot 2022-07-29 at 09 53 37" src="https://user-images.githubusercontent.com/33058720/181711795-3cc50050-203d-4418-81f8-d3b9cb113e68.png">
3. si on change le nombre de places d'une mission, sa visibilité n'est pas mise a jour si besoin ?
4. quand ya plus de place, on enlève complètement le bouton proposer ? il ne faudrait mieux pas le griser avec une infos expliquant pourquoi ce n'est pas possible ?
<img width="415" alt="Screenshot 2022-07-29 at 09 56 00" src="https://user-images.githubusercontent.com/33058720/181712226-748138a5-b8bc-40b9-abc8-7bace9a2d343.png">
5. pourquoi elle est fermée ? (cf 1.)
<img width="506" alt="Screenshot 2022-07-29 at 09 56 53" src="https://user-images.githubusercontent.com/33058720/181712404-ab34fdeb-09e1-4a72-83ef-12ecbcb6a4a5.png">

2022-07-29 08:03 UTC, tangimds commented on api/src/controllers/application.js
> +async function updateMission(app, fromUser) {
plus de `try..catch` ?

2022-07-29 08:03 UTC, tangimds commented on api/src/controllers/application.js
> +  });
pourquoi faire un `$and`

ca ne marche pas ca 👇 ?
```suggestion
  const placesTaken = await ApplicationObject.countDocuments({
    missionId: mission._id, status: { $in: ["VALIDATED", "IN_PROGRESS", "DONE"] } ,
  });
```

2022-07-29 08:03 UTC, tangimds commented on api/src/controllers/application.js
> +    console.log(`Mission ${mission.id}: total ${mission.placesTotal}, left from ${mission.placesLeft} to ${placesLeft}`);
faudrait peut etre virer ce console log, au moins en prod. qu'en penses tu ?

2022-07-29 08:03 UTC, tangimds commented on api/src/controllers/application.js
> +    $and: [{ missionId: mission._id }, { status: { $in: ["WAITING_VERIFICATION", "WAITING_VALIDATION", "WAITING_ACCEPTATION"] } }],
meme remarque que plus haut, pourquoi le `$and` ?

2022-07-29 08:03 UTC, tangimds commented on api/src/controllers/application.js
> +    $and: [{ missionId: mission._id }, { status: { $in: ["WAITING_VERIFICATION", "WAITING_VALIDATION", "WAITING_ACCEPTATION"] } }],
on ne compte pas les candidatures validées ?
>[PS : évidemment, 1 place est décompter sur la mission une fois qu’elle est en candidature approuvée (puis mission en cours/effectuée/abandonnée)
](https://www.notion.so/jeveuxaider/Phase-2-limitation-des-candidatures-au-niveau-de-la-mission-aae79ce9855e465abbac0796e6ad7c98#321398ec4c3e4c62b527e29486a68e26)

2022-07-29 08:03 UTC, tangimds commented on admin/src/scenes/missions/edit.js
> +                        {pendingApplications >= values.placesLeft * 5 ? (
pourquoi remettre cette logique ici ?

2022-07-29 08:03 UTC, tangimds commented on admin/src/scenes/missions/edit.js
> +                              Seuil de candidatures en attente atteint : la mission est <strong>fermée</strong> aux candidatures.
peut etre inciter a allez traiter les candidatures reçues ? comme sur la maquette par exemple ?

2022-07-29 08:03 UTC, tangimds commented on admin/src/scenes/missions/edit.js
> +                        )}
tout ca etait deja la avant mais si j'avais vu ca j'aurais pas accepté.
plutot que de conditionner tous les styles un a un, pourquoi ne pas faire 
```javascript
values.visibility === "VISIBLE"
? <div>mon truc en mode ouvert</div>
: <div>mon truc en mode fermé</div>
```

2022-07-29 08:08 UTC, nicobret commented on api/src/controllers/application.js
> +async function updateMission(app, fromUser) {
Je le remets (il a dégagé lors d'un copier/coller malencontreux... mb).

2022-07-29 08:41 UTC, nicobret commented on api/src/controllers/application.js
> +    $and: [{ missionId: mission._id }, { status: { $in: ["WAITING_VERIFICATION", "WAITING_VALIDATION", "WAITING_ACCEPTATION"] } }],
Si mais c'est la propriété placesLeft qui s'en charge déjà.

2022-07-29 09:01 UTC, nicobret commented on admin/src/scenes/missions/edit.js
> +                              Seuil de candidatures en attente atteint : la mission est <strong>fermée</strong> aux candidatures.
Tout à fait, j'ai oublié de faire le lien. Done.

2022-07-29 09:03 UTC, nicobret commented on api/src/controllers/application.js
> +    console.log(`Mission ${mission.id}: total ${mission.placesTotal}, left from ${mission.placesLeft} to ${placesLeft}`);
Fait.

2022-07-29 09:57 UTC, nicobret commented on admin/src/scenes/missions/edit.js
> +                        )}
Done.

2022-07-29 09:58 UTC, nicobret commented on api/src/controllers/application.js
> +  });
Si, c'est changé.

2022-07-29 09:59 UTC, nicobret commented on admin/src/scenes/missions/edit.js
> +                        {pendingApplications >= values.placesLeft * 5 ? (
Pour que l'admin ne puisse pas rouvrir manuellement les candidatures si il y en a trop en attente.

2022-07-29 10:34 UTC, nicobret commented
> 1. on ne fait pas la différence entre une mission fermée à la main et une mission fermée parce qu'il y a trop de candidatures ?

Les deux correspondent à la propriété "visibility" de la mission, mais dans un cas l'admin peut ouvrir ou fermer et dans l'autre ça se fait automatiquement. Je peux essayer d'être plus clair dans l'interface. Tu penses qu'il faut rajouter une propriété "tooManyApplications" dans le model ?

> 2. l'onglet s'appelle pas candidatures ?

Effectivement, je renomme.

> 3. si on change le nombre de places d'une mission, sa visibilité n'est pas mise a jour si besoin ?

Je ne crois que ce soit prévu, je peux le rajouter dans le controller de mission.

> 4. quand ya plus de place, on enlève complètement le bouton proposer ? il ne faudrait mieux pas le griser avec une infos expliquant pourquoi ce n'est pas possible ?

C'était la PR d'Hugo ça, il a choisit de masquer l'onglet comme solution temporaire comme ça en attendant une refonte plus complète des onglets de mission.

2022-07-29 15:58 UTC, tangimds commented on api/src/controllers/application.js
> +    $and: [{ missionId: mission._id }, { status: { $in: ["WAITING_VERIFICATION", "WAITING_VALIDATION", "WAITING_ACCEPTATION"] } }],
ok

2022-07-29 16:07 UTC, tangimds commented on admin/src/scenes/missions/edit.js
> +                        )}
non, c'est pire qu'avant.
le but de faire ça est d'éviter de mettre des opérations ternaires dans le dom ou meme dans les classnames
parfois c'est pas utile de scinder le trucs en deux mais la tous les `values.visibility === "VISIBLE" ? ... : ... ` rende le code illisible et non maintenable

2022-07-29 16:10 UTC, tangimds commented
1. tu es en train de me dire "les deux sont liés au meme champs dans le model, mais ce n'est pas la même chose". pourquoi ne pas faire un autre champs distinct alors ? et cloisonner les deux fonctionnements (meme si le résultat est le meme, ce n'est pas la meme fonctionnalité)

3. c'est pas une question de prévu ou non. Que se passe-t-il si on le fait ? l'ont-ils pris en compte ? l'as tu challengé ? l'as tu identifé ?

4. mmh ok, car c'était trop galère disabled, les conséquences sont ok ? quand est ce qu'on fait la refonte ? @hlecourt

2022-08-01 14:54 UTC, hlecourt commented on admin/src/scenes/missions/view/wrapper.js
> +            mission.pendingApplications < mission.placesLeft * 5 ? (
Tu crise pas l'onglet ducoup ?

2022-08-01 14:54 UTC, hlecourt commented on admin/src/scenes/missions/view/wrapper.js
> +            mission.pendingApplications < mission.placesLeft * 5 ? (
Juste en mettant le tab mais il fait rien

2022-08-01 14:54 UTC, hlecourt commented on api/src/controllers/application.js
> +async function updateMission(app, fromUser) {
why ?

2022-08-01 14:57 UTC, nicobret commented on api/src/controllers/application.js
> +async function updateMission(app, fromUser) {
Parce que maintenant elle n'update pas que le nb de places dispo mais aussi celui des candidatures en cours.

2022-08-01 15:33 UTC, nicobret commented on admin/src/scenes/missions/view/wrapper.js
> +            mission.pendingApplications < mission.placesLeft * 5 ? (
Oui c'est mieux, fait.

2022-08-02 09:53 UTC, hlecourt reviewed
Je test

2022-08-02 09:53 UTC, hlecourt commented on api/src/controllers/application.js
> +async function updateMission(app, fromUser) {
Yes mais pourquoi la passer en function ? Meme si ca n'a aucun impact ^^

2022-08-02 09:56 UTC, nicobret commented
Ah euh jsp ahah. En fait je l'ai retapée à la main et j'avais pas réalisé que j'avais changé ça.

2022-08-02 09:57 UTC, nicobret commented on api/src/controllers/application.js
> +async function updateMission(app, fromUser) {
Ah euh jsp ahah. En fait je l'ai retapée à la main et j'avais pas réalisé que j'avais changé ça.

2022-08-02 14:23 UTC, hlecourt reviewed
Y'a un propose mission depuis la page volontaire phase 2 a prendre en compte aussi

2022-08-02 14:23 UTC, hlecourt commented on admin/src/scenes/missions/view/index.js
> +        <SentryRoute path="/mission/:id/youngs" component={() => <Youngs mission={mission} updateMission={fetchMission} applications={applications} />} />
Pourquoi on passe plus le update application ?

2022-08-02 14:25 UTC, nicobret commented on admin/src/scenes/missions/view/index.js
> +        <SentryRoute path="/mission/:id/youngs" component={() => <Youngs mission={mission} updateMission={fetchMission} applications={applications} />} />
Dans le composant parent il y a déjà un useEffect qui va refetch les applications quand la mission est mise a jour. ça faisait double emploi (et double render).

2022-08-02 14:40 UTC, nicobret commented
> Y'a un propose mission depuis la page volontaire phase 2 a prendre en compte aussi

Ah bien vu ! Filtre ajouté.

2022-08-02 14:44 UTC, hlecourt commented on admin/src/scenes/missions/view/index.js
> +        <SentryRoute path="/mission/:id/youngs" component={() => <Youngs mission={mission} updateMission={fetchMission} applications={applications} />} />
ok

2022-08-03 08:16 UTC, hlecourt approved these changes
Yeeesssss 🎉

2022-08-03 09:17 UTC, merged