feat(admin): Add a modal to reattribute missions in case of delete
betagouv/service-national-universel pull request #1716
Opened 2022-08-02 12:59 UTC by naustra

2022-08-02 13:32 UTC, naustra reviewed
Il faut remplacer les toastr Structure_linked et ce profil a été supprimé par 2 nouvelles modals.

2022-08-02 15:54 UTC, hlecourt reviewed
Je recheck demain matin

2022-08-02 15:54 UTC, hlecourt commented on admin/src/components/modals/ModalChangeTutor.js
> +            <th className="py-3 text-left pl-4">Mission</th>
plutot mettre un gap au niveau du <tr>

2022-08-02 15:54 UTC, hlecourt commented on admin/src/components/modals/ModalChangeTutor.js
> +            <span style={{ color: "#cbd5e0", marginRight: 5 }}>Du</span> {formatStringDateTimezoneUTC(hit.startAt)}
className

2022-08-02 15:54 UTC, hlecourt commented on admin/src/components/modals/ModalChangeTutor.js
> +            <span style={{ color: "#cbd5e0", marginRight: 5 }}>Au</span> {formatStringDateTimezoneUTC(hit.endAt)}
className

2022-08-02 15:54 UTC, hlecourt commented on admin/src/scenes/structure/edit.js
> -      if (!ok && code === "LINKED_STRUCTURE") return toastr.error(translate(code), "Ce responsable est le dernier responsable de la structure.");
Pourquoi tu enleves ce message ?

2022-08-02 15:54 UTC, hlecourt commented on admin/src/scenes/structure/view/details.js
> -      if (!ok && code === "LINKED_STRUCTURE") return toastr.error(translate(code), "Ce responsable est le dernier responsable de la structure.");
Idem

2022-08-02 15:54 UTC, hlecourt commented on admin/src/scenes/team/panel.js
> -      if (!ok && code === "LINKED_STRUCTURE") return toastr.error(translate(code), "Ce responsable est le dernier responsable de la structure.");
Idem

2022-08-02 15:54 UTC, hlecourt commented on api/src/controllers/referent.js
> +        const structures = await StructureModel.find({ $or: [{ networkId: String(req.user.structureId) }, { _id: String(req.user.structureId) }] });
Sympa ca mdr

2022-08-03 08:50 UTC, hlecourt requested changes
Voir slack

2022-08-03 08:57 UTC, naustra commented on admin/src/components/modals/ModalChangeTutor.js
> +            <th className="py-3 text-left pl-4">Mission</th>
ça me demande de tout passer en grid

2022-08-03 16:27 UTC, naustra commented on admin/src/components/modals/ModalChangeTutor.js
> +            <th className="py-3 text-left pl-4">Mission</th>
J'ai fait avec margin auto

2022-08-03 16:28 UTC, naustra commented on admin/src/scenes/structure/edit.js
> -      if (!ok && code === "LINKED_STRUCTURE") return toastr.error(translate(code), "Ce responsable est le dernier responsable de la structure.");
Ça peut pas arriver ici et comme je dois foutre des modals partout. Je préfère virer ici plutot.

2022-08-04 09:54 UTC, hlecourt requested changes
Y'a des modale manquante

2022-08-04 09:54 UTC, hlecourt commented on api/src/controllers/mission.js
> +      mission.set({ ...mission, tutorId, tutorName });
pas besoin de remettre la mission ici

2022-08-04 09:54 UTC, hlecourt commented on admin/src/scenes/structure/view/details.js
> -      if (!ok && code === "LINKED_STRUCTURE") return toastr.error(translate(code), "Ce responsable est le dernier responsable de la structure.");
il manque le modale si structure liée sur la structure pour quasi tou les ecrans modifié

2022-08-04 12:43 UTC, pierre-lebihan commented on api/src/controllers/mission.js
> +      mission.set({ ...mission, tutorId, tutorName });
Pas compris

2022-08-04 12:44 UTC, naustra commented on admin/src/scenes/structure/view/details.js
> -      if (!ok && code === "LINKED_STRUCTURE") return toastr.error(translate(code), "Ce responsable est le dernier responsable de la structure.");
Structure lié peut pas arriver. On disable le bouton.

2022-08-04 13:32 UTC, hlecourt commented on api/src/controllers/mission.js
> +      mission.set({ ...mission, tutorId, tutorName });
```suggestion
      mission.set({ tutorId, tutorName });
```

2022-08-09 11:33 UTC, hlecourt commented on admin/src/components/modals/ModalChangeTutor.js
> +function Table(checkboxRef, onClickMainCheckBox, data, responsables, setMissionsSelected, forceUpdate, missionsSelected) {
Sortir la logique de ce composant React select et table

2022-08-09 11:33 UTC, hlecourt commented on admin/src/components/modals/ModalChangeTutor.js
> +import React, { useEffect, useReducer, useState } from "react";
Deplacer ce modale dans structure

2022-08-09 11:33 UTC, hlecourt commented on admin/src/components/modals/ModalReferentDeleted.js
> +        <AiOutlineCheckCircle size={40} color={"green"} />
ClassName sur les react icon

2022-08-09 11:40 UTC, naustra commented on admin/src/components/modals/ModalChangeTutor.js
> +import React, { useEffect, useReducer, useState } from "react";
non, utilisé ds utilisateur aussi.

2022-08-09 12:55 UTC, hlecourt commented on admin/src/components/modals/ModalChangeTutor.js
> +                      const responsablesOptions = responsables.map((e) => ({ label: e.firstName + " " + e.lastName, value: e._id.toString() }));
Tu peux pas le faire directement aux chargement ?

2022-08-09 14:21 UTC, hlecourt approved these changes
YEEEEEE 🎉

2022-08-09 14:22 UTC, merged