chore(all): Renouveau de la politique de mot de passe
betagouv/service-national-universel pull request #1718
Opened 2022-08-02 15:26 UTC by naustra

2022-08-02 16:27 UTC, naustra commented on api/src/auth.js
> -      const match = config.ENVIRONMENT === "development" || (await user.comparePassword(password));
A remettre apres avoir testé

2022-08-04 13:45 UTC, hlecourt requested changes
J'ai pas compris comment tu geres le +24h

2022-08-04 13:45 UTC, hlecourt commented on admin/src/scenes/auth/signin.js
> +  console.log("🚀 ~ file: signin.js ~ line 22 ~ Signin ~ tooManyRequests", tooManyRequests);
```suggestion
```

2022-08-04 13:45 UTC, hlecourt commented on api/src/crons/index.js
> +  cron.schedule("0 1 * * *", () => {
Ca donne tous les combien ca ?

2022-08-04 13:45 UTC, hlecourt commented on api/src/auth.js
> -      const match = config.ENVIRONMENT === "development" || (await user.comparePassword(password));
Faut pas oublié !

2022-08-04 13:45 UTC, hlecourt commented on admin/src/scenes/auth/signin.js
> +                          Vous avez atteint le maximum de tentatives de connexion autorisées. Réessayez {tooManyRequests.date !== "-" ? `à ${tooManyRequests.date}.` : "demain."}
Je vois pas ou tu set le "-"

2022-08-04 13:45 UTC, hlecourt commented on api/src/models/young.js
> +  nextLoginAttemptIn: {
Ajouter ce champs dans les champs ignorer voir ligne 1537

2022-08-04 14:36 UTC, pierre-lebihan commented on admin/src/scenes/auth/signin.js
> +                          Vous avez atteint le maximum de tentatives de connexion autorisées. Réessayez {tooManyRequests.date !== "-" ? `à ${tooManyRequests.date}.` : "demain."}
C'est ce que sort la fonction par défaut si la date est undefined

2022-08-04 14:40 UTC, hlecourt commented
C'est pas une chore c'est une secu par exemple

2022-08-04 14:42 UTC, naustra commented on api/src/crons/index.js
> +  cron.schedule("0 1 * * *", () => {
à 1h du mat tous les jours

2022-08-04 14:43 UTC, naustra commented on api/src/crons/index.js
> +  cron.schedule("0 1 * * *", () => {
On peut limiter à 12 avant la reset. Ça fera bien au max 24 tentatives en 24h

2022-08-04 14:44 UTC, naustra commented on api/src/auth.js
> -      const match = config.ENVIRONMENT === "development" || (await user.comparePassword(password));
Oh oh oh ! 
Resté positif dans nos têtes !
Faut pas oublier !
Oh oh oh !

2022-08-04 14:49 UTC, naustra commented on api/src/models/young.js
> +  nextLoginAttemptIn: {
Je l'ai déjà fait

2022-08-05 10:03 UTC, hlecourt approved these changes
🎉

2022-08-05 10:04 UTC, merged