fix(admin): Front  admin screen phase2 - missions candidatée
betagouv/service-national-universel pull request #1795
Opened 2022-09-15 15:49 UTC by Melinapgt

2022-09-15 16:19 UTC, hlecourt requested changes
<img width="338" alt="image" src="https://user-images.githubusercontent.com/50077368/190455632-c6ae772f-649d-4dfb-b7dc-f027fe628c9b.png">

C'est une première passe je regarderai demain en detail

2022-09-15 16:19 UTC, hlecourt commented on admin/src/scenes/volontaires/view/applicationList2.js
> +  console.log("appliction==>", applications);
```suggestion
```

2022-09-15 16:19 UTC, hlecourt commented on admin/src/scenes/volontaires/view/applicationList2.js
> +    <div className="relative  w-full  bg-white shadow-nina rounded-xl p-4 border-[1px] border-[#ffffff] hover:border-gray-200 drop-shadow-md mb-4">
```suggestion
    <div className="relative  w-full  bg-white shadow-nina rounded-xl p-4 border-[1px] border-white hover:border-gray-200 drop-shadow-md mb-4">
```
plus simple je pense !?

2022-09-15 16:19 UTC, hlecourt commented on admin/src/scenes/volontaires/view/applicationList2.js
> +const CopyLink = styled.button`
tout le styled div faut l'enlever

2022-09-15 16:20 UTC, Melinapgt commented on admin/src/scenes/volontaires/view/applicationList2.js
> +  console.log("appliction==>", applications);
Je viens de le voir celui la en lançant ma console 😅

2022-09-16 14:09 UTC, tangimds commented
c'est une premiere étape ?
on ne mets pas les préférences dans un onglet ?
on ne remonte pas les "Mes outils pour aider mon volontaire" ?

2022-09-16 14:19 UTC, tangimds requested changes

2022-09-16 14:19 UTC, tangimds commented on admin/src/components/ExportXlsx2.js
> +      </button>
pourquoi créer un autre composant global pour ca ?

2022-09-16 14:19 UTC, tangimds commented on admin/src/components/selectStatusApplication2.js
> +            <Chevron color={APPLICATION_STATUS_COLORS[application.status]} />
pourquoi le chevron est orange ?
<img width="93" alt="Screenshot 2022-09-16 at 16 15 12" src="https://user-images.githubusercontent.com/33058720/190660087-0fe65bf2-ce01-498e-acdd-a2197244dedb.png">

2022-09-16 14:19 UTC, tangimds commented on admin/src/scenes/volontaires/view/applicationList2.js
> +      </div>
pourquoi ?

2022-09-16 14:19 UTC, tangimds commented on admin/src/scenes/volontaires/view/applicationList2.js
> +              {environment === "production" ? (
pourquoi gérer l'environment ici ?
on va tout retoucher, si on mélange tout, on va se foirer c'est sur

2022-09-16 14:19 UTC, tangimds commented on admin/src/scenes/volontaires/view/phase2.js
> +          {environment === "production" ? <ApplicationList young={young} onChangeApplication={onChange} /> : <ApplicationList2 young={young} onChangeApplication={onChange} />}
je serais pour faire ca mais directement au niveau du ficheir phase2 je pense. obn peut en profiter pour cleaner et mieux ranger les doc (tout mettre dans un dossier phase2 par exemple)

2022-09-16 14:19 UTC, tangimds commented on lib/translation.js
> +      return "Candidature en attente";
je ne suis pas sur que ce changement de wording soit a faire côté admin

2022-09-19 16:56 UTC, tangimds commented on admin/src/components/ExportXlsx.js
> +      <button className="bg-write text-blue-600 border-blue-600 border-[1px] font-ubuntu text-sm rounded-lg p-2" onClick={onClick}>
as tu vérifié l'impact que cette modif a eu sur les utilisations de ce composant ?

<img width="390" alt="Screenshot 2022-09-19 at 18 47 39" src="https://user-images.githubusercontent.com/33058720/191070258-47f50ddb-f2fb-4bfa-96f7-4d488bb9ff8d.png">

2022-09-19 16:56 UTC, tangimds commented on admin/src/components/Chevron.js
> +  margin-left: 10px;
as tu vérifié l'impact que cette modif a eu sur les utilisations de ce composant ?

2022-09-19 16:56 UTC, tangimds commented on admin/src/scenes/volontaires/view/phase2bis/preferences.js
> +import React from "react";
je suppose que ce n'est pas fini ?

2022-09-19 16:56 UTC, tangimds commented on admin/src/scenes/volontaires/view/phase2bis/phase2Bis.js
> +          </div>
non

2022-09-19 16:56 UTC, tangimds commented on admin/src/scenes/volontaires/view/phase2bis/phase2Bis.js
> +                    </div>
trop compliqué, je ne comprends pas ce qu'il se passe ?
la settingPage est une page en particulier ?
on ne peux pas le gérer plus facilement ?

il n y a nul part dans l'app quelque chose de similaire ?

2022-09-19 16:56 UTC, tangimds commented on admin/src/scenes/volontaires/view/phase2.js
> +import { environment } from "../../../config";
ca sert a quoi ?

2022-09-19 16:56 UTC, tangimds commented on admin/src/scenes/volontaires/view/phase2.js
> +import ApplicationList2 from "./phase2bis/applicationList2";
ca sert a quoi ?

2022-09-19 16:56 UTC, tangimds commented on lib/translation.js
> +      return "Candidature en attente";
?

2022-09-19 16:57 UTC, tangimds requested changes
pas mal de retour, je pense qu'il faut que tu utilises plus le code qui est déjà présent, pour éviter de réinventer la roue à chaque fois.

on peut se call demain ?

2022-09-20 14:23 UTC, tangimds requested changes

2022-09-20 14:23 UTC, tangimds commented on admin/src/scenes/volontaires/view/phase2bis/phase2Bis.js
> +`;
on n'tulise plus les styledcomponents

2022-09-20 14:23 UTC, tangimds commented on admin/src/scenes/volontaires/view/phase2bis/preferences.js
> +                  {young.mobilityNearRelative === "true" ? <img src={CheckboxInput} /> : <img src={CheckboxUnchecked} />}
non, pourquoi ne pas utiliser la checkbox directement ?

2022-09-20 14:24 UTC, tangimds commented on lib/translation.js
> +      return "Candidature en attente";
je ne pense pas qu'il faut changer la trad ici ?

2022-09-21 07:42 UTC, tangimds approved these changes
yeah lets go !

2022-09-21 07:53 UTC, merged