feat(app): upload documents step for inscription 2023
betagouv/service-national-universel pull request #1867
Opened 2022-10-06 10:51 UTC by nicobret

2022-10-07 13:11 UTC, naustra commented on app/src/services/api.js
> +  uploadFile(path, arr, category, date) {
expirationDate

2022-10-07 15:43 UTC, pierre-lebihan commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +
capture

2022-10-07 15:43 UTC, pierre-lebihan commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +        setError({ text: `Une erreur s'est produite`, subText: code ? translate(code) : "" });
capture

2022-10-07 15:43 UTC, pierre-lebihan commented on api/src/controllers/young/documents.js
> +      const { error: bodyError, value: body } = Joi.object({
Sans required dans JOi, ce code ne sert a rien je crois.
Mais si tu le mets, tu vas casser d'autres export

2022-10-07 15:43 UTC, pierre-lebihan commented on api/src/controllers/young/documents.js
> +      const { error: bodyError, value: body } = Joi.object({
Mettre un objet body dans un objet body, c'est pas ouf

2022-10-07 15:43 UTC, pierre-lebihan commented on api/src/controllers/young/documents.js
> +      const { error: bodyError, value: body } = Joi.object({
Pas de stripUnknown

2022-10-07 15:43 UTC, pierre-lebihan commented on api/src/controllers/young/documents.js
> +        console.error(bodyError);
capture

2022-10-07 15:43 UTC, pierre-lebihan commented on api/src/controllers/young/inscription2023.js
> +    if (error) return res.status(400).send({ ok: false, code: ERRORS.INVALID_PARAMS });
Donc la le jeune recevra un mail avec ses parents en copie et les parents recevront un mail juste pour eux.

Faut pas enlever les parents du mail que reçoit le jeune du coup ?

2022-10-07 15:43 UTC, pierre-lebihan commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +    const dotted = fileName.split(".");
Non, on peut mettre des points au milieu de ses fichiers
Utilise filetype.extenstion plutot

2022-10-07 15:43 UTC, pierre-lebihan commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +    const dotted = fileName.split(".");
https://github.com/jshttp/mime-types#mimeextensiontype

2022-10-07 15:43 UTC, pierre-lebihan commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +    const dotted = fileName.split(".");
mime.extension

2022-10-07 15:43 UTC, pierre-lebihan commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +      for (let index = 0; index < Object.keys(files).length; index++) {
C'est lourd de gérer ça dans le front. C'est voulu ou pas ? On peut pas faire toute les vérifs de fichier en unifié dans le front ?
Comment fait google drive ?
Mets ça dans des fonctions séparés au moins.

2022-10-07 15:45 UTC, naustra commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +        await api.post(`/young/inscription2023/${young._id}/emailtoparent/${SENDINBLUE_TEMPLATES.young.OUTDATED_ID_PROOF}`, {
On est sur que c'est pas mieux de faire une nouvelle route pour les parents. On devrait faire un SENDINBLUE_TEMPLATES.parent.XXX pour ces mails spécifiques

2022-10-07 15:45 UTC, naustra reviewed
heho

2022-10-10 07:40 UTC, nicobret commented on app/src/services/api.js
> +  uploadFile(path, arr, category, date) {
Done.

2022-10-10 07:42 UTC, nicobret commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +
Done.

2022-10-10 07:43 UTC, nicobret commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +        setError({ text: `Une erreur s'est produite`, subText: code ? translate(code) : "" });
Done.

2022-10-10 07:47 UTC, nicobret commented on api/src/controllers/young/documents.js
> +        console.error(bodyError);
Done.

2022-10-10 08:43 UTC, nicobret commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +      for (let index = 0; index < Object.keys(files).length; index++) {
Tout ce qui est upload de fichiers j'ai repris les fonctions telles que deja presentes sur le site. il y a peut-etre mieux a faire effectivement mais je crois que la leçon de cet été c'est qu'il ne faut plus chercher à réinventer l'upload sur la plate-forme ! :D (en tout cas pas cette semaine)
Je mets ça dans une fonction séparée mais je touche pas la logique.

2022-10-10 08:50 UTC, nicobret commented on api/src/controllers/young/documents.js
> +      const { error: bodyError, value: body } = Joi.object({
Stripunknown ajouté.
Pour le body dans le body c'est pas top en effet mais c'est la fonction d'upload qui est comme ça (code de raph), j'ai peur de la casser en enlevant des choses.

2022-10-10 10:06 UTC, nicobret commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +        await api.post(`/young/inscription2023/${young._id}/emailtoparent/${SENDINBLUE_TEMPLATES.young.OUTDATED_ID_PROOF}`, {
J'ai tout mis dans la meme route.

2022-10-10 10:15 UTC, nicobret commented on api/src/controllers/young/inscription2023.js
> +    if (error) return res.status(400).send({ ok: false, code: ERRORS.INVALID_PARAMS });
Normalement le jeune ne reçoit pas de mail à cette étape.

2022-10-10 11:00 UTC, nicobret commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +    const dotted = fileName.split(".");
Done. Mais en fait vu qu'il y a deja une verification du type de fichier dans l'input et qu'on fait une vraie verif en back a partir du buffer, j'ai envie de supprimer notre verif custom en front : je crois ça ne fait rien de plus que le accept="" du <input> et ça alourdit le code.

2022-10-10 11:01 UTC, nicobret commented
J'ai répondu à tes comments + ajouté le bouton back, ajouté la navbar et réglé le pb d'affichage de la liste des fichiers. J'ai pas créé de nouvelle étape par contre, ça ne me semblait pas nécessaire. Pour l'affichage du sticky button on devrait peut-etre demander son avis à Nina ?

2022-10-10 12:52 UTC, naustra commented on api/src/controllers/young/documents.js
> +        console.error(bodyError);
fe

2022-10-10 13:46 UTC, naustra requested changes

2022-10-10 13:46 UTC, pierre-lebihan commented on api/src/controllers/cohort-session.js
> -        dates: "du 5 au 17 juillet",
17 non compris ?

2022-10-10 13:46 UTC, naustra commented on api/src/controllers/young/documents.js
> +      const { error: bodyError, value: body } = Joi.object({
Désolé mais je vois pas ou est réutilisé ce body après.
Pas de require() alors ?

2022-10-10 13:46 UTC, naustra commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +      console.log("LEZGOOOO");
LEZ GOOOO ? 🤔

2022-10-10 13:46 UTC, naustra commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +      console.log("🚀 ~ file: stepDocuments.js ~ line 113 ~ onSubmit ~ e", e);
console

2022-10-10 13:46 UTC, naustra commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +    console.log("🚀 ~ file: stepDocuments.js ~ line 32 ~ isFileSupported ~ type", type);
log

2022-10-10 13:46 UTC, naustra commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +      capture("FILE_CORRUPTED");
On capture déja ds le back, je suppose que c'est suffisant

2022-10-10 13:46 UTC, naustra commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +    if (!res.ok) {
En cas de fichier corrompu, on va passer dans les 2 if l'un apres l'autre. On aura a peine. le temps de voir le message d'erreur

2022-10-10 13:46 UTC, naustra commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +        await api.post(`/young/${young._id}/email/${SENDINBLUE_TEMPLATES.parent.OUTDATED_ID_PROOF}`, {
if (!ok) ?

2022-10-10 13:46 UTC, naustra commented on app/src/services/api.js
> +    for (const e of formData) console.log(e);
console log

2022-10-10 14:01 UTC, nicobret commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +      console.log("LEZGOOOO");
oups

2022-10-10 14:01 UTC, nicobret commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +      console.log("🚀 ~ file: stepDocuments.js ~ line 113 ~ onSubmit ~ e", e);
viré

2022-10-10 14:01 UTC, nicobret commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +    console.log("🚀 ~ file: stepDocuments.js ~ line 32 ~ isFileSupported ~ type", type);
viré

2022-10-10 14:20 UTC, nicobret commented on api/src/controllers/cohort-session.js
> -        dates: "du 5 au 17 juillet",
17 compris.

2022-10-10 14:26 UTC, nicobret commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +        await api.post(`/young/${young._id}/email/${SENDINBLUE_TEMPLATES.parent.OUTDATED_ID_PROOF}`, {
Ajouté.

2022-10-10 14:26 UTC, nicobret commented on app/src/services/api.js
> +    for (const e of formData) console.log(e);
Viré.

2022-10-10 14:27 UTC, nicobret commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +    if (!res.ok) {
Corrigé.

2022-10-10 14:27 UTC, nicobret commented on app/src/scenes/inscription2023/mobile/stepDocuments.js
> +      capture("FILE_CORRUPTED");
Ok.

2022-10-11 09:00 UTC, merged