chore(app): help section inscription
betagouv/service-national-universel pull request #1871
Opened 2022-10-06 13:51 UTC by Melinapgt

2022-10-06 14:30 UTC, hlecourt requested changes

2022-10-06 14:30 UTC, hlecourt commented on app/src/scenes/inscription2023/components/Help.js
> +      <div onClick={() => {}}>
Rajoute le vers la base de connaissance mais pas public

2022-10-07 07:05 UTC, hlecourt commented on app/src/scenes/inscription2023/components/Help.js
> +      <a href={"https://support.snu.gouv.fr/base-de-connaissance/"} target="_blank" rel="noreferrer" className="hover:text-[#161616]">
Utilise appURL du config

2022-10-07 07:19 UTC, Melinapgt commented on app/src/scenes/inscription2023/components/Help.js
> +      <a href={"https://support.snu.gouv.fr/base-de-connaissance/"} target="_blank" rel="noreferrer" className="hover:text-[#161616]">
fait, mais pour le moment comme hier renvoi sur la page inscription

2022-10-07 12:34 UTC, merged