feat(app): Correction stepEligibilite
betagouv/service-national-universel pull request #1970
Opened 2022-10-25 15:25 UTC by naustra

2022-10-26 15:31 UTC, hlecourt requested changes
C'est rigolo l'alignement + il manque le input en rouge 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/50077368/198067383-c10f8e12-2e6a-47ff-9f3a-78bfc0261ffe.png">
<img width="854" alt="image" src="https://user-images.githubusercontent.com/50077368/198067668-e1add6ed-1c0c-4daf-b028-141a537732ab.png">

Pas besoin d'afficher cette modal si il est toujours eligible sur le meme sejour 
<img width="861" alt="image" src="https://user-images.githubusercontent.com/50077368/198068616-83cce360-26bb-4009-a9c5-b73a3288923a.png">

2022-10-26 15:31 UTC, hlecourt commented on api/src/controllers/young/inscription2023.js
> +    if (!canUpdateYoungStatus({ body: value, current: young })) return res.status(403).send({ ok: false, code: ERRORS.OPERATION_UNAUTHORIZED });
Faire le check apres la correction des erreurs possible changement de statut

2022-10-26 15:31 UTC, hlecourt commented on app/src/app.js
> +            {environment !== "production" ? <SentryRoute path="/noneligible" component={NonEligible} /> : null}
pourquoi tu limites a la prod ? un jeune nous elegible doit toujours arriver ici

2022-10-26 15:31 UTC, hlecourt commented on app/src/scenes/inscription2023/desktop/correction/stepEligibilite.js
> +      return history.push("/home");
push("/") suffit

2022-10-27 09:32 UTC, naustra commented
On n'affiche pas la modale si le séjour est toujours valide, c'est bon

2022-10-28 14:15 UTC, merged