feat(admin): refonte inscription par référent
betagouv/service-national-universel pull request #2035
Opened 2022-11-10 16:44 UTC by guiTheret

2022-11-14 11:10 UTC, hlecourt requested changes
- Formik, on ne l'utilise plus on essaie de s'en passer
- On utilise plus non plus le styled.div (Box, Wrapper...), use tailwind
- Revoir ta config prettier / eslint

2022-11-14 11:10 UTC, hlecourt commented on admin/src/scenes/volontaires/create.js
> +      capture(res.code);
capture non importé

2022-11-15 14:31 UTC, rap2hpoutre reviewed
Cool! Quelques remarques :


Pas sûr qu'on ait besoin de `.editorconfig`

J'ai ce bug quand je valide: 
<img width="414" alt="Capture d’écran 2022-11-15 à 14 50 12" src="https://user-images.githubusercontent.com/1575946/201936000-bef35a35-b825-4a2f-9484-10857ebf7657.png">

Si je clique sur "non" sur la vérification d'adresse  ça me dit quand meme que c'est bon : 

<img width="514" alt="Capture d’écran 2022-11-15 à 14 52 49" src="https://user-images.githubusercontent.com/1575946/201936589-99bae242-8c17-4194-adf8-8a8fc8294667.png">

Je peux pas écrire dans "nature de l'aménagement spécifique"

<img width="509" alt="Capture d’écran 2022-11-15 à 15 01 05" src="https://user-images.githubusercontent.com/1575946/201938465-a132e111-cdc3-421e-88d2-c4c6c2d25394.png">

Quand situation est vide, je peux quand même remplir un établissement

<img width="554" alt="Capture d’écran 2022-11-15 à 15 02 22" src="https://user-images.githubusercontent.com/1575946/201938732-4d9c69f8-7ade-4846-b06b-50c23537527d.png">

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/components/Field.js
> + */
Je ne vois pas "mode"

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/components/Field.js
> +  if (type === "date") {
If type === date tout est différent, je pense que ça allégerait chaque composant de séparer vu que ça n'a à peu près rien à voir, ça évite un gros if.

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/components/Field.js
> +  }
J'ai pas compris tout ça, ça a un impact?

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/components/SimpleSelect.js
> +export default function SimpleSelect({ value, name, transformer, options, onChange, filterOnType }) {
- On n'avait pas déjà des composants ailleurs pour ça ? Autrement dit, est-ce qu'on peut juste changer le style d'un composant sans recréer un moteur de gestion de select?
- Est-ce qu'il est navigable au clavier ? (pas important vu l'état de l'accessibilité mais toujours à garder en tête).

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/components/SimpleSelect.js
> +    console.log("value change: ", value);
```suggestion
```

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/components/SimpleSelect.js
> +  }, []);
Ça semble un peu beaucoup, ça vient d'où ce bout de code ?

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/components/SimpleSelect.js
> +    console.log("new filter = ", e.target.value);
```suggestion
```

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/components/SimpleSelect.js
> +    console.log(e);
```suggestion
```

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/context/SectionContext.js
> +export default SectionContext;
Pas clair (+ajoute de la complexité : on évite le contexte sauf si vraiment besoin)

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/create.js
> +/* eslint-disable prettier/prettier */
Pourquoi supprimer prettier spécialement ici ?

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/create.js
> +    }
On n'a pas déjà ce genre de validation ailleurs ?

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/create.js
> +    }
La duplication n'est pas convaincante ici.

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/create.js
> +    }
Idem

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/create.js
> +    //
?

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/create.js
> +        <div className="ml-[32px] text-[18px] font-[500] mb-[24px]">Informations générales</div>
On perd l'intérêt de tailwind ici, il faut faire normal genre (à l'arrache):

```suggestion
    <div className="py-4 px-8">
      <div className="relative bg-white shadow rounded mb-4 pt-4">
        <div className="text-lg font-bold flex items-center justify-center">Créer une inscription manuellement</div>
        <div className="border-b mx-8 my-4" />
        <div className="ml-5 text-md font-normal mb-4">Informations générales</div>
```

Cf: https://selego.slack.com/archives/C03LSTVJNLD/p1668521934560949

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/create.js
> +function Representant2({ values, handleChange, errors }) {
Bon alors si c'est deux fois la même chose je pense qu'on peut factoriser.

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/components/Field.js
> +        {type === "select" && <SimpleSelect value={value} name={name} transformer={transformer} options={options} onChange={handleChange} filterOnType={filterOnType} />}
Question ouverte: je me demande si ça vaut le coup de mettre simple select ici, ça ajoute un niveau de nested. À voir.

2022-11-15 14:31 UTC, rap2hpoutre commented on admin/src/scenes/volontaires/components/SimpleSelect.js
> +              <div className="font-normal text-[14px] leading-[20px] p-[5px] text-[#1F2937]">{transformer ? transformer(value) : value}</div>
La passage de `transformer` en cascade n'est pas hyper clair

```suggestion
              <div className="font-normal text-[14px] leading-[20px] p-[5px] text-[#1F2937]">{transformer ? transformer(value) : value}</div>
```

2022-11-16 10:25 UTC, guiTheret commented on admin/src/scenes/volontaires/create.js
> +        handleChange={setFieldValue}
Pour les prochains commits

2022-11-21 11:08 UTC, hlecourt requested changes
RP manque num de tel 
<img width="546" alt="image" src="https://user-images.githubusercontent.com/50077368/203033364-e8ebba5e-297d-4372-8a13-63309cf4e0eb.png">

Adresse manque pays de residence (toggle france etranger )

Date de naissance set au 09/09/2007 afficher ensuite 08/09/2007
<img width="581" alt="image" src="https://user-images.githubusercontent.com/50077368/203033608-d63a752d-9d2a-4639-a9b3-dcb806080d90.png">

Le droit a l'image Rp1/2 n'est pas set

il manque un consentement coter jeune 
<img width="413" alt="image" src="https://user-images.githubusercontent.com/50077368/203034169-501a7443-55c8-44e4-9d59-0089c093c426.png">

Manque un check sur le num de tel 
<img width="519" alt="image" src="https://user-images.githubusercontent.com/50077368/203034377-1f3ea3c9-76a5-42e7-94c0-2d4e0c8540f2.png">

Tu peux enlever les field departement et region

2022-11-22 09:45 UTC, hlecourt approved these changes
Yeahhh ! Let's merge 🎉

2022-11-22 09:47 UTC, merged