feat(admin): add button to reset parental consent
betagouv/service-national-universel pull request #2195
Opened 2023-01-20 15:13 UTC by nicobret

2023-01-20 16:44 UTC, hlecourt requested changes

2023-01-20 16:44 UTC, hlecourt commented on api/src/controllers/young-edition.js
> +    young.set({ parentAllowSNU: undefined, parent1AllowSNU: undefined });
t'as les date a remettre a zero

2023-01-20 16:44 UTC, hlecourt commented on api/src/controllers/young-edition.js
> +    young.set({ parentAllowSNU: undefined, parent1AllowSNU: undefined });
+ le status en a set a en cours

2023-01-20 16:47 UTC, nicobret commented on api/src/controllers/young-edition.js
> +    young.set({ parentAllowSNU: undefined, parent1AllowSNU: undefined });
bien vu

2023-01-23 11:25 UTC, hlecourt approved these changes

2023-01-23 12:35 UTC, merged