feat(admin): refonte fiche structure
betagouv/service-national-universel pull request #2210
Opened 2023-01-25 15:49 UTC by nicobret

2023-01-26 08:58 UTC, hlecourt requested changes
<img width="642" alt="image" src="https://user-images.githubusercontent.com/50077368/214794657-ba674478-f6b4-4968-be78-bbdc3e261d43.png">

Erreur sur tete de reseaux + prepa militaire
<img width="674" alt="image" src="https://user-images.githubusercontent.com/50077368/214795108-f4bddcb0-7193-44ce-8df4-c15b95cceb0e.png">

Quand j'enregistre je perd la mise en forme sur ce champs
<img width="633" alt="image" src="https://user-images.githubusercontent.com/50077368/214795411-97b4bd88-4f11-4bed-8d5c-4d326862c7f3.png">

2023-01-26 10:17 UTC, nicobret commented
> 

J'ai fixé les toggle et les line breaks sur le textarea. Pourquoi le screen de l'adresse ?

2023-01-26 12:19 UTC, nicobret commented
- fix comportement vérification d'adresse (ajout champ addressVerified dans modèle)
- select réseau clearable
- ajout boutons de copie des liens
-  pas réussi à reproduire le souci d'affichage du select de réseau

2023-01-27 13:11 UTC, guiTheret requested changes

2023-01-27 13:11 UTC, guiTheret commented on admin/src/scenes/structure/view/detailsV2.js
> +    setErrors(error);
Faut rajouter un check sur addressVerified.
Quand je change l'adresse je peux enregistrer même si pas vérifié

2023-01-27 13:11 UTC, guiTheret commented on admin/src/scenes/structure/view/detailsV2.js
> +                    readOnly={!isEditing}
Faut confirmer, mais normalement on est pas censé pouvoir modifier Département + Région c'est uniquement avec la vérification

2023-01-27 13:11 UTC, guiTheret commented on admin/src/scenes/structure/components/MultiSelect.js
> +                    <div className="flex items-center justify-between w-full">
Bon ca c'est mon gout, mais tu veux pas le mettre justify-start ? A mon avis ca rend mieux

2023-01-27 13:11 UTC, guiTheret commented on admin/src/scenes/structure/components/MultiSelect.js
> +                      <span className="pointer-events-none flex items-center pr-2">
Le chevron est pas au bon endroit quand y'a pas d'items de sélectionné

2023-01-27 13:11 UTC, guiTheret commented on admin/src/scenes/structure/components/EditButton.js
> +
Tu veux pas le mettre tout en haut ce component ? On le réutilise beaucoup beaucoup mtn.

2023-01-27 13:37 UTC, nicobret commented on admin/src/scenes/structure/view/detailsV2.js
> +    setErrors(error);
BIen vu.

2023-01-27 13:38 UTC, nicobret commented on admin/src/scenes/structure/view/detailsV2.js
> +                    readOnly={!isEditing}
Exact.

2023-01-27 13:43 UTC, nicobret commented on admin/src/scenes/structure/components/EditButton.js
> +
Bonne idée.

2023-01-27 13:54 UTC, nicobret commented on admin/src/scenes/structure/components/MultiSelect.js
> +                      <span className="pointer-events-none flex items-center pr-2">
voir au-dessus

2023-01-27 13:54 UTC, nicobret commented on admin/src/scenes/structure/components/MultiSelect.js
> +                    <div className="flex items-center justify-between w-full">
Yes j'ai changé des trucs.

2023-01-27 13:54 UTC, nicobret commented on admin/src/scenes/structure/components/EditButton.js
> +
Bonne idée.

2023-01-27 15:30 UTC, merged