feat(admin): refonte structure : représentant de structure
betagouv/service-national-universel pull request #2223
Opened 2023-01-31 09:52 UTC by nicobret

2023-02-01 17:02 UTC, naustra commented
à la création d'une structure il faudrait set le tuteur originel par défaut en temps que responsable non ?

2023-02-01 17:21 UTC, pierre-lebihan commented
On est d'accord que ça fait pas du tout ce ticket là : https://www.notion.so/jeveuxaider/STRUCTURE-Refonte-du-compte-avec-alignement-sur-nouveau-design-tape-1-a5336c033cc04e52a71726e45a876767 ?
Il faudrait le virer de la PR si c'est pas le cas

2023-02-01 17:24 UTC, naustra requested changes

2023-02-01 17:24 UTC, pierre-lebihan commented on admin/src/scenes/structure/components/cards/CardRepresentant.js
> +    } catch (e) {
capture(e)

2023-02-01 17:24 UTC, pierre-lebihan commented on admin/src/scenes/structure/components/cards/CardRepresentant.js
> +      return toastr.error("Une erreur s'est produite :", translate(e.code));
capture (e)

2023-02-01 17:24 UTC, pierre-lebihan commented on admin/src/scenes/structure/components/modals/ModalRepresentant.js
> +              <div className="w-full flex justify-center items-center gap-2">
Do not show delete button if you don't have informations set

2023-02-01 17:24 UTC, pierre-lebihan commented on admin/src/scenes/structure/components/modals/ModalRepresentant.js
> +          <Field label="Téléphone" name="mobile" value={data.mobile} handleChange={handleChange} />
Vérifie le format téléphone. On peut mettre n'importe quoi la

2023-02-01 17:24 UTC, pierre-lebihan commented on admin/src/scenes/structure/components/modals/ModalRepresentant.js
> +          <Field label="Adresse email" name="email" value={data.email} handleChange={handleChange} />
Pareil vérifie le format mail.
Il y a pas de gestion en cas d'erreur sur l'appui sur enregistrer ?

2023-02-01 17:24 UTC, naustra commented on admin/src/scenes/structure/components/modals/ModalRepresentant.js
> +          <Field label="Rôle" name="role" value={data.role} handleChange={handleChange} />
Les valeurs possibles de role devraient pas être dans un enum plutot ?
A chalenger le produit la dessus. ça serait plus clair que ça soit un enum je pense.

2023-02-01 17:24 UTC, naustra commented on admin/src/components/Contract.js
> +      tutorRole: "Tuteur de mission",
à quoi sert role et mail ? C'est pas utilisé

2023-02-01 17:24 UTC, pierre-lebihan commented on admin/src/scenes/structure/components/cards/CardRepresentant.js
> +import Card from "../Card";
T'as vraiment besoin de duppliquer Card et Button ou juste flemme ?

2023-02-01 17:24 UTC, pierre-lebihan commented on api/src/controllers/contract.js
> +  sendContractEmail(contract, {
Tu peux envoyer les 2 mails en async en même temps :
Exemple avec ce code :
async function performMultipleAwaits() {
  const [result1, result2] = await Promise.all([
    asyncTask1(),
    asyncTask2()
  ]);
}

2023-02-01 17:24 UTC, pierre-lebihan commented on api/src/controllers/contract.js
> +  sendContractEmail(contract, {
D'ailleurs plusieurs choses vont pas ici, il faut écrire return await pour la plupart des fonctions et try catch autour du sendContractEmail

2023-02-01 17:24 UTC, pierre-lebihan commented on api/src/controllers/structure.js
> +    console.log("🚀 ~ file: structure.js:231 ~ router.post ~ error", error);
delete

2023-02-01 17:24 UTC, pierre-lebihan commented on api/src/utils/validator.js
> +      mobile: Joi.string().allow(null, ""),
Il y a une vérif de format téléphone éventuellement à faire ici si t'en voie à 'autres endroits dans le code mais le front devrait être suffisant

2023-02-01 17:35 UTC, nicobret commented
> à la création d'une structure il faudrait set le tuteur originel par défaut en temps que responsable non ?

Possible mais hors scope selon moi. Je demande à Gab.

> On est d'accord que ça fait pas du tout ce ticket là : https://www.notion.so/jeveuxaider/STRUCTURE-Refonte-du-compte-avec-alignement-sur-nouveau-design-tape-1-a5336c033cc04e52a71726e45a876767 ? Il faudrait le virer de la PR si c'est pas le cas

ça fait la partie carte au dessus du formulaire.

2023-02-01 17:36 UTC, nicobret commented on admin/src/scenes/structure/components/modals/ModalRepresentant.js
> +          <Field label="Rôle" name="role" value={data.role} handleChange={handleChange} />
C'est un "champ libre" d'après le ticket. Je pense que ça peut être des rôles propres à chaque structure.

2023-02-01 17:41 UTC, nicobret commented on admin/src/scenes/structure/components/cards/CardRepresentant.js
> +    } catch (e) {
Ajouté.

2023-02-01 17:41 UTC, nicobret commented on admin/src/scenes/structure/components/cards/CardRepresentant.js
> +      return toastr.error("Une erreur s'est produite :", translate(e.code));
Ajouté.

2023-02-01 17:42 UTC, nicobret commented on admin/src/scenes/structure/components/modals/ModalRepresentant.js
> +              <div className="w-full flex justify-center items-center gap-2">
Condition ajoutée.

2023-02-01 18:20 UTC, nicobret commented on admin/src/scenes/structure/components/modals/ModalRepresentant.js
> +          <Field label="Téléphone" name="mobile" value={data.mobile} handleChange={handleChange} />
Validation rajoutée en front.

2023-02-01 18:20 UTC, nicobret commented on admin/src/scenes/structure/components/modals/ModalRepresentant.js
> +          <Field label="Adresse email" name="email" value={data.email} handleChange={handleChange} />
Maintenant, oui.

2023-02-01 18:24 UTC, nicobret commented on admin/src/scenes/structure/components/cards/CardRepresentant.js
> +import Card from "../Card";
Oui, ça va servir pour l'autre carte de la page (elle est déjà en ligne mais le design est à améliorer) ainsi que les prochains composants en mode carte.

2023-02-01 18:26 UTC, nicobret commented on admin/src/components/Contract.js
> +      tutorRole: "Tuteur de mission",
Euh, si ? Tu parles du structureManager ou du tuteur ? (le tuteur a pas de rôle hormis celui de tuteur dans le cadre du contrat).

2023-02-01 18:31 UTC, nicobret commented on api/src/controllers/contract.js
> +  sendContractEmail(contract, {
Comme ça ?

```
async function sendStructureManagerContractEmail(contract, isValidateAgainMail) {
  try {
    return await Promise.all([
      sendContractEmail(contract, {
        email: contract.tutorEmail,
        name: `${contract.tutorFirstName} ${contract.tutorLastName}`,
        token: contract.tutorToken,
        isValidateAgainMail,
      }),
      await sendContractEmail(contract, {
        email: contract.structureManagerEmail,
        name: `${contract.structureManagerFirstName} ${contract.structureManagerLastName}`,
        token: contract.structureManagerToken,
        isValidateAgainMail,
      }),
    ]);
  } catch (e) {
    capture(e);
  }
}
```

2023-02-01 18:31 UTC, nicobret commented on api/src/controllers/structure.js
> +    console.log("🚀 ~ file: structure.js:231 ~ router.post ~ error", error);
Oups.

2023-02-01 18:35 UTC, nicobret commented on api/src/utils/validator.js
> +      mobile: Joi.string().allow(null, ""),
Vérification ajoutée en back.

2023-02-02 11:33 UTC, naustra commented
> > à la création d'une structure il faudrait set le tuteur originel par défaut en temps que responsable non ?
> 
> Possible mais hors scope selon moi. Je demande à Gab.
> 
> > On est d'accord que ça fait pas du tout ce ticket là : https://www.notion.so/jeveuxaider/STRUCTURE-Refonte-du-compte-avec-alignement-sur-nouveau-design-tape-1-a5336c033cc04e52a71726e45a876767 ? Il faudrait le virer de la PR si c'est pas le cas
> 
> ça fait la partie carte au dessus du formulaire.

Je ne comprends pas ce que tu dis.
Ta PR ne résoud pas ça si ?
![CleanShot 2023-02-02 at 11 32 20](https://user-images.githubusercontent.com/11462919/216313922-59683ce3-85c5-419a-991b-a1f0c0a691cf.png)

2023-02-02 11:45 UTC, nicobret commented
> > > à la création d'une structure il faudrait set le tuteur originel par défaut en temps que responsable non ?
> > 
> > 
> > Possible mais hors scope selon moi. Je demande à Gab.
> > > On est d'accord que ça fait pas du tout ce ticket là : https://www.notion.so/jeveuxaider/STRUCTURE-Refonte-du-compte-avec-alignement-sur-nouveau-design-tape-1-a5336c033cc04e52a71726e45a876767 ? Il faudrait le virer de la PR si c'est pas le cas
> > 
> > 
> > ça fait la partie carte au dessus du formulaire.
> 
> Je ne comprends pas ce que tu dis. Ta PR ne résoud pas ça si ? ![CleanShot 2023-02-02 at 11 32 20](https://user-images.githubusercontent.com/11462919/216313922-59683ce3-85c5-419a-991b-a1f0c0a691cf.png)

Cette PR résoud une partie de :
- Ma structure (pour responsable de structure)

2023-02-02 12:07 UTC, pierre-lebihan commented on admin/src/scenes/structure/components/modals/ModalRepresentant.js
> +    if (!data.email.match(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i)) errors.email = "L'email n'est pas valide";
Tu veux pas utiliser le package validator plutot ?
isEmail()

2023-02-02 12:07 UTC, pierre-lebihan commented on admin/src/scenes/structure/components/modals/ModalRepresentant.js
> +      if (!phone.match(/^(0|\+33)[1-9]([-. ]?[0-9]{2}){4}$/)) errors.mobile = "Le téléphone n'est pas valide";
Pareil, utilise regexPhoneFrenchCountries plutot

2023-02-02 12:07 UTC, pierre-lebihan commented on admin/src/scenes/structure/components/modals/ModalRepresentant.js
>    const handleSubmit = async () => {
Vu que cette fonction commence à prendre de la place, met la dans un try catch maintenant !

2023-02-02 12:07 UTC, pierre-lebihan commented on admin/src/components/Contract.js
> +      tutorRole: "Tuteur de mission",
tutorRole et tutorEmail, n'est utilisé nulle part dans le code

2023-02-02 12:07 UTC, pierre-lebihan commented on admin/src/scenes/structure/components/cards/CardRepresentant.js
> +import Card from "../Card";
ok

2023-02-02 12:07 UTC, pierre-lebihan commented on api/src/controllers/contract.js
> +  sendContractEmail(contract, {
Oui, c'est good. Par contre, t'as pas pris en compte mon second comm :
D'ailleurs plusieurs choses vont pas ici, il faut écrire return await pour la plupart des fonctions et try catch autour du sendContractEmail

2023-02-02 12:18 UTC, merged