feat(api,admin): Ajout des emplois du temps sur les sessions
betagouv/service-national-universel pull request #2238
Opened 2023-02-06 15:45 UTC by seb-doncker

Ticket : https://www.notion.so/jeveuxaider/CENTRE-T-l-versement-t-l-chargement-emploi-du-temps-9e8ea61edf864340ae837a76a2355c08

Script qu'il faudra lancer en prod pour mettre à jour les statuts d'emploi du temps déposé/non déposé : 
/scripts/update-time-schedule-for-all-sessions.js

2023-02-07 12:00 UTC, hlecourt requested changes
Pas tester

2023-02-07 12:00 UTC, hlecourt commented on admin/src/services/api.js
> +    formData.append("body", JSON.stringify(allData));
?

2023-02-07 12:00 UTC, hlecourt commented on admin/src/scenes/centersV2/components/modals/ModalTimeSchedule.js
> +const ACCEPTABLE_MIME_TYPES = ["image/jpg", "image/jpeg", "image/png", "application/pdf"];
Je pense qu'il faut accepter les excel aussi

2023-02-07 12:00 UTC, hlecourt commented on admin/src/scenes/centersV2/components/modals/ModalTimeSchedule.js
> +    console.log("return of the session: ", session);
```suggestion
```

2023-02-07 12:00 UTC, hlecourt commented on admin/src/scenes/centersV2/components/modals/ModalTimeSchedule.js
> +  useEffect(() => {
Le use effect est useless la

2023-02-07 12:00 UTC, hlecourt commented on admin/src/scenes/centersV2/components/modals/ModalTimeSchedule.js
> +    console.log("session changed: ", newSession);
```suggestion
```

2023-02-07 12:00 UTC, hlecourt commented on admin/src/scenes/centersV2/components/modals/ModalTimeSchedule.js
> +  const [communicating, setCommunicating] = useState(false);
😆

2023-02-07 12:00 UTC, hlecourt commented on admin/src/scenes/centersV2/components/modals/ModalTimeSchedule.js
> +    console.log("Upload File: ", file);
```suggestion
```

2023-02-07 12:00 UTC, hlecourt commented on admin/src/scenes/centersV2/components/modals/ModalTimeSchedule.js
> +    console.log("type: ", file.type);
```suggestion
```

2023-02-07 12:00 UTC, hlecourt commented on admin/src/scenes/centersV2/components/modals/ModalTimeSchedule.js
> +    console.log("accept: ", ACCEPTABLE_MIME_TYPES, ACCEPTABLE_MIME_TYPES.findIndex((t) => t === file.type) >= 0);
```suggestion
```

2023-02-07 12:00 UTC, hlecourt commented on admin/src/scenes/centersV2/components/modals/ModalTimeSchedule.js
> +  function dragIn(e) {
Pas de risque de fichier corrompu sur ca ?

2023-02-07 12:00 UTC, hlecourt commented on lib/constants.js
> +    TIME_SCHEDULE_REMINDER: 697
```suggestion
    TIME_SCHEDULE_REMINDER: "697",
```

2023-02-08 08:46 UTC, seb-doncker commented on admin/src/services/api.js
> +    formData.append("body", JSON.stringify(allData));
Alors ca en fait c'est pas mon code mais j'avais une erreur dans la console avec un properties qui povait être vide. J4ai juste mis un garde pour éviter l'erreur sans chercher plus loin.

2023-02-08 08:50 UTC, seb-doncker commented on admin/src/scenes/centersV2/components/modals/ModalTimeSchedule.js
> +  function dragIn(e) {
Le fichier est testé de la même manière dans le back qu'on le drag'n'drop ou qu'on l'upload via le file input. Donc, non pas de raison.

2023-02-08 09:57 UTC, hlecourt commented on admin/src/services/api.js
> +    formData.append("body", JSON.stringify(allData));
ok

2023-02-08 10:05 UTC, hlecourt approved these changes
Let's merggeeee 🎉

2023-02-08 13:18 UTC, merged