fix(admin): correction du selecteur de cohort sur schema et table repartition et gestion des droits
betagouv/service-national-universel pull request #2309
Opened 2023-02-23 11:48 UTC by BryanBerger98

**Problème rencontré:**

En tant que référent régional, depuis l’onglet schéma de répartition, je sélectionne un séjour, puis un département, si je reviens en arrière en cliquant sur précédent, la plateforme ne garde pas en mémoire le séjour sélectionné.

Comportement identique sur la page table de répartition.

**Corrections apportées:**

* Persistance du séjour sélectionné via un query param dans l'url (sur la page schéma de répartition & table de répartition)
* Correction des breadcrumbs. Certains élément n'était plus cliquables
* Correction des droits d'accès à la route `/schema-repartition`. Cette URL était accessible par tout le monde alors que seuls les rôles `admin` & `transporteur` y ont un droit d'accès.

[📌 Ticket](https://www.notion.so/jeveuxaider/Sch-ma-de-r-partition-s-lecteur-de-s-jour-et-retour-en-arri-re-be35e7cf7b654cd8b914aa592b83414e)

2023-02-24 09:48 UTC, hlecourt reviewed
Pas stable au niveau du selecteur de cohort 
L'acces au route est NOK pour ref region / dep
J'ai plein d'erreur qui se glisse 
--> en parle lundi

2023-02-28 08:30 UTC, hlecourt requested changes
En temps que moderateur quand je vais sur l'onglet du schema :
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/50077368/221796128-972e5be7-58e4-4ca4-8e23-9ba440796486.png">

Pour ref dep et region tester et ok (pas tester sur multi dep)

2023-02-28 08:30 UTC, hlecourt commented on admin/src/scenes/plan-transport/schema-repartition/SchemaRepartition.js
> +    }
il manque la route par default

2023-02-28 08:30 UTC, hlecourt commented on admin/src/scenes/plan-transport/schema-repartition/SchemaRepartition.js
> +    }
idem pour les departements, il manque la route par default

2023-02-28 08:30 UTC, hlecourt commented on admin/src/scenes/plan-transport/schema-repartition/SchemaRepartition.js
> +    }
Idem pour les departement : meme si tu vas repasser dessus pour fixe le bug du multi dep (tu peux mettre de base le user.department[0])

2023-02-28 08:30 UTC, hlecourt commented on admin/src/utils/components/RestrictedChildRoute.js
> +
Pour le coup tu peux commenter ce component

2023-02-28 11:33 UTC, BryanBerger98 commented on admin/src/scenes/plan-transport/schema-repartition/SchemaRepartition.js
> +    }
Quelle route par défaut ? `/schema-repartition` ?
Dans quel cas est-elle utile ici ?

2023-02-28 11:35 UTC, BryanBerger98 commented on admin/src/scenes/plan-transport/schema-repartition/SchemaRepartition.js
> +    }
Je ne l'ai pas mis pour les départements car ils ont toujours la même vue à ce niveau. Ils ne peuvent voir que les département et ne sont pas censés remonter au niveau national ou régional

2023-03-01 08:48 UTC, hlecourt approved these changes
Let's merggeeee 🎉

2023-03-01 08:48 UTC, hlecourt commented on admin/src/scenes/plan-transport/schema-repartition/SchemaRepartition.js
> +      console.log(region);
```suggestion
```

2023-03-01 09:11 UTC, merged