feat(api): Ajout d'envoi notification par email au transporteur à l'ouverture nouvelle demande de modification sur plan de transport
betagouv/service-national-universel pull request #2316
Opened 2023-02-27 14:01 UTC by BryanBerger98

**🧑‍💻 Fonctionnalités ajoutées:**

- Notification envoyée par email à tous les référents ayant le rôle "transporter" lors de l'ouverture d'une nouvelle demande de modification d'un plan de transport.

[📌 Ticket](https://www.notion.so/jeveuxaider/TRANSPORT-Branchement-des-notifs-de-demande-de-correction-sur-le-plan-de-transport-e4ddb3b7398545c0860266072f57f54e)

2023-02-28 08:35 UTC, hlecourt requested changes
Il manque les template 673-674 sur les status de demande + les destinataire en dur :
 - aux modérateurs (Edouard : [edouard.vizcaino@jeunesse-sports.gouv.fr](mailto:edouard.vizcaino@jeunesse-sports.gouv.fr) et Christelle : [christelle.bignon@jeunesse-sports.gouv.fr](mailto:christelle.bignon@jeunesse-sports.gouv.fr)  )

Je t'ai tag sur figma

2023-03-01 08:53 UTC, hlecourt commented on api/src/controllers/planDeTransport/demande-de-modification.js
> +        (status === "ACCEPTED" && SENDINBLUE_TEMPLATES.PLAN_TRANSPORT.MODIFICATION_ACCEPTEE) || (status === "REJECTED" && SENDINBLUE_TEMPLATES.PLAN_TRANSPORT.MODIFICATION_REFUSEE),
Plus simple non ? 
```javascript
const template = status === "ACCEPTED" ? SENDINBLUE_TEMPLATES.PLAN_TRANSPORT.MODIFICATION_ACCEPTEE : SENDINBLUE_TEMPLATES.PLAN_TRANSPORT.MODIFICATION_REFUSEE;
await sendTemplate(template,...);
```

2023-03-01 08:53 UTC, hlecourt commented on api/src/controllers/planDeTransport/demande-de-modification.js
> +          cta: `${config.ADMIN_URL}/ligne-de-bus/${lineId}`,
le cta peux être plus précis et ouvrir la demande de modiffcation je te laisse check

2023-03-01 09:23 UTC, BryanBerger98 commented on api/src/controllers/planDeTransport/demande-de-modification.js
> +          cta: `${config.ADMIN_URL}/ligne-de-bus/${lineId}`,
Il n'y a aucune fonctionnalité existante permettant l'ouverture de la demande depuis l'URL. Je l'ajoute ?

2023-03-01 09:41 UTC, hlecourt approved these changes
Let's goooo 🎉

2023-03-01 09:42 UTC, merged