feat(app): refonte de la barre de navigation
betagouv/service-national-universel pull request #2322
Opened 2023-02-28 23:18 UTC by nicobret

https://www.notion.so/jeveuxaider/D-ploiement-de-la-nouvelle-bar-de-navigation-978a7d8ae43e43a2a43ce24a1ce13788?pvs=4

2023-03-06 11:49 UTC, BryanBerger98 requested changes

2023-03-06 11:49 UTC, BryanBerger98 commented on app/src/index.css
>  }
Si tout est commenté ici on peut peut-être viré ça non ?

2023-03-06 11:49 UTC, BryanBerger98 commented on app/src/components/navbar/index.js
> +            <Hamburger className="text-[#828EAC]" />
Il faut que tu définisses une taille précise sur ton icône `Hamburger` car elle dépasse de la navbar. Ce qui fait que quand tu cliques un peu en dessous de la navbar, sur "PRÉNOM, vous avez validé votre Phase 1 !", ça ouvre la navbar (screenshot ci-dessous):
![Screenshot 2023-03-06 at 12 09 35](https://user-images.githubusercontent.com/39988518/223095308-0d0f2565-ff34-453f-a138-e8ccecccd705.png)

Sauf que si tu définis une taille sur ton icône, ta navbar au format mobile va se réduire pour prendre la taille de son contenu et donc ne prendra plus 100% de la largeur. Il faudra donc que tu modifies ce code à la ligne `224` du fichier `app/src/app.js` pour lui dire de prendre toute la largeur quand on est au format mobile comme ceci (je vais te proposer une suggestion directement dans la PR):

```jsx
<div className="fixed top-0 left-0 z-10 right-0 md:right-auto">
      <Navbar />
</div>
```

2023-03-06 11:49 UTC, BryanBerger98 commented on app/src/components/navbar/components/UserMenu.js
> +        <div className="">
Petit `className` vide ici

2023-03-06 11:49 UTC, BryanBerger98 commented on app/src/scenes/phase1/done.js
> +                className="flex  z-10 justify-between gap-3 items-center rounded-full border-[1px] border-blue-600 bg-blue-600 px-3 py-2 disabled:opacity-50 disabled:cursor-wait w-full"
Pourquoi le `z-10` ici ? Il ne me semble pas nécessaire

2023-03-06 11:49 UTC, BryanBerger98 commented on app/src/components/navbar/components/User.js
> +        <Link to="#" onClick={logout}>
Selon moi tu ne devrais pas utiliser un lien ici mais un bouton pour le `logout`. Pareil dans le composant `UserMenu` à la ligne `29` qui utilise `MenuItem` qui est un lien:
```jsx
 <MenuItem setOpen={setIsOpen} to="logout" text="Déconnexion" />
```
Ça fonctionne mais ça ne me semble pas approprié, notamment pour des questions d'accessibilité.
On devrait demander un avis supplémentaire pour cette question histoire d'être sûrs.

2023-03-06 11:49 UTC, BryanBerger98 commented on app/src/components/navbar/components/MenuItem.js
> +  const isActive = (to === "/" && location.pathname === "/") || (to !== "/" && location.pathname.includes(to));
Selon moi cette seule condition devrait suffire:
```jsx
const isActive = location.pathname.includes(to);
```

2023-03-06 11:49 UTC, BryanBerger98 commented on app/src/app.js
> +      <div className="fixed top-0 left-0 z-10">
Je te propose une petite modification en lien avec le commentaire que je t'ai laissé sur le fichier `app/src/components/navbar/index.js`:

```suggestion
      <div className="fixed top-0 left-0 z-10 right-0 md:right-auto">
```

2023-03-06 11:49 UTC, BryanBerger98 commented on app/src/app.js
> +          {/* <Footer /> */}
À virer ?

2023-03-06 21:45 UTC, nicobret commented on app/src/components/navbar/components/MenuItem.js
> +  const isActive = (to === "/" && location.pathname === "/") || (to !== "/" && location.pathname.includes(to));
Bien vu !

2023-03-06 21:46 UTC, nicobret commented on app/src/components/navbar/components/User.js
> +        <Link to="#" onClick={logout}>
Bonne idée, j'ai ajouté la possibilité d'utiliser un bouton dans ce composant.

2023-03-06 21:46 UTC, nicobret commented on app/src/scenes/phase1/done.js
> +                className="flex  z-10 justify-between gap-3 items-center rounded-full border-[1px] border-blue-600 bg-blue-600 px-3 py-2 disabled:opacity-50 disabled:cursor-wait w-full"
En effet.

2023-03-06 21:46 UTC, nicobret commented on app/src/components/navbar/components/UserMenu.js
> +        <div className="">
👍

2023-03-06 21:57 UTC, nicobret commented on app/src/components/navbar/index.js
> +            <Hamburger className="text-[#828EAC]" />
Bien vu ! Changement fait, et j'ai aussi modifié la forme du bouton (carré autour de l'icône).

2023-03-06 22:19 UTC, nicobret commented on app/src/app.js
> +          {/* <Footer /> */}
J'ai supprimé celui-ci et remis celui de la fonction App (je pensais que ça causerait pb avec la navbar en absolute mais non).

2023-03-07 09:39 UTC, BryanBerger98 requested changes

2023-03-07 09:39 UTC, BryanBerger98 commented on app/src/components/navbar/components/User.js
> +        </button>
Les balises paragraphe sont inutiles ici. Je suggère cette modification:
```suggestion
        <Link to="account" className="flex items-center gap-3 p-2 px-3 text-sm leading-5 hover:bg-gray-100 text-gray-900 hover:text-gray-900">
          Mon profil
        </Link>
        <Link to="preferences" className="flex items-center gap-3 p-2 px-3 text-sm leading-5 hover:bg-gray-100 text-gray-900 hover:text-gray-900">
          Mes préférences de mission
        </Link>
        <button onClick={logout} type="button" className="flex items-center gap-3 p-2 px-3 text-sm leading-5 hover:bg-gray-100 text-gray-900 hover:text-gray-900">
          Se déconnecter
        </button>
```

2023-03-07 09:39 UTC, BryanBerger98 commented on app/src/components/navbar/components/MenuItem.js
> +export default function MenuItem({ to, onClick, enabled = true, icon, text, status, setOpen }) {
D'après le point que j'ai eu avec Hugo et Raph, il faudrait split ce composant en deux:

* Un composant `MenuItemLink` dédié aux liens
* Un composant `MenuItemButton` dédié aux boutons

Histoire de simplifier la logique des composants.
Tu peux faire une seconde PR pour modifier ça. Pas besoin de le faire ici, c'est juste une indication.

2023-03-07 10:40 UTC, nicobret commented on app/src/components/navbar/components/MenuItem.js
> +export default function MenuItem({ to, onClick, enabled = true, icon, text, status, setOpen }) {
✅

2023-03-07 10:54 UTC, merged