fix(admin): validation du dossier des jeunes inscrits d'après l'objectif départemental
betagouv/service-national-universel pull request #2331
Opened 2023-03-02 11:27 UTC by BryanBerger98

🧑‍💻 **Fonctionnalités et modifications développées:**
* Baser la validation d'un dossier "en attente de validation" d'après les objectifs d’inscription départementaux.
* Remplacer les intitulés “Validé”* en “*Validé sur liste principale” et “Sur liste complémentaire” en “Validé sur liste complémentaire”.

🔄 **Refactorisations effectuées:**
* Création d'un composant `Button` générique dans le dossier `components/ui/buttons`
* Création d'un composant modale Tailwind intitulé `Modal` dans le dossier `components/ui/modals`
* Création d'un composant modale de confirmation intitulé `ConfirmationModal` à partir du composant `Modal`, placé dans le même dossier.

[📌 Ticket](https://www.notion.so/jeveuxaider/INSCRIPTION-Indexation-objectif-d-inscription-5f82069571da4216ae3e8c843a630d50)

2023-03-03 09:39 UTC, hlecourt requested changes
Alors pour moi ton refacto ne fit pas avec les concept de tailwind qui sont censé rester simple,  l'utilisation de composant général est cool mais j'aurais vu : 
- dossier component/button : un bouton par type PlainButton / OutlineButton avec en parametre juste le children / onClick
La ta logique est compliqué et rend la maintenabilité encore plus compliqué : on veux des choses simples !
Exemple : 
```javascript
export default function ButtonPlain({ tw = "bg-indigo-600 text-white", children, onClick }) {
  return (
    <button onClick={onClick} className={`${tw} py-[9px] px-4 rounded-md mt-2 hover:shadow-lg`}> //classname de base plus défini avec couleur etc
      {children}
    </button>
  );
}
```
- modal : un composant modal suffit sans lui rajouter la logique inside : 
Pour le composant ConfirmationModal ne sert a rien, j'aurais plus rajouté dans ton composant modale : 
 ```javascript
const ModalHeader = ({ children, title }) => {
  return (
    <div className="tw-flex tw-w-full tw-shrink-0 tw-items-center tw-justify-between tw-rounded-t-lg tw-border-b tw-border-gray-200 tw-bg-white">
      <div className="tw-w-full tw-py-4 sm:tw-flex sm:tw-items-start">
        <div className="tw-mt-3 tw-w-full tw-text-center sm:tw-mt-0 sm:tw-text-left">
          {!!title && (
            <Dialog.Title as="h3" className="tw-mb-0 tw-px-4 tw-text-lg tw-font-medium tw-leading-6 tw-text-gray-900 sm:tw-px-6">
              {title}
            </Dialog.Title>
          )}
          {children}
        </div>
      </div>
    </div>
  );
};

const ModalBody = ({ children, className = '' }) => {
  return (
    <div className="tw-shrink tw-bg-white tw-pb-4">
      <div className="sm:tw-flex sm:tw-items-start">
        <div className={['tw-w-full tw-text-center sm:tw-mt-0 sm:tw-text-left', className].join(' ')}>{children}</div>
      </div>
    </div>
  );
};

const ModalFooter = ({ children }) => {
  return (
    <div className="tw-shrink-0 tw-rounded-b-lg tw-border-t tw-border-gray-200 tw-bg-gray-50 tw-px-4 tw-py-3 sm:tw-flex sm:tw-justify-end sm:tw-px-6">
      {children}
    </div>
  );
};

export { Modal, ModalBody, ModalFooter, ModalContainer };
```

Ce qui nous laisse plus libre et fit beaucoup mieux avec les principe de tailwind (sachant que derriere dans les children on peux réutilisé les PlainButton ...

Voir : https://adamwathan.me/css-utility-classes-and-separation-of-concerns/

`Recently, I also released my own free open-source PostCSS framework called [Tailwind CSS](https://tailwindcss.com/) that's designed around this idea of working utility-first and extracting components from repeated patterns`

2023-03-03 09:39 UTC, hlecourt commented on admin/src/components/ui/modals/Modal.js
> +const Modal = ({ isOpen, onClose = () => {}, size = "md", children, className = "" }) => {
pas fan de definir la size je laisserais ca libre

2023-03-06 16:36 UTC, BryanBerger98 commented
Ce que j'ai modifié:
* J'ai retiré le composant `Button` trop complexe
* J'ai créé un composant `ButtonLight` et un autre `ButtonPrimary` tous deux beaucoup plus simples
* J'ai supprimé le composant `ConfirmationModal`
* J'ai retiré la gestion des sizes dans la `Modal` tailwind
* J'ai directement placé le code de la modale de confirmation dans la vue de la phase0. Ça mériterai d'être factorisé mais je propose de faire ce travail dans une autre PR vu que ce fix est très attendu

2023-03-08 09:16 UTC, hlecourt commented on admin/src/scenes/phase0/view.js
> +          <div className="bg-white rounded-lg">
Hum on peux pas mettre ca dans la modal direct ?

2023-03-08 09:18 UTC, BryanBerger98 commented on admin/src/scenes/phase0/view.js
> +          <div className="bg-white rounded-lg">
Si tu as carrément raison

2023-03-08 09:34 UTC, hlecourt commented on admin/src/scenes/phase0/view.js
> +        {confirmModal && (
Besoin de cette condition ?

2023-03-08 09:40 UTC, BryanBerger98 commented on admin/src/scenes/phase0/view.js
> +        {confirmModal && (
Oui, `Transition.Root` qui se trouve dans `Modal` a besoin d'un boolean. Si tu lui met autre chose, même si c'est falsy ou truthy, ça plante. Il besoin d'un vrai boolean

2023-03-08 09:46 UTC, hlecourt reviewed
Ok test !

2023-03-08 09:46 UTC, hlecourt approved these changes

2023-03-08 09:47 UTC, hlecourt commented on admin/src/scenes/phase0/view.js
> +        {confirmModal && (
yep je parle plus de la ligne 497 ?

2023-03-08 09:52 UTC, merged