fix(api): france connect state
betagouv/service-national-universel pull request #2449
Opened 2023-03-30 10:45 UTC by michaelgarcia75

https://www.notion.so/jeveuxaider/France-Connect-impl-menter-les-recommandations-OpenID-FC-sur-les-param-tres-state-et-nonce-9c287a00481147b6bc6577b4defaa7d2

En gros de ce que j'ai trouver les recommandations openID c'était crypto.randomBytes(20).toString("hex"), il était deja sur le nonce donc je l'ai rajouté sur le state aussi

2023-03-30 16:04 UTC, naustra commented
![CleanShot 2023-03-30 at 16 59 22](https://user-images.githubusercontent.com/11462919/228895486-5282d4a9-d4d0-410a-9c41-1917f14932ac.png)
Pas good, il faut mettre le value.callback en dur dans le code (a mon avis, ça change jamais) + autres choses dites à l'oral

2023-04-06 15:39 UTC, michaelgarcia75 commented
Dans l'index.js j'ai peur avec le client.on que ça spam en cas d'erreur
```
client.on("error", function (error) {
  console.error("Error connecting to Redis server", error);
});
```

2023-04-06 16:08 UTC, naustra requested changes

2023-04-06 16:08 UTC, pierre-lebihan commented on api/src/controllers/young/index.js
> +        console.error(error);
capture(error)

2023-04-06 16:08 UTC, pierre-lebihan commented on api/src/controllers/young/index.js
> +        console.error(error);
capture errror

2023-04-06 16:08 UTC, pierre-lebihan commented on api/src/controllers/young/index.js
> +    if (storedNonce !== decodedToken.nonce) {
Code trop lours, eneleve le console log

2023-04-06 16:08 UTC, naustra commented on api/src/controllers/young/index.js
> +const client = redis.createClient({
rename redisClient

2023-04-06 16:08 UTC, naustra commented on api/src/controllers/young/index.js
> +    if (storedNonce !== decodedToken.nonce) {
Mets juste si storedNonce existe non ? Si tu le trouve pas dans le redis, c'est que c'est pas bon

2023-04-06 16:08 UTC, naustra commented on api/src/controllers/young/index.js
>        return res.sendStatus(403, token);
Rajoute un capture ici avec France Connect User Information failed : + JSON.stringify({storedNonce, storedState, token})

2023-04-06 16:08 UTC, naustra commented on api/src/controllers/young/index.js
>        return res.sendStatus(403, token);
Merge les 2 if en dessous avec celui-co

2023-04-06 16:08 UTC, naustra commented on api/src/controllers/young/index.js
> +        console.log("Value set with expiration time");
enleve le log

2023-04-06 16:08 UTC, pierre-lebihan commented on api/src/controllers/young/index.js
> +        console.log("Value set with expiration time");
en le ve le log

2023-04-06 16:09 UTC, naustra commented on api/src/controllers/young/index.js
> +        console.error(error);
écrire juste (error) => capture(error), ça devrait suffire

2023-04-06 16:09 UTC, naustra commented on api/src/controllers/young/index.js
> +    if (storedNonce !== decodedToken.nonce) {
Merge avec au dessus

2023-04-07 15:23 UTC, merged