Protect JWT from password change and logout
betagouv/service-national-universel pull request #2472
Opened 2023-04-10 18:34 UTC by naustra

2023-04-11 14:42 UTC, rap2hpoutre requested changes
Euh a priori non. Si tu es sûr de ton coup je suggère de mettre une explication avec une source vers ce qui a permis de choisir cette solution.

<img width="805" alt="Capture d’écran 2023-04-11 à 16 40 18" src="https://user-images.githubusercontent.com/1575946/231198762-7f25d338-0a40-4986-8058-7fc412e926c0.png">


<img width="829" alt="Capture d’écran 2023-04-11 à 16 40 31" src="https://user-images.githubusercontent.com/1575946/231198744-dc0e73cf-0fd5-4cbf-84ea-52fa090a8f40.png">

Donc selon moi c'est non. Je pense que pour ce genre de proposition il faut mettre du texte qui explique les choix, avec des sources pour pouvoir faire une discussion sur l'implémentation. Parce que peut-être que je loupe juste quelque chose là.

2023-04-11 19:15 UTC, naustra commented
@rap2hpoutre , j'ai changé la méthode. Je set l'heure de changement de password à la place du hash du password

2023-04-13 08:27 UTC, rap2hpoutre reviewed
Cool. 👍 

À noter qu'on n'a toujours pas la source de l'approche, donc on va dire que c'est Selego. C'est mieux de prendre quelque chose d'existant à quoi on peut se référer, mais je l'ai déjà signalé donc ok.

Que va-t-il se passer pour les personnes actuellement connectées au moment où on merge ? Ils sont déconnectés ?

2023-04-13 08:27 UTC, rap2hpoutre commented on api/src/auth.js
> +      const user = await this.model.findOne({ email }).select("+passwordChangedAt +lastLogoutAt");
Je conseille de charger ces deux champs à part si c'est possible. 

Comme on renvoie tout le temps le user, notre seul garde fou reste `serializeYoung` (mais en l'occurrence il ne filtre pas `lastLogoutAt` par exemple et donc c'est dur de savoir si c'est voulu et `passwordChangedAt` qui est une donnée que le user n'est pas censé avoir). Ou alors si il est censé l'avoir pourquoi on l'a rajouté dans le select ?

Bref, c'est à clarifier et à décider. Si le user ne doit pas avoir ces données alors on ne doit pas les lui donner. Si on souhaite les mettre dans ce cas on ne devrait pas avoir à les rajouter à la main.

2023-04-13 08:27 UTC, rap2hpoutre commented on api/src/auth.js
> +      const user = await this.model.findById(req.user._id).select("+lastLogoutAt");
Même remarque il faut trancher d'un côté ou d'un autre.

2023-04-13 08:27 UTC, rap2hpoutre commented on api/src/controllers/referent.js
> +    else if (type === "young") user = await YoungModel.findById(id).select("+passwordChangedAt +lastLogoutAt");
👀

2023-04-13 08:27 UTC, rap2hpoutre commented on lib/roles.js
> +  console.log("🚀 ~ file: roles.js:205 ~ canUpdateReferent ~ actor:", actor);
```suggestion
```

2023-04-13 09:08 UTC, naustra commented
> Cool. 👍
> 
> À noter qu'on n'a toujours pas la source de l'approche, donc on va dire que c'est Selego. C'est mieux de prendre quelque chose d'existant à quoi on peut se référer, mais je l'ai déjà signalé donc ok.
> 
> Que va-t-il se passer pour les personnes actuellement connectées au moment où on merge ? Ils sont déconnectés ?

Oui, elles seront déconnectées.

2023-04-13 10:51 UTC, naustra commented on api/src/auth.js
> +      const user = await this.model.findOne({ email }).select("+passwordChangedAt +lastLogoutAt");
Tu préféres si je mets select à true dans le model et que je mette dans le serializer ?
Ça serait ok pour toi ?

2023-04-13 10:56 UTC, rap2hpoutre commented on api/src/auth.js
> +      const user = await this.model.findOne({ email }).select("+passwordChangedAt +lastLogoutAt");
Oui ça peut être un choix 👍

2023-04-13 11:07 UTC, rap2hpoutre approved these changes
Super c'est bon pour moi !

2023-04-13 11:07 UTC, merged