fix(admin, api, app, kb): Correction de la suppression des apostrophes dans les noms de fichier avant téléversement
betagouv/service-national-universel pull request #2726
Opened 2023-06-21 10:29 UTC by nicobret

2023-06-28 11:05 UTC, naustra commented
Pourquoi on a 2 fois le name ici ?
formData.append(file.name, file, safeFilename);

2023-06-28 11:36 UTC, naustra requested changes

2023-06-28 11:36 UTC, naustra commented on admin/src/services/api.js
>      const names = arr.map((e) => e.name || e);
C'est surtout ici qu'il faut refiltrer

2023-06-28 11:36 UTC, naustra commented on admin/src/services/api.js
> +      Object.defineProperty(file, "name", {
Pas sur que cela soit necessaire si tu utilise safeFilename comme nom déja

2023-06-28 11:36 UTC, naustra commented on admin/src/services/api.js
> +    const safeFilename = encodeURIComponent(file.name.replaceAll(/'/g, ""));
function safeFileName(originalName) {
    // Replace problematic characters with underscore
    let safeName = originalName.replace(/['\\/:*?"<>|\x00-\x1F\x80-\x9F]/g, "_");

    // Trim leading and trailing whitespaces
    safeName = safeName.trim();

    // URI encode the file name to ensure it's safe for transport
    safeName = encodeURIComponent(safeName);

    return safeName;
}

function uploadFile(path, files) {
    let formData = new FormData();

    for (let file of files) {
        file.name = safeFileName(file.name);
        formData.append(file.name, file);
    }
}

Use this instead

2023-06-28 11:36 UTC, naustra commented on admin/src/services/api.js
> +    const safeFilename = encodeURIComponent(file.name.replaceAll(/'/g, ""));
Check how we use the key "file.name" from the back. Is it mandatory ?

2023-06-28 11:36 UTC, naustra commented on admin/src/services/api.js
> +      formData.append(file.name, file, safeFilename);
Not mandatory to put filename (3rd argument), it uses automatically name from file if file is type File

2023-06-28 11:36 UTC, naustra commented on app/src/services/api.js
>      const names = arr.map((e) => e.name || e);
Gere les noms surtout !

Et vérifier comment c'est utilisé côté back

2023-06-28 13:22 UTC, naustra commented on admin/src/services/api.js
>      const names = arr.map((e) => e.name || e);
enfin pas surtout, mais il faut

2023-06-28 13:38 UTC, naustra requested changes

2023-06-28 13:38 UTC, naustra commented on api/src/controllers/young/documents.js
> +        console.log("🚀 ~ file: documents.js:315 ~ data:", data)
non

2023-06-28 13:38 UTC, naustra commented on admin/src/services/api.js
>    uploadFile(path, arr, properties) {
uploadFileS

2023-06-28 13:38 UTC, naustra commented on packages/lib/file.js
> +  let allData = properties ? { names, ...properties } : { names };
const allData = { names, ...(properties || {}) };

2023-06-29 15:18 UTC, pierre-lebihan commented
Nicolas
  [12 h 38](https://selego.slack.com/archives/D03MWNXUQPP/p1688035135262589)
je sais pas mais je pense que c’est hors scope
cet array des noms de fichiers qui sert à rien c’est là depuis le tout premier commit sur le snu
j’ai l’impression qu’on est en train de se lancer dans un refacto complet des fonctions d’upload (au risque de casser des trucs qui marchaient) au lieu de juste améliorer le renommage des noms de fichiers (le sujet à la base)
bref j’ai testé en l’état et les fichiers s’affichent bien avec le bon nom côté front quand ils ont été mis en ligne, et le téléchargement fonctionne
si tu veux une analyse pour chaque route de la façon dont on utilise les donnés envoyées avec le fichier ça va prendre du temps


Pierre Le Bihan
  [13 h 04](https://selego.slack.com/archives/D03MWNXUQPP/p1688036697702799)
Bah t’as changé la logique pour l’id qd même
[13 h 05](https://selego.slack.com/archives/D03MWNXUQPP/p1688036717312389)
T’envoie plus “file”, t’envoie une key file.name a la place


Nicolas
  [13 h 05](https://selego.slack.com/archives/D03MWNXUQPP/p1688036727936719)
ah oui zut ça c’est une erreur


Pierre Le Bihan
  [13 h 05](https://selego.slack.com/archives/D03MWNXUQPP/p1688036728618619)
Donc je te demande si t’es sur
[13 h 05](https://selego.slack.com/archives/D03MWNXUQPP/p1688036747437359)
Bah ça veut dire qu’on en a besoin alors !
[13 h 06](https://selego.slack.com/archives/D03MWNXUQPP/p1688036770600879)
Je te demande pas de refacto mais de comprendre pouquoi on l’envoi 3 fois.
[13 h 07](https://selego.slack.com/archives/D03MWNXUQPP/p1688036839094589)
oui, mais compliqué maintenant que t’as unifié les fonctions
[13 h 07](https://selego.slack.com/archives/D03MWNXUQPP/p1688036862990759)
Tu peux pas dire ds le back de pas chercher “file” mais “file.name” du coup


Pierre Le Bihan
  [13 h 12](https://selego.slack.com/archives/D03MWNXUQPP/p1688037174396249)
Bon, ok. Reduplique les uploadID/uploadFiles
[13 h 13](https://selego.slack.com/archives/D03MWNXUQPP/p1688037224540599)
et Mets un capture dans upload files en cas de plus d’un fichier avec les infos de path et tout. Pour qu’on sache ou c’est fait. C’est une mauvaise idée je pense,
[13 h 14](https://selego.slack.com/archives/D03MWNXUQPP/p1688037275364399)
Et dans ce cas la, t’as pas besoin de creuser


Nicolas
  [13 h 20](https://selego.slack.com/archives/D03MWNXUQPP/p1688037618006449)
pourquoi il faut redupliquer maintenant :sanglot:
jpp :sourire:

2023-07-10 11:15 UTC, merged