feat(all): Rework jwt
betagouv/service-national-universel pull request #2727
Opened 2023-06-21 11:29 UTC by naustra

Check avec le support et la KB si pas de soucis

2023-06-28 07:24 UTC, hlecourt requested changes
Prendre la place jeune -> tu passe l'id du user connecté ca ne marche pas

2023-06-28 07:24 UTC, hlecourt commented on admin/src/scenes/volontaires/panel.jsx
> +                  if (!young) return toastr.error("Vous devez être connecté pour effectuer cette action.");
```suggestion
```

2023-06-28 07:24 UTC, hlecourt commented on admin/src/scenes/volontaires/panel.jsx
> +                  if (!young) return toastr.error("Vous devez être connecté pour effectuer cette action.");
ou modifier parce que : 
![image](https://github.com/betagouv/service-national-universel/assets/50077368/c5b31b80-5222-44ee-9387-9334d4303596)

2023-06-29 08:44 UTC, rap2hpoutre approved these changes
Génial ça marche, j'ai mis deux commentaires qui servent à rien !

2023-06-29 08:44 UTC, rap2hpoutre commented on api/src/auth.js
> +    const { error, value } = Joi.object({ token_ref: Joi.string(), token_young: Joi.string() }).validate({ token_ref: req.cookies.jwt_ref, token_young: req.cookies.jwt_young });
```suggestion
    const { error, value } = Joi.object({
      token_ref: Joi.string().allow('', null),
      token_young: Joi.string().allow('', null)
    }).or('token_ref', 'token_young').validate({ token_ref: req.cookies.jwt_ref, token_young: req.cookies.jwt_young });
```

Pour harder une rétrocompatibilité on pourrait s'assurer qu'un des deux est bien présent au moins.

EDIT: ah non on s'en fout tu le teste plus bas 😶

2023-06-29 08:44 UTC, rap2hpoutre commented on api/src/auth.js
> +      if (!data || !token) throw Error("PB with signin_token");
```suggestion
      if (!data || !token) throw Error("Error with signin_token");
```

2023-06-29 08:57 UTC, merged