feat(admin): paramétrage de l'alerte du tableau de bord
betagouv/service-national-universel pull request #2842
Opened 2023-07-27 08:40 UTC by C2Chandelier

https://www.notion.so/jeveuxaider/Param-trage-de-l-alerte-des-tableau-de-bord-93cd490aca774f0f8c3f85d518b5f1d7?pvs=4

2023-08-03 13:20 UTC, hlecourt requested changes

2023-08-03 13:20 UTC, hlecourt commented on api/src/controllers/dashboard/alerte-message.js
> +    if (!canCreateAlerteMessage(req.user)) return res.status(403).send({ ok: false, code: ERRORS.OPERATION_UNAUTHORIZED });
Route get avec une verif sur `canCreateAlerteMessage`

2023-08-03 13:20 UTC, hlecourt commented on api/src/models/alerteMessage.js
> +  },
On peux rajouter le user qui a fais la derniere action avec la date de derniere modif non ?

2023-08-03 13:20 UTC, hlecourt commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +  const InputOption = (props) => {
Ca sert a rien

2023-08-03 13:20 UTC, hlecourt commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +      setSelectedOptions(
Y'a pas plus simple ?

2023-08-03 13:20 UTC, hlecourt commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +      if (!data.to_role) errors.to_role = "Ce champ est obligatoire";
Il faut verifier aussi la length sinon je peux en ajouter puis tout supprimer, je passe ici

2023-08-03 13:20 UTC, hlecourt commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +      if (!data.to_role) errors.to_role = "Ce champ est obligatoire";
On avait dit aussi qu'on utilisais react hook form mais on ca passe pour celle la

2023-08-03 13:20 UTC, hlecourt commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +const CheckBox = ({ value }) => {
Niveau accessibilité c'est pas ouf

2023-08-03 13:20 UTC, hlecourt commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +const CheckBox = ({ value }) => {
C'est même nul

2023-08-03 13:20 UTC, hlecourt commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +                  <Select
La logique est simplifiable je pense

2023-08-03 13:20 UTC, hlecourt commented on api/src/controllers/dashboard/alerte-message.js
> +router.delete("/:id", passport.authenticate("referent", { session: false, failWithError: true }), async (req, res) => {
Je serais pour un soft delete ici, comme ca on a une archive

2023-08-03 13:20 UTC, hlecourt commented on admin/src/scenes/dashboardV2/moderator-ref/subscenes/general/index.jsx
> +        {/*         <InfoMessage
Autant supprimer non ?

2023-08-03 13:20 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/ui/InfoMessage.jsx
> +export default function InfoMessage({ bg = "", Icon = null, message = "", data = null }) {
Tu peux clean les props ici

2023-08-03 15:45 UTC, C2Chandelier commented on admin/src/scenes/dashboardV2/components/ui/InfoMessage.jsx
> +export default function InfoMessage({ bg = "", Icon = null, message = "", data = null }) {
on s'en sert dans d'autre composant du component InfoMessage donc je trouvais interessant de laisser les props pour continuer de s'en servir a l'avenir

2023-08-03 16:49 UTC, C2Chandelier commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +                  <Select
C'est quoi qui te vas pas ? le selectedoptions qui fait doublon ?

2023-08-03 16:50 UTC, C2Chandelier commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +  const InputOption = (props) => {
Ba j'ai suivis la doc de React Select. Il me faut des checkbox dans mon select j'ai regardé la doc ca m'a dit de faire comme ca...

2023-08-03 16:57 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/ui/InfoMessage.jsx
> +export default function InfoMessage({ bg = "", Icon = null, message = "", data = null }) {
Sur les missions c'est vrai !

2023-08-17 08:59 UTC, nicobret requested changes
Tout fonctionne mais il y a un peu de code à simplifier sur le formulaire (+ une mini remarque sur la validation en back).

2023-08-17 08:59 UTC, nicobret commented on admin/src/scenes/dashboardV2/components/ui/InfoMessage.jsx
> +import { HiOutlineExclamationCircle } from "react-icons/hi";
```suggestion
import { HiOutlineInformationCircle, HiOutlineExclamationCircle } from "react-icons/hi";
```

2023-08-17 08:59 UTC, nicobret commented on admin/src/scenes/dashboardV2/components/ui/InfoMessage.jsx
>        <Icon className="h-10 w-10 text-white" />
```suggestion
      <Icon className="h-10 w-10 text-white stroke-[1.5px]" />
```

2023-08-17 08:59 UTC, nicobret commented on admin/src/scenes/dashboardV2/components/ui/InfoMessage.jsx
>      <div className={`flex items-center gap-4 rounded-lg ${bg} p-4 text-base leading-5 text-white`}>
```suggestion
    <div className={`flex items-center gap-4 rounded-xl ${bg} p-4 text-base leading-5 text-white`}>
```

2023-08-17 08:59 UTC, nicobret commented on packages/lib/roles.js
> +}
Pas de messages d'alerte pour le transporteur ?

2023-08-17 08:59 UTC, nicobret commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +      setIsLoading(true);
Pas de confirmation avant suppression ? Avec un confirm() tout simple.
Exemple sur cette page :

<img width="1143" alt="Screenshot 2023-08-17 at 10 53 07" src="https://github.com/betagouv/service-national-universel/assets/95406348/aeda10b5-4221-473b-88d3-fd2b4a71c075">

2023-08-17 08:59 UTC, nicobret commented on admin/src/scenes/alerte/index.jsx
> +  }, [isNew]);
Pourquoi ?

2023-08-17 08:59 UTC, nicobret commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +  }, [editInfo]);
Pas besoin de ce useEffect (il cause des renders pour rien et rend le code trop compliqué).
Utiliser les arguments de la fonction useSate. Exemple :
`  const [editInfo, setEditInfo] = React.useState(isNew);
`
`  const [data, setData] = React.useState(message || {});
`
```
const [selectedOptions, setSelectedOptions] = React.useState(
    message
      ? message.to_role.map((role) => ({
          value: role,
          label: options.filter((item) => item.value === role)[0].label,
        }))
      : [],
  );
```

2023-08-17 08:59 UTC, nicobret commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +                  <Select
Effectivement je pense qu'on peut faire sans dupliquer le state de l'option choisie.

2023-08-17 08:59 UTC, nicobret commented on api/src/controllers/dashboard/alerte-message.js
> +    if (content.length > 500) return res.status(400).send({ ok: false, code: ERRORS.INVALID_PARAMS });
Utiliser la validation Joi à la place : `.max(500)`

2023-08-17 09:00 UTC, nicobret commented on admin/src/scenes/alerte/components/ModalAlerteMess.jsx
> +                  <Select
Effectivement je pense qu'on peut faire sans dupliquer le state de l'option choisie.

2023-08-18 14:29 UTC, nicobret approved these changes

2023-08-18 14:40 UTC, merged