chore: add kb and analytics to turbo workflow
betagouv/service-national-universel pull request #2984
Opened 2023-09-13 13:23 UTC by nicobret

- update turbo
- add knowledge-base & analytics to the list of workspaces started by turbo

2023-09-13 15:44 UTC, FlawaCLV requested changes
C'est top ! Juste, je pense que les icons react ce sont glissés dans ta PR ;-)

2023-09-13 15:44 UTC, FlawaCLV commented on admin/src/scenes/plan-transport/ligne-bus/View/components/Itineraire.jsx
Pas sûr que ça fasse partie du scope de la PR

2023-09-13 15:44 UTC, FlawaCLV commented on admin/src/scenes/volontaires/components/Equivalence.jsx
Pas sûr que ça fasse partie du scope de la PR

2023-09-13 15:44 UTC, FlawaCLV commented on admin/src/scenes/volontaires/view/phase2MilitaryPreparationV2.jsx
Pas sûr que ça fasse partie du scope de la PR

2023-09-13 15:44 UTC, FlawaCLV commented on app/package.json
Pas sûr que ça fasse partie du scope de la PR

2023-09-13 15:44 UTC, FlawaCLV commented on admin/package.json
Pas sûr que ça fasse partie du scope de la PR

2023-09-13 15:44 UTC, FlawaCLV commented on knowledge-base-public/package.json
Pas sûr que ça fasse partie du scope de la PR

2023-09-13 15:59 UTC, nicobret commented on admin/src/scenes/plan-transport/ligne-bus/View/components/Itineraire.jsx
En effet, on dirait que ça n'a pas de rapport, mais il fallait faire ça pour que ça marche après update :)
Ce que je crois comprendre, c'est qu'on importait des icônes qui existent dans certaines versions de react-icons (4.6 pour app et admin) mais pas dans les plus récentes (4.10 pour la bdc). Comme turborepo utilise autant que possible la meme version du package pour toutes les apps, ça ne marchait plus. D'où la modif.

2023-09-13 16:01 UTC, FlawaCLV commented on admin/src/scenes/plan-transport/ligne-bus/View/components/Itineraire.jsx
Ok, je comprends mieux. Top, je valide 🚀

2023-09-13 16:02 UTC, FlawaCLV approved these changes

2023-09-14 07:26 UTC, nicobret commented
Pb de versions de react. J'investigue.

2023-09-14 09:51 UTC, nicobret commented
Je clôt, division de cette PR en 2 (analytics/bdc).

2023-09-14 09:51 UTC, closed without merging