Feat(BDC-Front): Top article on Homepage + <span> on Emoji
betagouv/service-national-universel pull request #2994
Opened 2023-09-14 12:06 UTC by GuiPich91

2023-09-15 12:32 UTC, nicobret commented on knowledge-base-public/src/components/NavigationArticle.jsx
> +                        href={`${path}/${type === "section" ? slugTheme : slug}${type === "section" ? `?loadingType=section&openTheme=${slug}` : ""}`}
undefined

2023-09-15 12:39 UTC, nicobret commented on knowledge-base-public/src/components/knowledge-base/KnowledgeBaseArticleCard.js
> +      </div> */}
enlever

2023-09-15 12:40 UTC, nicobret commented on knowledge-base-public/src/components/knowledge-base/KnowledgeBaseArticleCard.js
> +        <h3 className="line-clamp-2 text-sm font-medium text-gray-900">{emoji}{text}</h3>
pb d'alignement : utliser le formatage prettier

2023-09-15 12:41 UTC, nicobret commented on knowledge-base-public/src/utils/index.js
> +    );
formatage

2023-09-15 12:41 UTC, nicobret commented on knowledge-base-public/src/utils/index.js
> +      emoji = <span className="mr-1" aria-hidden>{emoji}</span>;
formatage

2023-09-15 12:42 UTC, nicobret commented on knowledge-base-public/src/components/knowledge-base/KnowledgeBasePublicArticle.js
> +                <h1 className="mb-2 text-[24px] font-bold md:text-[30px] print:mb-0 print:text-black">{emoji}{text}</h1>
formatage

2023-09-15 12:43 UTC, nicobret commented on knowledge-base-public/src/components/knowledge-base/KnowledgeBasePublicSection.js
> +  const [top5Article, setTop5Article] = useState([]);
D'après le ticket c'est un top 4, non ? : https://www.notion.so/jeveuxaider/Front-BdC-Mise-en-avant-des-articles-sur-la-page-d-accueil-de-la-base-de-connaissance-40617d948f5246848d6aab3ea3120bac?pvs=4

2023-09-15 12:44 UTC, nicobret commented on knowledge-base-public/src/components/knowledge-base/KnowledgeBasePublicSection.js
> +        console.error(error);
capture plutot que console.error

2023-09-15 13:17 UTC, nicobret requested changes

2023-09-15 13:17 UTC, nicobret commented on knowledge-base-public/src/components/knowledge-base/KnowledgeBasePublicSection.js
> +        </div>
C'est un peu compliqué je trouve, pourquoi il y a une div dans une div et un h3 dans un Link dans une autre div ?
Proposition avec seulement deux balises :
```suggestion
          <div className="mx-auto mt-4 flex max-w-[90%] lg:max-w-[70%] flex-wrap justify-center gap-2">
            {top5Article.map(({ _id, slug, text }) => (
              <Link
                key={_id}
                className="rounded-full bg-blue-100 px-4 py-1 text-center text-sm font-medium leading-5 text-blue-800"
                href={`/base-de-connaissance/${slug}`}
                aria-label={`Lire l'article ${text}`}
              >
                {text}
              </Link>
            ))}
          </div>
```

2023-09-15 13:17 UTC, nicobret commented on knowledge-base-public/src/components/Accordion.js
> +                <li className="flex border-t border-gray-200 text-sm font-medium text-gray-900" key={index}>
Eviter d'utilier l'index comme key, ça peut provoquer des bugs. Plutôt key={slug}.

2023-09-15 13:17 UTC, nicobret commented on knowledge-base-public/src/components/knowledge-base/KnowledgeBasePublicSection.js
> +        <div className="flex h-40 w-full flex-col justify-end gap-6 border-t-[1px] border-white border-opacity-20 bg-[#32257F]">
Le titre "J'ai besoin d'aide" et la barre de recherche sont trop bas maintenant : quand on clique sur la barre, la modale ne s'affiche plus au meme niveau que la barre.

2023-09-19 09:14 UTC, szilagyikinga commented on knowledge-base-public/src/utils/index.js
> +        <span className="mr-1" aria-hidden>
je propose de retourner juste le texte pour l'emoji et faire un composant Emoji pour le span 

```
const Emoji = ({emoji, className = "mr-1"}) => {
  return <span className={className} aria-hidden>{emoji}</span>;
}
```

2023-09-20 14:22 UTC, merged