feat(admin/api) creation du dashboard en Vue Responsable et Superviseur
betagouv/service-national-universel pull request #3058
Opened 2023-09-28 08:19 UTC by C2Chandelier

2023-10-02 13:41 UTC, FlawaCLV requested changes
@C2Chandelier quelques minis retours mais surtout pense à rebase cette branche et refaire une série de tests ;-)

`git rebase --autosquash -i origin/main`

2023-10-02 13:41 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/moderator-ref/subscenes/general/components/CustomFilter.jsx
>  import DatePicker from "../../../../../../components/ui/forms/DatePicker";
```suggestion
import DatePicker from "@/components/ui/forms/DatePicker";
```

2023-10-02 13:41 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/moderator-ref/subscenes/general/components/CustomFilter.jsx
> +        {role === ROLES.RESPONSIBLE || role === ROLES.SUPERVISOR ? <span>Filtres (1)</span> : <span>Filtres (2)</span>}
```suggestion
        {[ROLES.RESPONSIBLE, ROLES.SUPERVISOR].includes(role) ? <span>Filtres (1)</span> : <span>Filtres (2)</span>}
```

2023-10-02 13:41 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/moderator-ref/subscenes/general/components/CustomFilter.jsx
> +        {role === ROLES.RESPONSIBLE || role === ROLES.SUPERVISOR ? <span>Filtres (1)</span> : <span>Filtres (2)</span>}
Ça fait le même taf mais un peu plus simple à maintenir/lire

2023-10-02 13:41 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/moderator-ref/subscenes/general/components/CustomFilter.jsx
> +              {role === ROLES.RESPONSIBLE || role === ROLES.SUPERVISOR ? null : (
Idem avec `[ROLES.RESPONSIBLE, ROLES.SUPERVISOR].includes(role)`

2023-10-02 13:41 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/responsible/subscenes/general/index.jsx
> +import { capture } from "../../../../../sentry";
```suggestion
import { capture } from "@/sentry";
```

2023-10-02 13:41 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/responsible/subscenes/general/index.jsx
> +import api from "../../../../../services/api";
```suggestion
import api from "@/services/api";
```

2023-10-02 13:41 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/responsible/subscenes/general/index.jsx
> +  React.useEffect(() => {
```suggestion
 useEffect(() => {
```

2023-10-02 13:41 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/responsible/subscenes/general/index.jsx
> +  React.useEffect(() => {
```suggestion
 useEffect(() => {
```

2023-10-02 13:41 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/responsible/subscenes/general/index.jsx
@C2Chandelier pense à bien `rebase` cette branche car il y a eut une refactor des todo.

Pour info: `git rebase --autosquash -i origin/main`

2023-10-02 13:41 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/responsible/subscenes/general/index.jsx
> +import React, { useState } from "react";
```suggestion
import React, { useState, useEffect } from "react";
```

2023-10-02 13:41 UTC, FlawaCLV commented on admin/src/scenes/volontaires-responsible/listV2.jsx
>  } from "../../utils";
```suggestion
} from "@/utils";
```

2023-10-19 15:20 UTC, hlecourt approved these changes

2023-10-19 15:20 UTC, hlecourt commented on admin/src/components/filters-system-v2/components/Filters.jsx
> +        console.log(dataFilter)
```suggestion
```

2023-10-19 15:20 UTC, hlecourt approved these changes

2023-10-19 15:21 UTC, merged