feat(admin/api): création vue dashboard Head-Center
betagouv/service-national-universel pull request #3090
Opened 2023-10-09 15:26 UTC by C2Chandelier

2023-10-11 12:20 UTC, hlecourt requested changes

2023-10-11 12:20 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/Todos.jsx
> +      columns.push(columnInscription, columnSejour);
? il y a juste sejour non ?

2023-10-11 12:20 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/inscription/Details.jsx
On utilise ca coter head-center ?

2023-10-11 12:20 UTC, hlecourt commented on api/src/controllers/elasticsearch/dashboard/inscription.js
Pourquoi ?

2023-10-11 12:20 UTC, hlecourt commented on admin/src/scenes/dashboardV2/head-center/subscenes/sejour/index.jsx
> +    status: [YOUNG_STATUS.VALIDATED],
Doit etre gerée dans le back vu que tu as route specifique

2023-10-11 12:20 UTC, hlecourt commented on admin/src/scenes/dashboardV2/moderator-ref/subscenes/sejour/components/OccupationBarVertical.jsx
Si use par plusieurs dossier on deplace les composants dans le parents

2023-10-11 12:20 UTC, hlecourt commented on admin/src/scenes/dashboardV2/moderator-ref/subscenes/sejour/components/Presences.jsx
Si use par plusieurs dossier on deplace les composants dans le parents

2023-10-11 12:20 UTC, hlecourt commented on admin/src/scenes/dashboardV2/moderator-ref/subscenes/sejour/components/StatusPhase1.jsx
Si use par plusieurs dossier on deplace les composants dans le parents

2023-10-11 12:20 UTC, hlecourt commented on admin/src/scenes/dashboardV2/moderator-ref/subscenes/sejour/components/StatusPhase1.jsx
> +          {role === ROLES.HEAD_CENTER && (
legacy plus de liste complementaire affecté

2023-10-11 12:20 UTC, hlecourt commented on admin/src/scenes/dashboardV2/moderator-ref/subscenes/sejour/components/StatusPhase1.jsx
> +          {role === ROLES.HEAD_CENTER && (
Same on desiste plus sur des phase 1 + tu filtre par default sur statut validé (0 desisté dans tous les cas)

2023-10-11 12:20 UTC, hlecourt commented on api/src/controllers/session-phase1.js
Pourquoi ?

2023-10-11 12:24 UTC, hlecourt reviewed
![image](https://github.com/betagouv/service-national-universel/assets/50077368/0f3c2254-08f2-4490-96f0-508fa9a62b41)
Adapter la vue genérale quand on a pas de keynumbers 
Maybe une autre PR

2023-10-11 12:27 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/Todos.jsx
> +      columns.push(columnInscription, columnSejour);
ok vu dans les chiffre clés mais par default on met tout dans une colonne

2023-10-11 12:28 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/inscription/Details.jsx
ok vu

2023-10-11 12:28 UTC, hlecourt commented on api/src/controllers/elasticsearch/dashboard/inscription.js
ok

2023-10-11 13:08 UTC, C2Chandelier commented on api/src/controllers/session-phase1.js
j'aime bien faire des routes

2023-10-12 07:03 UTC, hlecourt commented on admin/src/scenes/dashboardV2/head-center/subscenes/general/index.jsx
> +    const updateStats = async () => {
Pourquoi ne pas mettre ce call dans le composant todo ?

2023-10-12 07:03 UTC, hlecourt commented on admin/src/scenes/dashboardV2/head-center/subscenes/sejour/index.jsx
> +    status: [YOUNG_STATUS.VALIDATED],
up

2023-10-13 07:38 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/sejour/Presences.jsx
> +  console.log(sessionId);
```suggestion
```

2023-10-13 07:38 UTC, hlecourt commented on api/src/controllers/elasticsearch/dashboard/inscription.js
> +            session ? { terms: { "sessionPhase1Id.keyword": [session._id] } } : null,
On prend que les jeunes validé aussi ici non ?

2023-10-13 07:38 UTC, hlecourt commented on api/src/controllers/elasticsearch/dashboard/inscription.js
> +            session ? { terms: { "sessionPhase1Id.keyword": [session._id] } } : null,
si head center ?

2023-10-13 08:06 UTC, hlecourt approved these changes

2023-10-13 08:08 UTC, merged