feat/fix(admin): disconnected redirect, updated footer, CNI preview
betagouv/service-national-universel pull request #3098
Opened 2023-10-11 15:19 UTC by FlawaCLV

2023-10-23 16:44 UTC, naustra requested changes

2023-10-23 16:44 UTC, naustra commented on admin/src/scenes/phase0/components/CniField.jsx
> +                      href={api.apiURL + "/young/" + young._id + "/documents/cniFiles/" + file._id + "?" + queryString.stringify({ token: api.token, preview: 1 })}
Mets l'url en variable du composant plutot, c'est trop complexe la

2023-10-23 16:44 UTC, naustra commented on admin/src/services/api.js
> +    this.apiURL = apiURL;
Pourquoi changer ça ?

2024-02-01 16:23 UTC, naustra commented
@FlawaCLV on kill ça du coup ?

2024-02-01 16:49 UTC, closed without merging

2024-02-01 16:50 UTC, FlawaCLV commented
> @FlawaCLV on kill ça du coup ?

Yes, je viens de close. Bien vu.