feat(admin/api): dashboard visitors
betagouv/service-national-universel pull request #3107
Opened 2023-10-17 13:41 UTC by tangimds

2023-10-17 13:56 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/visitor/subscenes/inscription/index.jsx
> +import api from "../../../../../services/api";
```suggestion
import api from "@/services/api";
```

2023-10-17 13:56 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/visitor/subscenes/inscription/index.jsx
> +import { orderCohort } from "../../../../../components/filters-system-v2/components/filters/utils";
```suggestion
import { orderCohort } from "@/components/filters-system-v2/components/filters/utils";
```

2023-10-17 13:56 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/visitor/subscenes/inscription/index.jsx
> +import plausibleEvent from "../../../../../services/plausible";
```suggestion
import plausibleEvent from "@/services/plausible";
```

2023-10-17 13:56 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/visitor/subscenes/inscription/index.jsx
> +import { getNewLink } from "../../../../../utils";
```suggestion
import { getNewLink } from "@/utils";
```

2023-10-17 13:56 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/visitor/subscenes/inscription/index.jsx
> +  });
Je me demande si on a pas une constante dans `snu-lib`. (Ping @hlecourt)

```suggestion
  const [selectedFilters, setSelectedFilters] = useState({
    cohort: ["Février 2023 - C", "Avril 2023 - A", "Avril 2023 - B", "Juin 2023", "Juillet 2023", "Octobre 2023 - NC"],
  });
```

2023-10-17 13:56 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/visitor/subscenes/inscription/index.jsx
Beaucoup de code dupliqué par rapport à `admin/src/scenes/dashboardV2/moderator-ref/subscenes/inscription/index.jsx`.

Je pense que ça vaut le coup de refacto comme l'a fait @C2Chandelier sur `admin/src/scenes/dashboardV2/components/General.jsx`

2023-10-18 18:14 UTC, tangimds commented on admin/src/scenes/dashboardV2/components/inscription/TabSchool.jsx
> +        {user.role === ROLES.REFERENT_REGION ? (
exemple de condition que j'aime pas quand on factorise ce genre d'écran

2023-10-18 18:36 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/components/inscription/TabSchool.jsx
> +        {user.role === ROLES.REFERENT_REGION ? (
Oui je comprends, c'est comme les `if (ENV === "production")` c'est pourquoi on a créé des features flags où tu peux activer/désactiver une feature en fonction de l'environnement et du rôle.

2023-10-19 15:57 UTC, hlecourt requested changes

2023-10-19 15:57 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/inscription/General.jsx
> +      ![ROLES.REFERENT_DEPARTMENT, user.role === ROLES.VISITOR].includes(user.role)
bizarre

2023-10-19 15:57 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/inscription/General.jsx
> +      ![ROLES.REFERENT_DEPARTMENT, user.role === ROLES.VISITOR].includes(user.role)
bizarre

2023-10-19 15:57 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/inscription/TabSchool.jsx
> +          {user.role === ROLES.REFERENT_REGION ? (
no needs

2023-10-19 15:57 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/inscription/TabSchool.jsx
> +        {user.role === ROLES.REFERENT_REGION ? (
no needs

2023-10-19 15:57 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/inscription/General.jsx
> +        options: COHORTS.map((cohort) => ({ key: cohort, label: cohort })),
on a changer pendant ta PR le systeme on va les chercher en ligne mtn (dans le redux)
Je te laisse check main / les autres dashboard pour t'aligner

2023-10-19 15:57 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/inscription/General.jsx
> +    user.role === ROLES.REFERENT_REGION || user.role === ROLES.VISITOR ? [{ key: user.region, label: user.region }] : regionList.map((r) => ({ key: r, label: r }));
Petit include

2023-10-19 15:57 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/inscription/General.jsx
> +    user.role === ROLES.REFERENT_REGION || user.role === ROLES.VISITOR
Petit include

2023-10-20 07:30 UTC, tangimds commented on admin/src/scenes/dashboardV2/components/inscription/General.jsx
> +      ![ROLES.REFERENT_DEPARTMENT, user.role === ROLES.VISITOR].includes(user.role)
yes ca fait une logique bizarre

si c'est ni un ref depaertemental, ni un visiteur, il peut choisir nimporte quelle région

2023-10-20 09:09 UTC, hlecourt commented on admin/src/scenes/dashboardV2/components/common.js
> +  const departmentOptions = user.role === ROLES.REFERENT_REGION || user.role === ROLES.VISITOR ? region2department[user.region] : departmentList;
hum il y en a un qui traine encore

2023-10-20 09:37 UTC, FlawaCLV commented on admin/src/scenes/dashboardV2/visitor/subscenes/inscription/index.jsx
> +  });
@hlecourt question: est-ce que les cohorts on va les chercher toujours via `const cohorts = useSelector((state) => state.Cohorts);` maintenant ?

2023-10-20 09:38 UTC, hlecourt commented on admin/src/scenes/dashboardV2/visitor/subscenes/inscription/index.jsx
> +  });
yes c'est le refacto de kinga pour mettre les cohort en ligne !

2023-10-23 08:43 UTC, hlecourt approved these changes

2023-10-23 08:44 UTC, merged