test de partage de components entre head-center et responsible
betagouv/service-national-universel pull request #311
Opened 2021-06-23 09:03 UTC by hugo3m

Exemple de ce qu'on devrait faire si on voulait refactor les components  qui sont pareil (ou presque). Je suis pas sûr que ce soit vraiment pertinent parce que dans ce cas on pourrait avoir un seul composant unique avec pleins de conditions d'affichage ? Honnêtement aucune idée en tout cas c'est faisable

2021-06-29 09:34 UTC, rap2hpoutre approved these changes
Moi ça me semble bien parce que tu as enlevé une grosse duplication et que je suis pour avancer pas à pas. Mais j'aimerai l'avis de @tangimds aussi

2021-06-29 10:30 UTC, tangimds reviewed
Il faudra dans tous les cas refacto ces composants. donc c'est une bonne idée de base !
On peut le faire petit à petit comme ça effectivement, comme on le fait pour d'autre sujets, c'est moins risqué et moins de charge de travail en oneshot.
Cependant, je ne trouve pas intuitif le fait que la vue d'un chef de centre soit dans `scenes/volontaires-head-center`, et qu'on utilise des composant d'une autre `scene` avec des conditions.

Proposition : sortir complètement ces composants, les mettre dans `components/volontaire-view` (ou je ne sais pas comment vous préférez l'appeler). Et on appelle ce composant depuis `scenes/volontaires-head-center` et `scenes/volontaires-responsible`. Ducoup le render conditionnel prend plus de sens (puisque le composant est a l'exterieur). En fait, je pense que c'est plus explicite d'utiliser un 'vrai' composant plutot que d'aller chercher une bribe de code dans une autre scene et de mettre des `if`.

*Voir dans le wrapper de `volontaire-responsible` un `if(role === head-center)` alors qu'il existe un wrapper `volontaire-head-center` est embrouillant, je trouve*

2021-06-29 12:07 UTC, rap2hpoutre commented
Je suis convaincu !

2021-06-29 12:08 UTC, hugo3m commented
Convaincu aussi

2021-06-29 12:36 UTC, rap2hpoutre requested changes
En attente de refacto

2021-06-30 10:04 UTC, tangimds commented on admin/src/scenes/volontaires-responsible/view/wrapper.js
> +          </TabList>
je ne comprends pas ce que ca fait ca ? avec le contrat ? `tab` ne peut jamait etre égal à `contract` j'ai l'impression ?

2021-06-30 10:04 UTC, tangimds commented on admin/src/scenes/volontaires-responsible/view/wrapper.js
>      <div style={{ flex: tab === "missions" ? "0%" : 2, position: "relative", padding: "3rem" }}>
`tab === mission` ?
je crois qu'on peut virer, un vieux copier coller mal maitrisé de ma part tres cetainement :)

2021-06-30 12:29 UTC, merged