Feat/address autocomplete
betagouv/service-national-universel pull request #3121
Opened 2023-10-23 06:56 UTC by szilagyikinga

2023-10-24 16:27 UTC, GuiPich91 commented on app/src/scenes/inscription2023/steps/stepCoordonnees.jsx
>          region: young.region || data.region,
Problème sur le champ département, on récup un undefined

2023-10-24 16:28 UTC, GuiPich91 requested changes
Il y a un petit soucis sur le champ département.
Problème aussi sur l'affichage du dropDown par rapport à la maquette. On devrait afficher les libellés de rues, hors on affiche le zip code à la place

2023-10-25 08:23 UTC, nicobret commented on app/src/scenes/inscription2023/steps/stepCoordonnees.jsx
>          region: young.region || data.region,
Bien vu, c'est corrigé.

2023-10-25 08:25 UTC, nicobret commented
> Il y a un petit soucis sur le champ département. Problème aussi sur l'affichage du dropDown par rapport à la maquette. On devrait afficher les libellés de rues, hors on affiche le zip code à la place

C'est corrigé, merci !

2023-10-25 09:32 UTC, GuiPich91 approved these changes
- Auto complete de l'adresse et modification de l'adresse du jeune Ok
- Modification effective sur app et admin Ok
- Modification de l'adresse du RL sur la partie inscription et Image right Ok
- Modification effective sur admin Ok

figma respecté, on est tout bon !

2023-10-25 10:26 UTC, merged