refacto(api): cloisonnement par role et 403 sur les requete des dashboards
betagouv/service-national-universel pull request #3122
Opened 2023-10-23 12:04 UTC by C2Chandelier

https://www.notion.so/jeveuxaider/Refacto-Gestion-des-roles-controller-dashboard-cloisonnement-403-f0c31303e7704e1b82183da3f3fd70f2?pvs=4
https://www.notion.so/jeveuxaider/Refacto-Gestion-des-roles-controller-dashboard-cloisonnement-donn-es-par-roles-67b60a6f3e364767b32658ac77f580ec?pvs=4

2023-10-23 12:49 UTC, FlawaCLV commented on api/src/controllers/elasticsearch/dashboard/engagement.js
> +const { ES_NO_LIMIT, ROLES, APPLICATION_STATUS, canSeeAllDashboardEngagementInfo, canSeeDashboardEngagementInfo } = require("snu-lib");
Je trouve que c'est pas assez clair la diff entre les 2. C'est quoi la diff ?

2023-10-23 12:53 UTC, FlawaCLV commented on packages/lib/roles.js
> +}
```suggestion
function canSeeDashboardEngagementInfo(actor) {
  return [ROLES.ADMIN, ROLES.REFERENT_REGION, ROLES.REFERENT_DEPARTMENT].includes(actor.role);
}
```

2023-10-23 12:54 UTC, FlawaCLV commented on packages/lib/roles.js
> +}
```suggestion
function canSeeDashboardEngagementStatus(actor) {
  return [ROLES.SUPERVISOR, ROLES.RESPONSIBLE].includes(actor.role);
}
```

2023-10-23 14:13 UTC, FlawaCLV approved these changes

2023-10-24 07:44 UTC, hlecourt requested changes

2023-10-24 07:44 UTC, hlecourt commented on api/src/controllers/elasticsearch/utils.js
> +
Il manque la gestion des visiteurs -> buildDashboardUserRoleContext

2023-10-24 08:22 UTC, C2Chandelier commented on api/src/controllers/elasticsearch/utils.js
> +
my bad j'avais zappé que c'etait des ref reg bizarre ceux la ^^

2023-10-24 12:20 UTC, hlecourt approved these changes

2023-10-24 12:22 UTC, merged