chore(app): Refacto inscription
betagouv/service-national-universel pull request #3145
Opened 2023-10-27 09:53 UTC by GuiPich91

2023-10-30 14:54 UTC, nicobret requested changes
- Pre-inscription : le stepper est en 2 étapes au lieu de 3 (mais il y a bien l’étape 1) : c’est normal ?
- J'ai pas compris le point "Mettre en BDD un numéro de tel invalide"
- Il manque un message d’erreur sur la situation scolaire : j’ai cliqué sur continuer sur un jeune en réinscription sans préciser sa situation (scolarisé, apprentissage etc.)
=> pourquoi c’est vide ? dossier trop ancien/incohérent ?
=> il faut ajouter un message “ce champ doit être renseigné”.

Le reste est bon pour moi !

2023-10-30 15:14 UTC, hlecourt commented on api/src/controllers/young/inscription2023.js
> +      return res.status(400).send({ ok: false, code: ERRORS.INVALID_PARAMS, msg: error.message });
J'aime pas trop ca ! On peux pas le gerer dans le front en premier lieux ? Permet un un user pas content de connaitre toute nos erreurs

2023-10-30 15:14 UTC, hlecourt commented on app/src/scenes/inscription2023/steps/stepRepresentants.jsx
> +          if (msg && msg.includes("parent1Email")) {
Autant le gerer ducoup avant d'envoyer sur l'api ?

2023-10-30 15:19 UTC, hlecourt commented on api/src/controllers/young/inscription2023.js
> +      return res.status(400).send({ ok: false, code: ERRORS.INVALID_PARAMS, msg: error.message });
C'était dans notre premiere audit de secu il me semble ne pas retourné d'erreur depuis le back

2023-10-30 15:20 UTC, nicobret commented on api/src/controllers/young/inscription2023.js
> +      return res.status(400).send({ ok: false, code: ERRORS.INVALID_PARAMS, msg: error.message });
Le problème c'est qu'on a du mal à aligner la validation d'email front (librairie validator) et back (joi.isEmail) : il y a des cas où un email peut être jugé valide en front mais pas en back => l'idée était de renvoyer l'erreur détaillée depuis le back pour gérer ces cas-là (sinon on a une erreur générique mais pas d'indication pour l'user que c'est l'email qui passe pas).

2023-10-31 09:24 UTC, GuiPich91 commented on api/src/controllers/young/inscription2023.js
> +      return res.status(400).send({ ok: false, code: ERRORS.INVALID_PARAMS, msg: error.message });
On priorise sur un autre ticket la semaine prochaine !
intégrons joi niveau front pour les phase d'inscription/pré-inscription/ etc.. ? afin d'être similaire au back ?

2023-10-31 09:41 UTC, nicobret approved these changes

2023-10-31 10:42 UTC, merged