feat(api): 1406 - CLE Create classe
betagouv/service-national-universel pull request #3264
Opened 2023-11-14 15:33 UTC by FlawaCLV

2023-11-15 13:35 UTC, hlecourt commented on api/src/controllers/cle/classe.js
> +    if (!etablissement) return res.status(403).send({ ok: false, code: ERRORS.OPERATION_UNAUTHORIZED });
404 ?

2023-11-15 13:35 UTC, hlecourt commented on api/src/controllers/cle/classe.js
> +    session = await mongoose.startSession();
?

2023-11-15 13:35 UTC, hlecourt commented on api/src/controllers/cle/classe.js
> +        sousChefIds: [...etablissement.sousChefIds, referent._id.toString()],
on limite pas a 1 ?

2023-11-15 13:35 UTC, hlecourt commented on api/src/controllers/cle/classe.js
> +    classe = await classe.save();
fromuser

2023-11-15 13:35 UTC, hlecourt commented on api/src/controllers/cle/classe.js
> +      uniqueId: Joi.string().alphanum().min(1).max(5).required(),
on prevois pas d'avoir de cohort pour le moment ? Par defaut c'est CLE 23 24 mais ca doit pouvoir changer

2023-11-15 13:35 UTC, hlecourt commented on api/src/controllers/cle/classe.js
> +    session = await mongoose.startSession();
Pour faire une session ici et ne pas juste faire partout ?

2023-11-15 13:38 UTC, hlecourt requested changes

2023-11-15 13:38 UTC, hlecourt commented on api/src/controllers/cle/classe.js
> +        sousChefIds: [...etablissement.sousChefIds, referent._id.toString()],
Ca n'a pas lieu d'etre enfaite ici 
Pourquoi un ref de classe se retrouve dans les coordinateur de l'etablissement ?

2023-11-15 13:51 UTC, FlawaCLV commented on api/src/controllers/cle/classe.js
> +    if (!etablissement) return res.status(403).send({ ok: false, code: ERRORS.OPERATION_UNAUTHORIZED });
Humm oui et non. Oui 404 si la ressource n'existe pas mais je recherche le document pour lequel l'utilisateur est `chefId`

2023-11-15 13:53 UTC, FlawaCLV commented on api/src/controllers/cle/classe.js
> +        sousChefIds: [...etablissement.sousChefIds, referent._id.toString()],
Oui effectivement, mais honnêtement le mélange franglais amène bcp de confusion... On utilise `coordinateur` mais là c'est `sousChef`. Si même moi qui suis briefé je me trompe, imagine un noob qui monte en compétence sur la plateforme.

2023-11-15 13:54 UTC, FlawaCLV commented on api/src/controllers/cle/classe.js
> +      uniqueId: Joi.string().alphanum().min(1).max(5).required(),
Plus bas je vais chercher la cohorte par défaut. Il faudrait pouvoir gérer ça avec un `defaultCleCohort: true` dans le modèle `Cohorte` par exemple. Qu'en penses-tu ?

2023-11-15 13:57 UTC, FlawaCLV commented on api/src/controllers/cle/classe.js
> +    session = await mongoose.startSession();
Oui partout où ça du sens (plusieurs inserts), carrément !

2023-11-15 13:57 UTC, FlawaCLV commented on api/src/controllers/cle/classe.js
> +    classe = await classe.save();
Yes 👍🏻

2023-11-15 14:00 UTC, hlecourt commented on api/src/controllers/cle/classe.js
> +        sousChefIds: [...etablissement.sousChefIds, referent._id.toString()],
Go changer le wording de chefids a : referent_etablissementID et sousChef a coordinateur ?

2023-11-15 14:01 UTC, hlecourt commented on api/src/controllers/cle/classe.js
> +    session = await mongoose.startSession();
Un c'etait pas la question + pourquoi tu fais une session ? On a pas reellement besoin

2023-11-15 14:03 UTC, FlawaCLV commented on api/src/controllers/cle/classe.js
> +    session = await mongoose.startSession();
Je créé une session car c'est comme cela que l'on créé une transaction en mongoose...

2023-11-15 14:07 UTC, FlawaCLV commented on api/src/controllers/cle/classe.js
> +        sousChefIds: [...etablissement.sousChefIds, referent._id.toString()],
Pour garder la cohérence du camel case et du type de variables (tableau d'ID), je propose `referentEtablissementIds` et `coordinateurIds`. Ça t'irait ?

2023-11-16 14:38 UTC, hlecourt approved these changes

2023-11-16 14:38 UTC, merged