feat(api/admin/lib/ds): liste user for new role CLE
betagouv/service-national-universel pull request #3267
Opened 2023-11-15 13:24 UTC by hlecourt

2023-11-16 15:27 UTC, FlawaCLV requested changes

2023-11-16 15:27 UTC, FlawaCLV commented on admin/src/scenes/utilisateur/edit/details.jsx
> +            {!isSaving && roleMode !== MODE_DEFAULT && (
C'est quoi le `MODE_DEFAULT` ?

2023-11-16 15:27 UTC, FlawaCLV commented on admin/src/scenes/utilisateur/list.jsx
> +        <span className="font-bold text-gray-900 text-base leading-5">{hit.status !== "DELETED" ? `${hit.firstName} ${hit.lastName}` : "Compte supprimé"}</span>
Il n'y a pas une variable dans `snu-lib` pour ce statut `"DELETED"` ?

2023-11-16 15:27 UTC, FlawaCLV commented on api/src/controllers/elasticsearch/referent.js
> +    const etablissement = await EtablissementModel.findOne({ chefIds: user._id });
```suggestion
    const etablissement = await EtablissementModel.findOne({ referentEtablissementIds: user._id });
```

2023-11-16 15:27 UTC, FlawaCLV commented on api/src/controllers/elasticsearch/referent.js
> +    refIds.push(...classes.flatMap((c) => c.classeReferentIds), ...etablissement.chefIds, ...etablissement.sousChefIds);
J'ai inversé pour plus de cohérence avec le modèle `Etablissement`

```suggestion
    refIds.push(...classes.flatMap((c) => c.referentClasseIds), ...etablissement.referentEtablissementIds, ...etablissement.coordinateurIds);
```

2023-11-16 15:27 UTC, FlawaCLV commented on api/src/controllers/elasticsearch/referent.js
> +    const classes = await ClasseModel.findOne({ classeReferentIds: user._id });
```suggestion
    const classes = await ClasseModel.findOne({ referentClasseIds: user._id });
```

2023-11-16 15:27 UTC, FlawaCLV commented on api/src/controllers/elasticsearch/referent.js
> +    const refIds = [...etablissement.chefIds, ...etablissement.sousChefIds];
```suggestion
    const refIds = [...etablissement.referentEtablissementIds, ...etablissement.coordinateurIds];
```

2023-11-16 15:27 UTC, FlawaCLV commented on packages/lib/roles.js
> +  const isReferentClasse = actor.role === ROLES.REFERENT_CLASSE && [ROLES.REFERENT_DEPARTMENT, ROLES.REFERENT_CLASSE, ROLES.ADMINISTRATEUR_CLE].includes(target.role);
Je ne comprends pas ces conditions. Tu testes `ROLES.ADMINISTRATEUR_CLE && [..., ROLES.ADMINISTRATEUR_CLE]` ?

C'est quoi `target` ici ?

2023-11-16 15:52 UTC, hlecourt commented on packages/lib/roles.js
> +  const isReferentClasse = actor.role === ROLES.REFERENT_CLASSE && [ROLES.REFERENT_DEPARTMENT, ROLES.REFERENT_CLASSE, ROLES.ADMINISTRATEUR_CLE].includes(target.role);
Le user que tu veux voir

2023-11-16 15:53 UTC, hlecourt commented on admin/src/scenes/utilisateur/edit/details.jsx
> +            {!isSaving && roleMode !== MODE_DEFAULT && (
Pas d'editable

2023-11-16 15:53 UTC, hlecourt commented on admin/src/scenes/utilisateur/list.jsx
> +        <span className="font-bold text-gray-900 text-base leading-5">{hit.status !== "DELETED" ? `${hit.firstName} ${hit.lastName}` : "Compte supprimé"}</span>
Si certaiment j'ai rien changer ici

2023-11-17 08:37 UTC, FlawaCLV approved these changes

2023-11-17 08:50 UTC, merged