feat(api): 1403 - CLE referents signup
betagouv/service-national-universel pull request #3270
Opened 2023-11-15 16:50 UTC by FlawaCLV

2023-11-16 16:37 UTC, hlecourt requested changes

2023-11-16 16:37 UTC, hlecourt commented on api/src/controllers/cle/referent-signup.js
> +    delete referent.password;
serialize ref dans le res

2023-11-17 08:57 UTC, hlecourt reviewed
On créér ou l'établissement lié au ref ?

2023-11-17 12:41 UTC, FlawaCLV commented
> On créér ou l'établissement lié au ref ?

C'est une invitation d'un ADMINISTRATEUR_CLE donc il a son Etablissement par lequel il est rattaché

2023-11-17 14:28 UTC, hlecourt commented
> > On créér ou l'établissement lié au ref ?
> 
> C'est une invitation d'un ADMINISTRATEUR_CLE donc il a son Etablissement par lequel il est rattaché

Hum non il a rien ducoup ^^ il y a juste l'admin cle coordinateur qui aura son établissement

2023-11-20 09:56 UTC, hlecourt approved these changes

2023-11-20 09:56 UTC, merged