up
betagouv/service-national-universel pull request #328
Opened 2021-06-30 08:44 UTC by hugo3m

2021-06-30 12:53 UTC, hugo3m commented
Je crois avoir fais les principaux, certains dans edit utilisaient déjà le LoadingButton

2021-06-30 18:23 UTC, tangimds requested changes
C'est niquel.
quand on enregistre un contrat, les deux boutons chargent. c'est un comportement que l'on veut éviter je pense.
j'ai regardé vite fais, c'est peut etre un peu chiant de gérer les deux boutons. mais si tu peux le faire ce serait cool je pense :)

2021-06-30 18:23 UTC, tangimds commented on admin/src/components/Contract.js
> +                    loading={loading}
tu utilises le meme `loading` pour les deux boutons !
il faudrait en faire un par bouton

2021-07-01 09:39 UTC, hugo3m commented on admin/src/components/Contract.js
> +                    loading={loading}
yo

2021-07-01 10:16 UTC, tangimds approved these changes
yes, let's go !

2021-07-01 10:17 UTC, merged