fix(api): Save parents email as lowercase
betagouv/service-national-universel pull request #3398
Opened 2023-12-20 10:09 UTC by nicobret

# Description

Fixes [Notion ticket #123](https://notion.so/abc)

## Checklist

- [ ] **⚠️ My code can have side-effects on other part of the code-base**
- [ ] I have added the Plausible tags/events
- [ ] I have performed a self-review of my code (and removed console.log)

## Testing instructions

## Screenshots

2024-01-02 12:38 UTC, naustra requested changes

2024-01-02 12:38 UTC, naustra commented on api/src/models/young.js
> +    lowercase: true,
trim

2024-01-02 12:38 UTC, naustra commented on api/src/models/young.js
> +    lowercase: true,
trim

2024-01-02 12:38 UTC, naustra commented on api/src/controllers/cle/referent-signup.js
> +      email: Joi.string().trim().lowercase().email().required(),
il faudrait autoriser le front a envoyer en majuscule et retransformer ensuite en minuscule apres le joi plutot

2024-01-02 12:38 UTC, naustra commented on api/src/controllers/cle/referent-signup.js
> +      email: Joi.string().trim().lowercase().email().required(),
des gens vont paniquer sinon et pas capter qu'ils doivent ecreir leur mail en minuscule pour que ça marche

2024-01-09 13:26 UTC, nicobret commented on api/src/controllers/cle/referent-signup.js
> +      email: Joi.string().trim().lowercase().email().required(),
Bien vu ça
Je vais faire la modif

2024-01-29 09:56 UTC, nicobret commented on api/src/controllers/cle/referent-signup.js
> +      email: Joi.string().trim().lowercase().email().required(),
Pas de besoin de modifier en fait. La méthode lowercase() de joi convertit en lowercase si ça n'est pas déjà le cas : https://joi.dev/api/?v=15.1.1#stringlowercase

2024-01-29 11:42 UTC, naustra approved these changes

2024-01-29 12:38 UTC, merged