Invitation head center
betagouv/service-national-universel pull request #352
Opened 2021-07-06 06:56 UTC by SpookyUmi

- I created a select input similar to the two other one (référent région & référent département)
- I adapted it to the requirements by fetching all the available centers and displaying them in my select input. 
- I added a conditional rendering on the "Fonction" select as a head center user doesn't have a subrole.

2021-07-13 12:54 UTC, tangimds requested changes
2 remarques (voir mes commentaires ci dessous).
As tu testé cette PR ? Je suis curieux car je ne comprends pas comment cela pouvait marcher ?
(J'ai testé en étant admin et en voulant inviter un chef de centre).

PS : rien à voir (un peu quand même ^^) avec cette PR mais si je sélectionne `referent departemental` puis je repasse en `chef de centre` , le departement est gardé en mémoire et on set donc un département à un chef de centre (ce qui n'a pas de sens)
Ca peut etre le cas dana lautre sens également, si on choisi un centre puis on change de role et on choisi un referent regional par exemple, ce referent sera lié a un centre (illogique)
Je fais une autre issue, c'est un autre probleme, qui était déjà là

Je te laisse revoir cette PR ducoup :) dispo pour écahnger si ce n'est pas clair :)

2021-07-13 12:54 UTC, tangimds commented on admin/src/components/header/invite.js
> +    return onChange({ target: { value: centers?.[0], name: "center" } });
je ne comprends pas ce que tu veux faire ici ?

2021-07-13 12:54 UTC, tangimds commented on admin/src/components/header/invite.js
> +      <Input disabled={user.role === REFERENT_ROLES.HEAD_CENTER} type="select" name="center" value={value} onChange={onChange}>
il y a deux fields à mettre à jour dans le chef de centre.
`cohesionCenterId` et `cohesionCenterName`

`center` n'existe pas

2021-07-22 14:21 UTC, tangimds requested changes
J'espère que tu vas réussir à me lire et comprendre ce que je veux te dire.

Pour résumer :
- import inutiles
- useEffect pour mettre des valeurs par défaut (si c'est un chef de centre qui veut inviter un autre chef de centre. Pour l'instnat, ce n'est pas possible mais autant bien faire les choses tout de suite)
- changement du `onChange` dans le `ReactSelect`

Tu remarqueras que, si tu test en l'état, le centre n'est pas pris en compte.
C'est normal, car dans le back, on ne récupère pas cette info. Et oui, les routes sont sécurisées et si on rajoute un paramètre, il faut vérifier que le back le traite effectivement.

Pour corriger ca, je te laisse aller voir le controller de la route appelé par ce Formik et faire les changements qu'il faut :)
(C'est deux lignes)

Dispo pour en parler si ma connection le veut bien

2021-07-22 14:21 UTC, tangimds commented on admin/src/components/header/invite.js
> +    // </Input>
n'hésite pas à supprimer du code si jamais tu en as pas besoin, on le retrouvera dans les anciens commits.
et pour relire etc c'est beaucoup plus clean
```suggestion
```

2021-07-22 14:21 UTC, tangimds commented on admin/src/components/header/invite.js
> +      options={centers}
je crois qu'on n'a pas autorisé les chefs de centre a inviter d'autres chef de centre, mais autant le mettre pour une possible futur amélioration, ca mange pas de pain
```suggestion
      disabled={user.role === REFERENT_ROLES.HEAD_CENTER}
      options={centers}
```

2021-07-22 14:21 UTC, tangimds commented on admin/src/components/header/invite.js
> +        onSelect?.(e);
je ne sais pas ce que ca faisait mais ca devait être très bizarre au niveau de l'utilisateur.
=> Il peut choisir nimprote quel centre, et à la selection ca mettait son centre puis directement apres ca rechangeait avec le centre selectionné... étrange
```suggestion
        console.log('VALUE', JSON.stringify(e));
        onChange({ target: { value: e._id, name: "cohesionCenterId" } });
        onChange({ target: { value: e.value, name: "cohesionCenterName" } });
        onSelect?.(e);
```

2021-07-22 14:21 UTC, tangimds commented on admin/src/components/header/invite.js
> +  // }, []);
on peut utiliser le `useEffect` pour mettre des valeurs par défaut si besoin.
Dans ce cas, si c'est un chef de centre on va preremplir avec son centre (et le `disabled` l'empeche de changer)
```suggestion
   useEffect(() => {
     if (user.role === REFERENT_ROLES.HEAD_CENTER) {
       return (
         onChange({ target: { value: user.cohesionCenterId, name: "cohesionCenterId" } }),
         onChange({ target: { value: user.cohesionCenterName, name: "cohesionCenterName" } })
       )
     }
   }, []);
```

2021-07-22 14:21 UTC, tangimds commented on admin/src/components/header/invite.js
> +import { ReactiveBase } from "@appbaseio/reactivesearch";
on ne s'en sert pas
```suggestion
```

2021-07-22 14:21 UTC, tangimds commented on admin/src/components/header/invite.js
> +import { apiURL } from "../../config";
on ne s'en sert pas
```suggestion
```

2021-07-22 14:52 UTC, SpookyUmi commented
Pour le code commenté et non supprimé, généralement je fais ça pour laisser au reviewer plus de visu sur ce que j'ai fait/essayé, puis je clean en dernière intention, avant de proposer la version "mergeable". Mais je comprends si ce n'est pas une bonne pratique et si ça fait perdre du temps, j'éviterai à l'avenir. 
Pour les imports inutiles, totalement my bad. 
Merci pour ta review et ton aide, je vais enfin terminer cette PR !

2021-07-23 08:26 UTC, tangimds approved these changes

2021-07-23 08:26 UTC, merged