chore(admin): Add Error Boundary to force reload
betagouv/service-national-universel pull request #3700
Opened 2024-03-28 15:47 UTC by achorein

**Description**

Mise en place d'une page d’erreur standard invitant à recharger la page pour accéder à la dernière mise à jour.

**Screenshots**

![image](https://github.com/betagouv/service-national-universel/assets/6529851/bf692be1-2481-49f8-961a-1446e05f2c76)

**Ticket**
https://www.notion.so/jeveuxaider/Check-versions-mismatch-to-possibly-force-reload-3621ec0524eb4c7da8a316f066a9aea0

**Checklist**

- [ ] **⚠️ My code can have side-effects on other part of the code-base**
- [ ] I have added the Plausible tags/events
- [ ] I have performed a self-review of my code (and removed console.log)

**Testing instructions**

2024-03-29 11:15 UTC, FlawaCLV requested changes
Je "valide" mais mets quand même le request changes pour que le design d'Emmanuel puisse être intégré à cette PR ;-)

2024-03-29 11:15 UTC, FlawaCLV commented on .nvmrc
C'est bizarre que ça soit mit à la racine, no ? Je me souviens avoir mis celui sur `/api`.
Car chaque app du monorepo peut _potentiellement_ avoir une version différente de node.

2024-03-29 11:15 UTC, FlawaCLV commented on admin/src/components/layout/ApplicationError.jsx
À valider le design w/ Emmanuel

2024-03-29 11:41 UTC, achorein commented on .nvmrc
c'est lié à turbo en fait, je lance le build depuis la racine (le npm i avec du coup) donc avec la version node 18.16.
pour moi il y a un peu de spécialisation à faire car on devrait pouvoir lancer le `run dev` de chaque app séparément depuis la racine avec turbo (sans modifier le filtre à la main). On peux déjà le faire mais ça mélange toutes les logs dans un seul terminal.
un sujet à discuter avec @naustra pour la DX.

dans les fait j'ai actuellement un `.nvmrc` dans chaque app et je passe par des tasks vscode pour split mes terminaux.

2024-03-29 11:41 UTC, achorein commented on admin/src/components/layout/ApplicationError.jsx
j'ai eu la maquette figma, mais il faut que je vois où c'est implémenter actuellement car il semble que ce travail a déjà été fait...

2024-04-02 14:21 UTC, achorein commented
@FlawaCLV la maquette a été intégrée !

2024-04-02 17:00 UTC, FlawaCLV commented
> @FlawaCLV la maquette a été intégrée !

@achorein pour ce genre de PR, pour quasi toute en réalité, pense à mettre `-ci-` dans le nom de ton commit pour générer des customs envs. Je vais voir si je peux les générer manuellement.

2024-04-04 12:09 UTC, achorein commented
- admin_endpoint  = "https://admin-chore-1451-admin-errorbou.ci.beta-snu.dev/"
- api_endpoint    = "https://api-chore-1451-admin-errorbou.ci.beta-snu.dev/"
- app_endpoint    = "https://moncompte-chore-1451-admin-errorbou.ci.beta-snu.dev/"

2024-04-04 13:54 UTC, FlawaCLV approved these changes
Un petit conflit à régler et go pour merge 🚀

2024-04-04 14:59 UTC, merged