Feat change structure responsible
betagouv/service-national-universel pull request #375
Opened 2021-07-16 15:07 UTC by hugo3m

2021-07-20 09:04 UTC, hugo3m commented
In draft cause we are missing some information about the product

2021-07-20 09:07 UTC, tangimds requested changes
le temps de chargement est trop long, il faudrait isoler les calls qui prennent beaucoup  de temps (structures, centers).
Je ne pense pas qu'intégrer le `structureName` dans le `user` soit une bonne idée, il faut le mettre dans `initialvalues` mais pas dans le user, ca ralenti le process (on doit attendre d'avoir toutes les structures, pour avoir la sienne, pour pouvoir afficher le user...)

2021-07-20 09:07 UTC, tangimds commented on admin/src/scenes/utilisateur/edit.js
> +      setStructures(s);
le problème ici, c'est que peu importe le référent en qu'on veut voir on va chercher toutes les structures (ce qui est un peu long).
il faudrait séparer les différents traitements dans différents `useEffect` et isoler les structures

2021-07-21 13:08 UTC, tangimds requested changes
ok, je pense que c'est encore améliorable.

j'ai rajouté un message d'alerte si la structure a été modifiée sans être validée. Ca explique un peu le comportement non habituel de cette page.
Mais je suis vraiment pas fan du refresh a chqaue fois, on s'y prend mal.

et le changement de structure se faisait meme si il avait des missions (oublie de `return`)

2021-07-21 13:08 UTC, tangimds commented on api/src/controllers/referent.js
> +    if (missions.length > 0) res.status(405).send({ ok: false, code: ERRORS.OPERATION_NOT_ALLOWED });
```suggestion
    if (missions.length > 0) return res.status(405).send({ ok: false, code: ERRORS.OPERATION_NOT_ALLOWED });
```

2021-07-23 08:47 UTC, tangimds approved these changes

2021-07-23 08:47 UTC, merged