Feat 2158 download classroom convocation ci
betagouv/service-national-universel pull request #3763
Opened 2024-04-12 09:45 UTC by Johannbr

**Description**

**Todo**

**Checklist**

- [ ] **⚠️ My code can have side-effects on other part of the code-base**
- [ ] I have added the Plausible tags/events
- [ ] I have performed a self-review of my code (and removed console.log)

**Ticket / Issue**

**Testing instructions**

2024-04-15 12:00 UTC, nicobret commented on api/src/young/young.type.ts
> +interface File {
Est-ce qu'on ne pourait pas inférer les types directement depuis les schemas pour éviter cette redondance ?
Voir https://mongoosejs.com/docs/typescript/schemas.html

2024-04-15 13:06 UTC, achorein commented on admin/src/scenes/classe/view.jsx
> +      return errorMessage;
ce contrôle devrait être fait en amont et désactiver le téléchargement si ce n'est pas possible

2024-04-15 13:06 UTC, achorein commented on admin/src/scenes/classe/view.jsx
> +    handleConvocationDownload(downloadCertificatesByClassId(classe._id), "Téléchargement des convocations en cours", "Les convocations ont bien été téléchargées", getErrorMessage);
utiliser un `useMutation` de `react-query` plutôt

2024-04-18 15:32 UTC, Johannbr commented on admin/src/scenes/classe/view.jsx
> +      return errorMessage;
Dans le principe, oui, mais j'ai choisi d'utiliser le retour du WS, j'ai eu des doutes sur la valeur du nombre d'élèves affichée dans la page.
Dans les faits, ça ne devrait pas arriver, le seuil est fixé à 50 élèves.

2024-04-18 15:32 UTC, Johannbr commented on api/src/young/young.type.ts
> +interface File {
oui, bonne idée !
A tester

2024-04-18 15:32 UTC, Johannbr commented on admin/src/scenes/classe/view.jsx
> +    handleConvocationDownload(downloadCertificatesByClassId(classe._id), "Téléchargement des convocations en cours", "Les convocations ont bien été téléchargées", getErrorMessage);
je ne connais pas, je jetterai un oeil

2024-04-18 15:56 UTC, C2Chandelier reviewed
Stylé ! par contre c'est trop long / couteux d'inférer le type d'un jeune d'apres son schema sur cette PR ? Pck effectivement quitte a mettre typescript c'est un truc a faire, sinon on va se trimbaler le nouveau young.type.ts partout et ensuite ce sera plus chiant ?

2024-04-19 07:19 UTC, Johannbr commented
> Stylé ! par contre c'est trop long / couteux d'inférer le type d'un jeune d'apres son schema sur cette PR ? Pck effectivement quitte a mettre typescript c'est un truc a faire, sinon on va se trimbaler le nouveau young.type.ts partout et ensuite ce sera plus chiant ?

Oui, ça serait mieux, je regarde, mais pas sûr de pouvoir le faire auj', ça dépendra de la charge sur la squad run :-)

2024-04-19 08:32 UTC, Johannbr commented
> Stylé ! par contre c'est trop long / couteux d'inférer le type d'un jeune d'apres son schema sur cette PR ? Pck effectivement quitte a mettre typescript c'est un truc a faire, sinon on va se trimbaler le nouveau young.type.ts partout et ensuite ce sera plus chiant ?

Pas possible, on utilise mongoose 5, l'inférence fonctionne à partir de mongoose 6. La version la plus à jour en avril 2024 est la 8.
ça nécessite une modif' de config de tsc, que j'ai inclue dans la PR.
Il faudra upgrader mongoose dans une autre PR pour limiter le scope.

2024-04-19 08:36 UTC, Johannbr commented on api/src/young/young.type.ts
> +interface File {
@nicobret , voir comm' ici : https://github.com/betagouv/service-national-universel/pull/3763#issuecomment-2066094535

2024-04-22 09:12 UTC, marin42 approved these changes

2024-04-22 09:12 UTC, marin42 commented on admin/src/hooks/usePendingAction.js
Ce type de hook mériterait d'etre dans la lib pour que MonCompte en profite :)

2024-04-22 09:50 UTC, hlecourt reviewed
C'est super, surtout pour les tests et l'implémentation en TypeScript ! J'aimerais également discuter de l'architecture des fichiers. Hugo P. avait proposé une architecture intéressante. Actuellement, on organise par ressource, mais je me questionne aussi sur les logiques entremêlées, etc. Je pense que ca peux être un sujet intéressant pour le point tech.

2024-04-22 09:50 UTC, hlecourt commented on admin/src/scenes/classe/view.jsx
> +    handleConvocationDownload(downloadCertificatesByClassId(classe._id), "Téléchargement des convocations en cours", "Les convocations ont bien été téléchargées", getErrorMessage);
Ce bout de code avec un hook qui gère plusieurs fonctions et des messages en paramètresest assez complexe à comprendre. Sur notre plateforme, on privilégie généralement quelque chose de plus simple et maintenable, par exemple :

```javascript
const { ok, code } = await api.put(route, data);
if (!ok) {
  // Gestion de l'erreur
}
toastr.success("La session a bien été mise à jour");
// Suite du traitement
} catch (e) {
  capture(e);
  // Gestion de l'erreur
}
```
De plus, je ne vois pas vraiment la nécessité d'un hook custom ici. On pourrait tout à fait gérer ça avec un simple `isLoading` ou avec `react-query,` ce qui serait suffisant et plus aligné avec nos pratiques.

2024-04-22 09:50 UTC, hlecourt commented on admin/src/services/convocation.service.js
Je questionne la nécessité de créer un fichier de services dédié pour une fonction qui est actuellement utilisée uniquement à un seul endroit. Ne serait-il pas plus interessant d'intégrer cette logique directement là où elle est utilisée, pour de simplifier la structure de notre code ?

2024-04-22 09:50 UTC, hlecourt commented on admin/src/hooks/usePendingAction.js
L'utilisation d'un hook personnalisé ici semble superflue et pourrait être remplacée par l'utilisation de React Query ou par la gestion directe de la logique au sein du composant. Ajouter une couche supplémentaire d'abstraction peut rendre le code plus complexe à lire et à maintenir à l'avenir.

2024-04-22 09:50 UTC, hlecourt commented on api/src/index.js
> -  app.use("/classe", require("./controllers/cle/classe"));
Où sont passées les fonctions de l'ancien contrôleur ?

2024-04-22 09:50 UTC, hlecourt commented on api/src/classe/classe.service.ts
Il est important de maintenir une structure claire en ce qui concerne la granularité des fonctions. L'enchaînement actuel, où une fonction en appelle une autre jusqu'à cinq fois de suite, rend le code difficile à suivre. Il serait utile de revoir cette méthode pour rendre notre code plus facile à comprendre et à maintenir.
Définir la granularité souhaitée comme discuter lundi dernier

2024-04-22 09:50 UTC, hlecourt commented on api/src/young/young.type.ts
Aligné avec Nico : l'inférence serait intéressante mais nécessite une version plus élevée de Mongoose ! Question : est-ce que le moment est bien choisi pour migrer ? Ce genre de typage me paraît aussi complexe à maintenir.

2024-04-22 09:50 UTC, hlecourt commented on api/src/geo.ts
Est-ce compatible avec les appels non typés ?

2024-04-22 09:50 UTC, hlecourt commented on api/src/controllers/request.ts
Pourquoi dans le dossier controller ?

2024-04-22 10:03 UTC, naustra commented
> > Stylé ! par contre c'est trop long / couteux d'inférer le type d'un jeune d'apres son schema sur cette PR ? Pck effectivement quitte a mettre typescript c'est un truc a faire, sinon on va se trimbaler le nouveau young.type.ts partout et ensuite ce sera plus chiant ?
> 
> Pas possible, on utilise mongoose 5, l'inférence fonctionne à partir de mongoose 6. La version la plus à jour en avril 2024 est la 8. ça nécessite une modif' de config de tsc, que j'ai inclue dans la PR. Il faudra upgrader mongoose dans une autre PR pour limiter le scope.

Ah clair, c'est un sujet identifié oui.
On peut le traiter la semaine pro le temps d'être sur 100% que la prod fonctionne marche

2024-04-22 10:08 UTC, naustra commented on admin/src/scenes/classe/view.jsx
> +    handleConvocationDownload(downloadCertificatesByClassId(classe._id), "Téléchargement des convocations en cours", "Les convocations ont bien été téléchargées", getErrorMessage);
oui, je préfère pousser l'adoption de react-query aussi

2024-04-22 10:10 UTC, naustra commented on api/src/index.js
> -  app.use("/classe", require("./controllers/cle/classe"));
CRITIQUE Johann ici, il manque du code

2024-04-22 10:16 UTC, naustra commented on api/src/young/young.type.ts
On est clairement en dette technique sur le mongoose donc moi ça me parait pertinent mais il y a des risques comme on est avant juin

2024-04-22 10:47 UTC, pierre-lebihan commented
> > Stylé ! par contre c'est trop long / couteux d'inférer le type d'un jeune d'apres son schema sur cette PR ? Pck effectivement quitte a mettre typescript c'est un truc a faire, sinon on va se trimbaler le nouveau young.type.ts partout et ensuite ce sera plus chiant ?
> 
> Pas possible, on utilise mongoose 5, l'inférence fonctionne à partir de mongoose 6. La version la plus à jour en avril 2024 est la 8. ça nécessite une modif' de config de tsc, que j'ai inclue dans la PR. Il faudra upgrader mongoose dans une autre PR pour limiter le scope.

Pourquoi l'update tcs est inclus dans cette PR ?
On en a pas besoin apriori non ? Autant le faire en mm temps que le mongoose ?

2024-04-22 11:28 UTC, naustra requested changes
On en rediscute au point tech

2024-04-22 11:28 UTC, naustra commented on admin/src/scenes/classe/view.jsx
> +    handleConvocationDownload(downloadCertificatesByClassId(classe._id), "Téléchargement des convocations en cours", "Les convocations ont bien été téléchargées", getErrorMessage);
oui, go react-query, je préfère aussi

2024-04-22 11:28 UTC, naustra commented on api/jest.config.js
> +  testMatch: ["**/?(*.)+(test).[jt]s?(x)"],
Ça fait quoi ça pour les tests ?.
Tu sélectionne les fichiers run c'est ça ?

2024-04-22 11:28 UTC, naustra commented on api/src/classe/classe.controller.ts
> +);
il manque plein de routes ici @Johannbr

2024-04-22 11:28 UTC, naustra commented on api/src/young/young.service.ts
> +  const filteredYoungPdfPromises = await Promise.all(youngPdfPromises).then((youngPdfs) => youngPdfs.filter((youngPdf): youngPdf is YoungPdfWithUniqueName => youngPdf !== null));
Le filtered te protège de quoi ?

2024-04-22 11:28 UTC, naustra commented on api/src/young/young.service.ts
> +  const filteredYoungPdfPromises = await Promise.all(youngPdfPromises).then((youngPdfs) => youngPdfs.filter((youngPdf): youngPdf is YoungPdfWithUniqueName => youngPdf !== null));
il vaut mieux empêcher generatePdf de te renvoyer null non ?

2024-04-22 11:28 UTC, naustra commented on api/src/young/young.service.ts
> +export const generateConvocationByYoung = async (young: YoungType): Promise<YoungPdfWithUniqueName> => {
Fonction trop spécifique. On peut pas mettre YOUNG_DOCUMENT.CONVOCATION et YOUNG_DOCUMENT_PHASE_TEMPLATE.COHESION en argument pour pouvoir adapter a tous les documents ?
Si on a des pb avec certains documents, la on fera des fonction spécifiques

2024-04-22 11:28 UTC, naustra commented on api/src/classe/classe.controller.ts
> +      const convocations = await generateConvocationsByClasseId(id);
C'est pas clair que generateConvocationsByClasseId te génére un zip.

Moi, je sortirai bien la fonction buildZip au niveau du controller ici.

Sinon renomme la fonction pour que ça soit plus clair :
Soit tu sors le zip et tu l'appelle generatePdfConvocationsByClasseId
Soit generateZipConvocationsByClasseId, mais je suis plus fan de la première. Je pense qu'on peut écrire plus d'une ligne pour la partie fonctionnelle dans le controlleur tant que ça dépasse pas 4 lignes

2024-04-22 11:28 UTC, naustra commented on api/src/young/young.service.ts
> +  const filteredYoungPdfPromises = await Promise.all(youngPdfPromises).then((youngPdfs) => youngPdfs.filter((youngPdf): youngPdf is YoungPdfWithUniqueName => youngPdf !== null));
Si le filtered ne sert a rien, je suis plus partant pour ne pas faire la fonction et on fera un map au niveau au dessus si on en a besoin

2024-04-22 11:28 UTC, naustra commented on api/src/young/young.type.ts
on en rediscute au point tech

2024-04-22 13:50 UTC, Johannbr commented on api/src/index.js
> -  app.use("/classe", require("./controllers/cle/classe"));
comme expliqué en point tech, ce require était une "erreur", le require de cle/ est ligne 128. Côté front, la modif' a été faite dans admin/src/scenes/volontaires/create.jsx pour aligner le path

2024-04-22 13:52 UTC, Johannbr commented on api/jest.config.js
> +  testMatch: ["**/?(*.)+(test).[jt]s?(x)"],
c'est pour matcher les TU avec nommage : *.test.ts

2024-04-25 10:14 UTC, merged