throw error at startup
betagouv/service-national-universel pull request #3873
Opened 2024-05-14 14:31 UTC by pitiscarf

2024-05-23 14:45 UTC, naustra reviewed
Il te manque de créer les secrets dans scaleway non ?

2024-05-23 14:45 UTC, pierre-lebihan commented on admin/src/config.ts
> +const SENTRY_TRACING_SAMPLE_RATE = getEnv("SENTRY_TRACING_SAMPLE_RATE", 0.1);
pourquoi 0,1 ?
En developpement on veut 1 pour pas s'embeter

2024-05-23 14:45 UTC, pierre-lebihan commented on admin/src/config.ts
> +const SENTRY_TRACING_SAMPLE_RATE = getEnv("SENTRY_TRACING_SAMPLE_RATE", 0.1);
```suggestion
const SENTRY_TRACING_SAMPLE_RATE = getEnv("SENTRY_TRACING_SAMPLE_RATE", 1.0);
```

2024-05-23 14:45 UTC, pierre-lebihan commented on admin/src/config.ts
> +const SENTRY_SESSION_SAMPLE_RATE = getEnv("SENTRY_SESSION_SAMPLE_RATE", 0.1);
```suggestion
const SENTRY_SESSION_SAMPLE_RATE = getEnv("SENTRY_SESSION_SAMPLE_RATE", 1.0);
```

2024-05-23 15:25 UTC, naustra reviewed
Je créer une tache pour gérer le cas d'analytics du coup

2024-05-23 15:25 UTC, naustra commented on api/package.json
> +    "debug": "NODE_CONFIG_DIR=./src/config DEBUG=express:* nodemon ./src/index.js",
Je préfère remonter le dossier config au dossier parent et enlever tout ça

2024-05-23 16:31 UTC, naustra reviewed
C'est bizarre pour la gestion en mode dev local : 
Sur le front on est dans une logique (Si tu touches aux env, ça reste ds git donc faut faire gaffe a pas le commiter)
et dans le back ce n'est pas le cas.

Il vaut mieux passer par les .env a la racine de app et admin si tu veux overwrite les variable

2024-05-23 16:41 UTC, pierre-lebihan reviewed
Supprimer les env de defaut pour l'api apres avoir merge

2024-05-23 16:43 UTC, naustra reviewed
A la racine de votre monorepo vous devez avoir ça :
GITGUARDIAN_API_KEY=
SCW_ACCESS_KEY=
SCW_SECRET_KEY=
SCW_DEFAULT_PROJECT_ID=
DEV=true

2024-05-23 16:49 UTC, naustra reviewed
TODO :
Check testing
Create ticket to deal with analytics
Check changes on custom env

2024-05-23 16:50 UTC, naustra reviewed
Delete .env-testing if needed

2024-05-23 17:22 UTC, naustra reviewed
La var d'env SCW_ACCESS_KEY est utilisé dans plein de github action. Est-ce qu'on doit pas simplifier des choses là bas aussi ?

2024-05-23 17:22 UTC, naustra commented on api/src/secrets-manager.js
> +    MONGO_URL: asyncConfig(getSecret("MONGO_URL")),
Mets on peut pas get tous les secrets d'un coup puis les ajouter a l'objet ? Là on fait 40 calls au lieu d'un a scaleway

2024-05-23 17:22 UTC, naustra commented on admin/Dockerfile
> +ARG RELEASE=""
On touche déjà a la release plus haut dans le fichier. Pourquoi on fait ça ?

2024-05-23 17:22 UTC, naustra commented on api/src/es/index.js
> +  const has_protocol = config.ES_ENDPOINT.startsWith("http://") || config.ES_ENDPOINT.startsWith("https://");
Quand on gère ça du coup ?

2024-05-23 17:22 UTC, naustra commented on api/src/secrets-manager.js
> +  return async (config, original) => {
pouruoi on garde original ici ?

Pourquoi on a pas besoin de SCW_DEFAULT_PROJECT_ID alors que c'est utilisé côté analytics

2024-05-23 17:24 UTC, pierre-lebihan requested changes
J'attends les réponses aux questions

2024-05-23 19:22 UTC, naustra commented on app/Dockerfile
> +ENV RELEASE=${RELEASE}
c'est au dessus également

2024-05-23 19:23 UTC, naustra commented on api/package.json
> +    "debug": "NODE_CONFIG_DIR=./src/config DEBUG=express:* nodemon ./src/index.js",
Je l'ai fait

2024-05-23 19:24 UTC, naustra commented on api/src/es/index.js
> +  const has_protocol = config.ES_ENDPOINT.startsWith("http://") || config.ES_ENDPOINT.startsWith("https://");
Je pensais qu'on le simplifiait en virant le http et en gérant tout dans la var d'env plutot. On fera ça apres le merge ?

2024-05-23 19:27 UTC, naustra commented
Clean les fichiers d'env une fois fini, il y a sans doute plein de variables plus utilisées

2024-05-23 19:42 UTC, naustra reviewed
Sur l'api, on peut pas prendre tout par défaut (Faire confiance aux envs de scaleway) et virer tous les undefined de default ?

Ça complexifie trop je trouve

2024-05-23 20:03 UTC, naustra reviewed
Est-ce qu'il faudrait pas une logique de default.json qui overwrite env.json sur les fronts aussi pour éviter la duplication et être iso au back sur la logique ?

2024-05-23 20:11 UTC, naustra reviewed
Dire que les revisions sont en dur dans le code maintenant aussi et qu'il faudra un commit en plus d'un changement d'env pour pouvoir modifier/ajouter/retirer une variable

2024-05-23 20:19 UTC, naustra reviewed
Si vous utiliser les env local > migrer vers le nouveau mode vos env et commentez  ...asyncSecretConfig(), pour ne pas load les trucs de scaleway

2024-05-23 20:20 UTC, naustra reviewed
Pour faire les changement front sur le custom env, il faut modifier les fichiers custom.json > Rien n'est sensé être secret sur le front

2024-05-27 06:49 UTC, pitiscarf commented on api/src/secrets-manager.js
> +    MONGO_URL: asyncConfig(getSecret("MONGO_URL")),
la fonction getSecret utilise un singleton secrets défini dans le module qui n'est initialisé par un appel a scaleway que lors du 1er appel. Les appels suivants ne renvoient qu'une propriété de l'objet

2024-05-27 06:52 UTC, pitiscarf commented on admin/Dockerfile
> +ARG RELEASE=""
L'image docker utilise plusieurs étapes : base, installer, runner

Pour avoir access aux build-args, une étape doit utiliser la commande ARG. En l'occurence c'est ce qui permet d'injecter dans l'image la variable d'environnement RELEASE depuis les arguments de build

2024-05-27 06:52 UTC, pitiscarf commented on api/src/es/index.js
> +  const has_protocol = config.ES_ENDPOINT.startsWith("http://") || config.ES_ENDPOINT.startsWith("https://");
Je préfère faire ça effectivement après le merge

2024-05-27 06:59 UTC, pitiscarf commented on api/src/secrets-manager.js
> +  return async (config, original) => {
on peut effectivement enlever l'argument inutilisé `original`

Les clefs API sont liées a un projet par défaut. Cela dit pour être complètement explicite, rien n'empeche de continuer a spécifier le projet et la region

2024-05-27 07:02 UTC, pitiscarf commented
> Sur l'api, on peut pas prendre tout de scaleway par défaut (Faire confiance aux envs de scaleway) et virer tous les undefined de default.json ?

2024-05-27 07:08 UTC, pitiscarf commented
> Sur l'api, on peut pas prendre tout de scaleway par défaut (Faire confiance aux envs de scaleway) et virer tous les undefined de default.json ?
> 
> Comme ce qu'on avait au fait
> 
> Ça complexifie trop je trouve

On peut, mais je ne suis pas favorable à cette idée.

Mettre explicitement undefined dans default.json permet 3 choses importantes :
1. S'assurer qu'une valeur doit être définie plus tard par un override (mandatory) : `[Additionally, setting config values explicitly to undefined is a helpful way to ensure that they must be defined by a later configuration file.](https://github.com/node-config/node-config/wiki/Common-Usage#using-config-values)`
2. Voir directement depuis le code toutes les entrées possibles de configuration possible de l'api, sans passer par un fichier distant
3. Expliciter quelles entrées sont récupérées depuis les secrets

2024-05-27 07:11 UTC, pitiscarf commented
> Est-ce qu'il faudrait pas une logique de default.json qui overwrite env.json sur les fronts aussi pour éviter la duplication et être iso au back sur la logique ?

Par défaut l'app front n'ayant pas de runtime, on ne peut pas utiliser un outil comme node-config. Les défauts sont donc les valeurs de fallback dans `config.js`

2024-05-27 09:03 UTC, pitiscarf commented on api/src/es/index.js
> +  const has_protocol = config.ES_ENDPOINT.startsWith("http://") || config.ES_ENDPOINT.startsWith("https://");
C'est fait

2024-05-27 09:47 UTC, naustra approved these changes

2024-05-27 10:03 UTC, naustra commented on api/Dockerfile
> +ENV NODE_CONFIG_DIR=./api/config
besoin du coup ?
L'app est run depuis le dossier parent en custom env ?
Je pige pas pourquoi il y en a besoin

2024-05-27 10:03 UTC, naustra commented on api/src/main.js
> +  getAllPdfTemplates();
pas d'await ici ?

2024-05-27 10:05 UTC, pitiscarf commented on api/Dockerfile
> +ENV NODE_CONFIG_DIR=./api/config
Yes le current working dir est /app :
`CMD ["node", "api/src/index.js"]`

2024-05-27 10:05 UTC, pitiscarf commented on api/src/main.js
> +  getAllPdfTemplates();
Non, c'était deja le cas avant. Ce code n'est pas touché par la PR

2024-05-27 10:06 UTC, naustra reviewed
> > Est-ce qu'il faudrait pas une logique de default.json qui overwrite env.json sur les fronts aussi pour éviter la duplication et être iso au back sur la logique ?

Par défaut l'app front n'ayant pas de runtime, on ne peut pas utiliser un outil comme node-config. Les défauts sont donc les valeurs de fallback dans `config.js` 


C'est pas qu'une histoire de fallback, un default.json permettrait d'éviter la redite dans chaque env.json aussi

2024-05-27 10:07 UTC, naustra reviewed
> > > Est-ce qu'il faudrait pas une logique de default.json qui overwrite env.json sur les fronts aussi pour éviter la duplication et être iso au back sur la logique ?

>> Par défaut l'app front n'ayant pas de runtime, on ne peut pas utiliser un outil comme node-config. Les défauts sont donc les valeurs de fallback dans `config.js` 

> 
C'est pas qu'une histoire de fallback, un default.json permettrait d'éviter la redite dans chaque env.json aussi

2024-05-27 10:12 UTC, naustra commented on api/Dockerfile
> +ENV NODE_CONFIG_DIR=./api/config
Ah j'avais pas vu, qu'on runnait le docker comme ça.
Mais c'est pas du tout dans la philosophie turbo ça je pense

2024-05-27 10:13 UTC, naustra commented on api/Dockerfile
> +ENV NODE_CONFIG_DIR=./api/config
bon, c'est pas trop grave ok

2024-05-27 10:14 UTC, pitiscarf commented on api/Dockerfile
> +ENV NODE_CONFIG_DIR=./api/config
si c'est meme documenté par Turbo : https://turbo.build/repo/docs/handbook/deploying-with-docker

2024-05-27 13:49 UTC, merged