Fix throw error in referent.js
betagouv/service-national-universel pull request #388
Opened 2021-07-20 15:15 UTC by hugo3m

2021-07-20 16:49 UTC, tangimds reviewed
elle ne passe pas les tests ?

2021-07-20 16:49 UTC, tangimds commented on api/src/controllers/referent.js
> +      password: Joi.string().required(),
pourquoi pas :

```suggestion
      password: Joi.string().min(12).required(),
```

2021-07-21 08:43 UTC, tangimds requested changes
euh ca va pas du tout en fait https://prnt.sc/1dv3u70

il manque les bons messages a pleins d'endroits 
https://prnt.sc/1dv45dk
https://prnt.sc/1dv4901

2021-07-21 09:10 UTC, hugo3m reviewed
C'est changé!

2021-07-21 10:54 UTC, merged