Revert "fix(admin): Reopen boite reception temporairement"
betagouv/service-national-universel pull request #3928
Opened 2024-05-28 14:10 UTC by michaelgarcia75

https://www.notion.so/jeveuxaider/Finir-taches-derniers-sprints-e9effce8aa7f46cda576f59ae42a74d8

2024-05-28 14:45 UTC, pierre-lebihan requested changes

2024-05-28 14:45 UTC, pierre-lebihan commented on admin/src/components/drawer/components/SNUpportBox.jsx
> +      if (!ok) return toastr.error("Oups, une erreur est survenue. Veuillez contacter le support", translate(code));
fait un capture ici

2024-05-29 08:04 UTC, michaelgarcia75 commented on admin/src/components/drawer/components/SNUpportBox.jsx
> +      if (!ok) return toastr.error("Oups, une erreur est survenue. Veuillez contacter le support", translate(code));
done

2024-05-29 09:03 UTC, naustra requested changes

2024-05-29 09:03 UTC, naustra commented on admin/src/components/drawer/components/SNUpportBox.jsx
> +        capture("Failed to sign in to SNUpport", { ok, data, code });
captureMessage("Invalid redirect url", { extra: { redirect } });

C'est comme ça qu'on fait voici un exemple

2024-05-29 09:09 UTC, michaelgarcia75 commented on admin/src/components/drawer/components/SNUpportBox.jsx
> +        capture("Failed to sign in to SNUpport", { ok, data, code });
done my bad

2024-05-29 09:19 UTC, merged