fix(api): 2746 - stop cron en cas de fail brevo
betagouv/service-national-universel pull request #3985
Opened 2024-06-10 16:11 UTC by michaelgarcia75

**Pull Request Title Rules**

Pull request format must respect this format:

```
<type>(<scope>, <scope>...): <Notion ID> or "sentry" - <description>
```

Allowed types: `feat`, `fix`, `refactor`, `chore`.
Allowed scopes: `release`, `app`, `admin`, `misc`, `api`, `all`, `github`, `terraform`, `kb`, `lib`.

Notion ID, followed by a `-` is **mandatory** on types `refactor`, `feat` and `fix`.

_If you really need to bypass the pull request title validation, you can add the `bypass title` label to you PR._

Examples of valid PR titles:

- `chore(release): New version 1.3.3.7`
- `refactor(api): 1789 - Removed monarchy from codebase`
- `fix(api, app, admin): 1981 - User cannot delete each other accounts anymore.`
- `fix(api): sentry - Implement capture or fix a bug.`

**Description**

**Todo**

**Checklist**

- [ ] **⚠️ My code can have side-effects on other part of the code-base**
- [ ] I have added the Plausible tags/events
- [ ] I have performed a self-review of my code (and removed console.log)

**Ticket / Issue**

**Testing instructions**

2024-06-10 16:26 UTC, naustra requested changes

2024-06-10 16:26 UTC, naustra commented on api/src/crons/applicationPending.js
> +        try {
Faut pas faire de try catch ici
On va gérer le bug dans une autre PR

2024-06-11 08:41 UTC, michaelgarcia75 commented on api/src/crons/applicationPending.js
> +        try {
je close la PR alors ?

2024-06-11 09:30 UTC, pierre-lebihan commented on api/src/crons/applicationPending.js
> +        try {
non, il faut push que le awit !

2024-06-11 12:37 UTC, naustra approved these changes

2024-06-11 12:37 UTC, merged