chore(api): ajout des transactions sur la mise à jour des etablissements
betagouv/service-national-universel pull request #4042
Opened 2024-06-27 14:07 UTC by achorein

**Description**

**Todo**

- [ ] Ajout d'une transaction sur les endpoints de mise à jour des établissement
- [ ] Récupération de la session courante dans le hook de pre save

**Ticket / Issue**

**Testing instructions**

2024-06-28 09:56 UTC, naustra requested changes

2024-06-28 09:56 UTC, naustra commented on api/src/models/cle/etablissement.js
> +  const transaction = this.$session();
Descendre dans le if

2025-01-15 14:51 UTC, achorein commented
maintenant que l'indexation elastic est indépendante du code nous pouvons rajouter cette transaction. pour rappel c'est pour eviter les desynchro de departement entre les classes et les etablissement

2025-01-24 09:57 UTC, Johannbr approved these changes

2025-01-28 14:31 UTC, merged