fix(crons): 3114 - mongomonitor amelioration logs
betagouv/service-national-universel pull request #4195
Opened 2024-08-19 14:59 UTC by michaelgarcia75

https://www.notion.so/jeveuxaider/Am-lioration-du-crons-de-monitoring-mongo-b9a20351e3c74927b1d2d5ddfa0f748b

2024-08-19 15:46 UTC, pierre-lebihan requested changes

2024-08-19 15:46 UTC, pierre-lebihan commented on api/src/crons/mongoMonitoring.js
> +function logMetrics(metrics) {
Je comprends pas l'interet de cette fonction

2024-08-19 15:46 UTC, pierre-lebihan commented on api/src/crons/mongoMonitoring.js
> +function logMetrics(metrics) {
Il faut appeler les objets selon ce qu'ils sont et les fonction selon ce qu'elles font. Est-ce que t'es sur du nom de la fonction ?

2024-08-21 08:08 UTC, pitiscarf approved these changes

2024-08-21 08:11 UTC, merged