chore(terraform): add reindexing job
betagouv/service-national-universel pull request #4343
Opened 2024-09-18 09:04 UTC by achorein

**Description**

Ajout de job dans scaleway pour lancer des reindexations sans intervention manuel, à l'image de l'anonymisation. il faudrait idéalement généralisé à staging et prod. sachant que en prod il faut se limiter au minimum de model possible

**Todo**

- [x] PROD: Ajout d'un job pour la reindexation des centres (cf [ticket](https://www.notion.so/jeveuxaider/Lancer-une-r-indexation-des-centres-et-PDR-10472a322d5080ffad3bd33cdbdd8f37?pvs=4))
- [x] PROD: Ajout d'un job pour la reindexation des classes et etablissement
- [ ] STAGING: ajout d'un job pour reindexer les models dit "useful"

**Ticket / Issue**

**Testing instructions**

2024-09-18 09:17 UTC, Johannbr commented on api/src/scripts/reindex_es_all_models/docker/start_reindex_db.sh
C'est une réindexation ES, nommage : start_reindex_es.sh

2024-09-18 09:17 UTC, Johannbr commented on api/src/scripts/reindex_es_all_models/index.js
> +    }
Ok, pour des listes de modèles courant.
Et aussi peut être laisser la possibilité à l'utilisateur de déclarer explicitement les modèles à réindexer.

2024-09-18 09:18 UTC, achorein commented on api/src/scripts/reindex_es_all_models/index.js
> +    }
les params sont uniquement pour les jobs donc pre-remplie avec le minimum selon le context.
pour le lancement en local ça ne change rien à d'habitude, tu modifie la valeur par defaut de `models_indexed`plus haut.
après il faut en effet quels sont les models courant à reindex

2024-09-18 09:19 UTC, achorein commented on api/src/scripts/reindex_es_all_models/docker/start_reindex_db.sh
je reindex la db dans es :D

2024-09-18 09:23 UTC, Johannbr commented on api/src/scripts/reindex_es_all_models/docker/start_reindex_db.sh
Il est aussi possible d'indexer la db en y ajoutant des index Mongo. 
C'est pourquoi je trouvais que le nom du fichier prêtait à confusion.

2024-09-18 09:43 UTC, pitiscarf requested changes
Dans jobs.tf, je définirais juste 1 job, reindex_es, mais rajouterais 2 variables d'environnement:
`"GROUP_NAME" = "all"`
`"NODE_ENV" = "staging"`

Dans start_reindex_db.sh, si l'argument 1 n'est pas renseigné, je lui mettrais la valeur de GROUP_NAME

De cette maniere il est possible d'overrider a l'execution du job, a la fois NODE_ENV et GROUP_NAME

2024-09-19 08:25 UTC, achorein commented on terraform/environments/ci/jobs.tf
> +  description = "Reindex models in Elasticsearch"
```suggestion
  description = "Reindex models in Elasticsearch (GROUP_NAME=usefull | cle | centre | all)"
```

2024-09-19 08:25 UTC, achorein commented on terraform/environments/production/jobs.tf
> +  description = "Reindex models in Elasticsearch"
```suggestion
  description = "Reindex models in Elasticsearch (GROUP_NAME=usefull | cle | centre | all)"
```

2024-09-19 08:25 UTC, pitiscarf approved these changes

2024-09-19 08:41 UTC, merged