3258 add referent to coordinateur
betagouv/service-national-universel pull request #4382
Opened 2024-09-27 15:05 UTC by C2Chandelier

https://www.notion.so/jeveuxaider/CLE-Permettre-de-s-lectionner-un-r-f-rent-de-classe-en-tant-que-coordinateur-8804776db35047aba2aef53e81568814?pvs=4

2024-10-01 15:52 UTC, Johannbr commented on api/src/services/cle/referent.ts
> +export const addReferentClasseAsCoordinator = async (
cette fonction n'ajoute pas de referent de classe, elle envoit un email.
Proposition : renommer en **_inviteReferentAsCoordinator_**

2024-10-04 14:35 UTC, GuiPich91 requested changes

2024-10-04 14:35 UTC, GuiPich91 commented on admin/src/scenes/etablissement/components/ButtonAddCoordinator.tsx
> +      const uniqueIds = new Set();
ici tu as oublié d'exclure les réf qui sont déjà coordinateurs de l'établissement

2024-10-08 13:17 UTC, C2Chandelier commented on admin/src/scenes/etablissement/components/ButtonAddCoordinator.tsx
> +      const uniqueIds = new Set();
si je les retire ligne 57
const uniqueArray = [...(coordinateurs ?? []), ...refList].filter((item) => {
coordinateurs ce sont les coordinateurs déja présent dans l'etablissement :)

2024-10-08 13:40 UTC, Johannbr approved these changes

2024-10-08 14:16 UTC, GuiPich91 approved these changes
ok

2024-10-08 14:56 UTC, merged