chore(api): ajouter la dépendance exceljs for dev
betagouv/service-national-universel pull request #4402
Opened 2024-10-02 13:58 UTC by naustra

2024-10-02 13:59 UTC, hlecourt approved these changes

2024-10-03 07:54 UTC, achorein requested changes
pourquoi ajouter cette lib alors qu'on a déjà "xlsx": "~0.18.5", il faudrait choisir l'une au l'autre non ?

2024-10-04 08:36 UTC, naustra commented
C'est pour le repo script. On avait besoin d'une gestion de la couleur sur les excels qu'apparemment xlsx ne gère pas.
@achorein c'est pour éviter d'installer un package a la mano quand on run un des scripts d'affectation. Ça peut ralentir le prochain en run si on merge pas

2024-10-04 08:37 UTC, naustra commented
c'est @hlecourt qui a codé le script. Il peut t'en dire plus

2024-12-06 17:34 UTC, naustra commented
@achorein Je te laisse décider du sort de cette PR

2025-01-15 14:41 UTC, closed without merging