fix(api): 3480 - fix inscription and ReinscriptionStep when changeCoh…
betagouv/service-national-universel pull request #4435
Opened 2024-10-10 12:48 UTC by GuiPich91

Ticket Notion : https://www.notion.so/jeveuxaider/Sprint-MonCompte-S41-42-10572a322d5080ffad11c2e5a31609f7?p=11572a322d5080f4809adae968f73ffc&pm=s

2024-10-10 13:33 UTC, nicobret commented on api/src/referent/referentController.ts
> +
On force l'étape Représentants pour tous les cas de bascule ? Qu'est-ce qui se passe si le volontaire en était pas encore à cette étape ?

2024-10-10 14:11 UTC, GuiPich91 commented on api/src/referent/referentController.ts
> +
exact je vais faire un check sur la step en préambule

2024-10-11 15:21 UTC, nicobret requested changes, later dismissed

2024-10-11 15:21 UTC, nicobret commented on api/migrations/20241010123909-updateinscriptionStepForYoungCleBug.js
> +      await YoungModel.updateMany(
Eviter les updateMany (on n'a pas de traça). Itérer sur les users et faire un .save() avec le nom de la migration dans le fromUser.

2024-10-11 15:21 UTC, nicobret commented on api/migrations/20241010123909-updateinscriptionStepForYoungCleBug.js
> +      );
Même remarque sur le updateMany + ce "down" n'est pas le symétrique du "up", il va mettre tous les volontaires de l'étape "Représentants" à l'etape de la CNI = ça n'inverse pas la migration, ça étend le pb. Je ne sais pas si on peut faire un down sur cette migration, à moins d'enregistrer la liste des jeunes modifiés qqpart (pas ouf).

2024-10-11 15:21 UTC, nicobret commented on api/src/referent/referentController.ts
> +    if (cohortModel?.type === YOUNG_SOURCE.CLE && young.status === YOUNG_STATUS.IN_PROGRESS && (inscriptionStep === "DOCUMENTS" || reinscriptionStep === "DOCUMENTS")) {
Je pense qu'il vaut mieux importer `STEPS2023` et utiliser `STEPS2023.DOCUMENTS` et `STEPS2023.REPRESENTANTS` plutôt que d'écrire les étape en dur.

2024-10-18 08:53 UTC, C2Chandelier approved these changes

2024-10-18 14:26 UTC, merged