feat(admin): add regional goals for cohort
betagouv/service-national-universel pull request #4582
Opened 2024-11-30 15:57 UTC by naustra

This pull request adds the functionality to define regional goals for a cohort. It includes changes to the `GeneralTab` component to display and select the objectif level (either "departemental" or "regional"). The selected objectif level is then saved in the `cohort` object.

2024-12-02 13:28 UTC, achorein requested changes

2024-12-02 13:28 UTC, achorein commented on api/src/services/inscription-goal.ts
> +export const getCompletionObjectifs = async (department: string, cohort: string, objectifLevel: string) => {
```suggestion
export const getCompletionObjectifs = async (department: string, cohort: string) => {
```
il faut récupéré `objectifLevel`dans les paramétrage dynamiquer directement.

2024-12-02 13:28 UTC, achorein commented on admin/src/scenes/phase0/components/YoungHeader.jsx
> +              if (cohortYoung?.objectifLevel === "regional") {
on pourrait mettre une constante dans la snu-lib plutot qu'une string ? (`INSCRIPTION_GOAL_LEVELS` ?)

2024-12-02 13:47 UTC, naustra commented on api/src/services/inscription-goal.ts
> +export const getCompletionObjectifs = async (department: string, cohort: string, objectifLevel: string) => {
non, on doit laisser departemental volontairement sur certaines routes je pense

2024-12-02 13:48 UTC, naustra commented on api/src/services/inscription-goal.ts
> +export const getCompletionObjectifs = async (department: string, cohort: string, objectifLevel: string) => {
genre les call sur les routes /department ds inscription-goal par exemple

2024-12-02 13:58 UTC, achorein commented on api/src/services/inscription-goal.ts
> +export const getCompletionObjectifs = async (department: string, cohort: string, objectifLevel: string) => {
@naustra le service retourne tout : `getCompletionObjectifs(...).department` te donne l'info que tu veux.

2024-12-02 14:08 UTC, achorein commented on api/src/controllers/inscription-goal.ts
> +      const completionObjectif = await getCompletionObjectifs(department, cohort, INSCRIPTION_GOAL_LEVELS.DEPARTEMENTAL);
```suggestion
      const completionObjectif = await getCompletionObjectifs(department, cohort, INSCRIPTION_GOAL_LEVELS.DEPARTEMENTAL);
```
tu es sur que ici on ne veux pas simplement savoir si on a dépassé les objectifs ?
si l'objectif "level" est a région, il doit quand meme retourné qu'on a atteint les objectif pour le département.

2024-12-02 14:10 UTC, naustra commented on api/src/services/inscription-goal.ts
> +export const getCompletionObjectifs = async (department: string, cohort: string, objectifLevel: string) => {
Mais comment tu veux choper le param dynamique si tu l'envois pas ds la fonction de toutes façons ? Tu veux faire un call pour choper la cohorte dans le service alors qu'on avait déjà l'info ds la route ?
Ou faire passer toute la cohorte en param et plus seulement le nom ?

2024-12-02 14:32 UTC, naustra commented on api/src/controllers/inscription-goal.ts
> +      const completionObjectif = await getCompletionObjectifs(department, cohort, INSCRIPTION_GOAL_LEVELS.DEPARTEMENTAL);
Vu que la route parle spécifiquement des départements, ça me semblerait bizarre qu'on renvoie des infos de région. Mais peut-être qu'il faut oui

2024-12-02 14:52 UTC, naustra commented on api/src/controllers/inscription-goal.ts
> +      const completionObjectif = await getCompletionObjectifs(department, cohort, INSCRIPTION_GOAL_LEVELS.DEPARTEMENTAL);
Je vais voir aves Thomas. Mais c'est moins complexe de pas faire d'exception et tout baser sur le parametrage dynamique oui. Je vérifie les impacts qd même

2024-12-02 16:19 UTC, achorein commented on api/src/services/inscription-goal.ts
> +export const getCompletionObjectifs = async (department: string, cohortName: string, objectifLevel: string) => {
```suggestion
// TODO: passer l'object "cohort" directement
export const getCompletionObjectifs = async (department: string, cohortName: string, cohortObjectifLevel: string) => {
```
a minima, renommer `objectifLevel` en `cohortObjectifLevel` pour que ce ça soit plus clair à la lecture

2024-12-02 16:20 UTC, achorein commented on api/src/services/inscription-goal.ts
> +export const getCompletionObjectifs = async (department: string, cohort: string, objectifLevel: string) => {
oui pour passer toute la cohort dans le méthode.

2024-12-03 15:38 UTC, achorein commented on api/src/__tests__/cohort-group.test.ts
> +      expect(response.status).toBe(404);
pourquoi on change le code ici ? c'est pas plutot le test à adapter ?

2024-12-03 15:38 UTC, achorein commented on api/src/controllers/young/account.ts
> +      const cohortObj = await CohortModel.findOne({ name: cohort });
```suggestion
      const cohortDocument = await CohortModel.findOne({ name: cohort });
```

2024-12-03 15:38 UTC, achorein commented on api/src/services/inscription-goal.test.ts
> +    const cohort = await createCohortHelper(getNewCohortFixture({ name: "Test Cohort" }));
`getNewCohortFixture` donne un "level" aléatoire entre region est département, il faudrait le spécialisé et s'assuré que le region est différent du département.

2024-12-03 15:38 UTC, achorein commented on api/src/services/inscription-goal.test.ts
> +  it("should return departmental completion when objectifLevel is 'departemental'", async () => {
pareil ici

2024-12-03 15:38 UTC, achorein approved these changes

2024-12-06 13:30 UTC, naustra commented on api/src/__tests__/cohort-group.test.ts
> +      expect(response.status).toBe(404);
bah non 404 c'est le code normal pour NOT_FOUND. J'ai changé a la fois la route et le test

2024-12-06 13:31 UTC, naustra commented on api/src/services/inscription-goal.ts
> +export const getCompletionObjectifs = async (department: string, cohortName: string, objectifLevel: string) => {
J'ai mis un objet du coup

2024-12-06 16:28 UTC, merged