add cron autovalidation + fixes
betagouv/service-national-universel pull request #46
Opened 2021-01-15 18:08 UTC by tangimds

Ajout du cron (qui tournerait toute les nuits ?) permettant de valider automatiquement les candidatures étant passé en "Attente de validation" depuis plus de 2 semaines.

\+ Quelques fixs pour intégrer cette nouvelle fonctionnalité

2021-01-18 10:45 UTC, rap2hpoutre requested changes
D'après mes tests ça remet à jour indéfiniment tous ceux qui ont un statut à `WAITING_VALIDATION` vieux de plus de deux semaines.

 ```
// check the last item in historic with status WAITING_VALIDATION
const lastStatus = getLastStatus(doc, "WAITING_VALIDATION");
```

(et ça resync avec sendinblue).

Pour tester, j'ai lancé le script toutes les 5 secondes et ça remet à jour toujours les mêmes.

2021-01-18 18:03 UTC, tangimds commented
Ah yes bien vu ! je fix ça>
Merci

2021-01-19 09:02 UTC, rap2hpoutre approved these changes
Super, ça marche !

2021-01-19 09:02 UTC, rap2hpoutre commented on api/src/crons/index.js
> +        count++;
(optionnel) Pour savoir qui est concerné (et du coup la partie `console.log("checking", doc.email);` devient pas importante et supprimable).

```suggestion
        console.log("updating", doc.email);
        count++;
```

2021-02-04 13:51 UTC, merged