Feat  envoyer un mail au référent à la création d'une mission (#481)
betagouv/service-national-universel pull request #485
Opened 2021-10-06 15:29 UTC by lucienklein

**WIP**
- [ ] Create Sendinblue template

2021-10-07 07:22 UTC, rap2hpoutre commented
Tant que c'est WIP je te le laisse affecté @lucienklein

2021-10-07 09:02 UTC, rap2hpoutre commented
@lucienklein Le fail du test était lié au fait que la mission n'avait pas de référent départemental. J'ai donc fixé ton code au cas où il n'y a pas de référent départemental trouvé (ce qui pourrait arriver).

2021-10-07 09:39 UTC, lucienklein commented
> @lucienklein Le fail du test était lié au fait que la mission n'avait pas de référent départemental. J'ai donc fixé ton code au cas où il n'y a pas de référent départemental trouvé (ce qui pourrait arriver).

Ok, merci je ne savais pas 😉

2021-10-11 07:52 UTC, tangimds requested changes
c'est cool !
j'ai mis a jour l'id du template !

il y a quelques commentaires, n'hésite pas à revenir vers moi si mes retours ne sont pas clairs :)

2021-10-11 07:52 UTC, tangimds commented on api/src/controllers/mission.js
> +    const referentDepartment = await UserObject.findOne().and([{ role: "referent_department" }, { department: checkedMission.department }]);
pourquoi pas :
```suggestion
    const referentDepartment = await UserObject.findOne({ role: "referent_department", department: checkedMission.department });
```
?

de plus, on a des constantes qu'on préfère utiliser -> `ROLES` .

Je te laisse fouiller dans le code pour voir comment elles sont importées/utilisées

2021-10-11 07:52 UTC, tangimds commented on api/src/controllers/mission.js
> +      });
dans le mail, il y a aura un lien pour accéder directement à la mission (https://prnt.sc/1voiej1)
il faut donc passer le lien dans les paramètres (`params.cta`) . Pareil, je te laisse fouiller pour voir comment ca marche :)

2021-10-11 07:52 UTC, tangimds commented on lib/constants.js
> +    NEW_MISSION: "163",
```suggestion
    NEW_MISSION: "192",
```

2021-10-11 10:32 UTC, tangimds requested changes

2021-10-11 10:32 UTC, tangimds commented on api/src/controllers/mission.js
> +          cta: `${APP_URL}/mission/${data._id}`,
⚠️  `APP_URL` est l'url de la plateforme jeune !
il faut utiliser ici l'url de la plateforme admin (oublie pas de l'importer ducoup)

```suggestion
          cta: `${ADMIN_URL}/mission/${data._id}`,
```

2021-10-11 14:51 UTC, tangimds approved these changes
perfect 🎉

2021-10-12 10:05 UTC, merged