Fix  several fixes
betagouv/service-national-universel pull request #532
Opened 2021-10-12 07:25 UTC by SpookyUmi

2021-10-12 08:59 UTC, tangimds requested changes
hey, pas mal de retours, ils ne sont peut etre pas tous hyper clairs ni "obligatoires".
je suis dispo pour échanger si il faut of course !!

2021-10-12 08:59 UTC, tangimds commented on admin/src/components/footer.js
> +            <a href="https://admin.snu.gouv.fr/besoin-d-aide" target="_blank">
c'est pas tres grave mais ducoup il y a un lien vers la prod en staging/local

je ferais plutot ca :
```suggestion
            <a href={`${ADMIN_URL}/besoin-d-aide`} target="_blank">
```

On ne devrait pas plutot pousser la base de connaissance ?

2021-10-12 08:59 UTC, tangimds commented on admin/src/scenes/inbox/components/ticketInfos.js
> +  const currentUser = useSelector((state) => state.Auth.user);
a quoi sert `currentUser` ?

2021-10-12 08:59 UTC, tangimds commented on admin/src/scenes/inbox/components/ticketInfos.js
> +      }
on ne peut pas récupérer les tags du ticket et faire le call au bon model en utilisant le tag `EMETTEUR_...` ?
ca marche comme ca mais un peu maladroit je trouve

2021-10-12 08:59 UTC, tangimds commented on admin/src/scenes/inbox/components/ticketInfos.js
> +            <Link to={user.role ? `/user/${user._id}/edit` : `/volontaire/${user._id}/edit`} target="_blank" rel="noopener noreferrer">
faire en sorte d'avoir le bon lien directement avec le tag `EMETTEUR_...`  ?

les `if` de partout comme ca, ca va nous exploser à la figure et c'est vraiment galère à maintenir :(
Si on peut éviter je pense que ce serait mieux

2021-10-12 08:59 UTC, tangimds commented on admin/src/scenes/inbox/components/ticketMessage.js
> +  ${'' /* flex: 0; */}
pourquoi ?
si c'est pour gérer le multiligne, c'était déjà le cas (l'input s'agrandit à chaque nouvelle ligne)

on peut mettre un peu plus grand mais ca prend beaucoup de place pour "juste" du blanc

2021-10-12 08:59 UTC, tangimds commented on admin/src/scenes/inbox/components/ticketTabs.js
> +        </> */}
il vaut mieux éviter de push des commentaires
```suggestion
```

2021-10-12 08:59 UTC, tangimds commented on admin/src/scenes/inbox/components/ticketTabs.js
> +import ticketExample from "../ticketExample";
```suggestion
```

2021-10-12 08:59 UTC, tangimds commented on admin/src/scenes/support-center/ticket/create.js
> +              {(user.role === "referent_department" || user.role === "referent_region") && values.type === "Aide sur un cas particulier" && (
il faudrait utiliser la constant `ROLES`
```suggestion
              {(user.role === ROLES.REFERENT_DEPARTMENT || user.role === ROLES.REFERENT_REGION) && values.type === "Aide sur un cas particulier" && (
```

2021-10-12 08:59 UTC, tangimds commented on admin/src/scenes/support-center/ticket/create.js
> +                  Pour vous aider à résoudre ce cas particulier, merci de nous transmettre toutes les informations nécessaires à la compréhension de cette situation. Si vous souhaitez joindre des piè
rendre le mail cliquable ?

2021-10-12 08:59 UTC, tangimds commented on api/src/controllers/referent.js
> +    console.log("email", email);
```suggestion
```

2021-10-12 08:59 UTC, tangimds commented on api/src/controllers/referent.js
> +    console.log("Data", data);
```suggestion
```

2021-10-12 08:59 UTC, tangimds commented on api/src/controllers/referent.js
> +    const email = req.query.email;
⚠️ je crois que ce n'est pas le cas sur la route `young` non plus, donc ce trou est à corriger sur les deux routes

Il faudrait sécuriser cette route et faire en sorte que le params `email` existe (pas `null` ou `""`) et que c'est au format email.

la si il n y a pas d'email, ca fait ce call `await ReferentModel.findOne({});` et ca retourne le premier referent de la db 😬

2021-10-12 08:59 UTC, tangimds commented on api/src/controllers/referent.js
> +    return res.status(200).send({ ok: true, data });
on essaie de serialiser (reformater) les infos qu'on renvoit (supprimer les tokens et autres infos à ne pas partager)

```suggestion
    return res.status(200).send({ ok: true, data: serializeReferent(referent, req.user) });
```

2021-10-12 08:59 UTC, tangimds commented on app/src/components/footer.js
> +              Besoin d'aide
cette url n'existe pas :/

2021-10-12 09:13 UTC, SpookyUmi commented on admin/src/scenes/inbox/components/ticketMessage.js
> +  ${'' /* flex: 0; */}
Les référents se sont plaint que l'input pour écrire son message soit trop petite

2021-10-12 09:28 UTC, SpookyUmi commented on admin/src/components/footer.js
> +            <a href="https://admin.snu.gouv.fr/besoin-d-aide" target="_blank">
Bertille m'a demandé de remplacer les deux liens "Nous contacter" et "FAQ" par "besoin d'aide", mais on peut rajouter la base de connaissance

2021-10-12 09:29 UTC, SpookyUmi commented on admin/src/scenes/inbox/components/ticketInfos.js
> +  const currentUser = useSelector((state) => state.Auth.user);
Je voulais m'en servir pour appliquer une condition sur l'apparition des boutons "consulter", "modifier" et "prendre sa place", qui ne sont normalement réservés qu'aux Admin ?

2021-10-12 10:27 UTC, tangimds commented on admin/src/scenes/inbox/components/ticketInfos.js
> +  const currentUser = useSelector((state) => state.Auth.user);
nope, c'est accessibles aux référents aussi (c'est discutable, certes)
mais c'est pas bete de filtrer en plus, pour etre sur que ce ne sont pas des structures ou autres.

Logiquement, les utilisateurs structures (les `responsible` ) n'auront pas acces a la boite de reception, et si ils y accedent, n'auront aucun ticket de visibles.

Mais on peut mettre la condition quand meme (l'important c'est que le back soit sécurisé, notament pour l'edition et la prise de controle)

2021-10-12 10:29 UTC, tangimds commented on admin/src/scenes/inbox/components/ticketMessage.js
> +  ${'' /* flex: 0; */}
oui, c'était avant que je mette la hauteur dynamique. Suite a ce retour, j'ai fait en sorte que l'input s'étire en fonctoin de la taille du message en train d'être tapé.
Tu penses qu'il faut agrandir la taille de l'input par défaut ?

2021-10-13 09:17 UTC, SpookyUmi commented on admin/src/scenes/inbox/components/ticketMessage.js
> +  ${'' /* flex: 0; */}
Ah non du coup si tu as déjà solutionné ce pb, pas besoin ˆˆ

2021-10-13 12:33 UTC, tangimds requested changes
hello, quelques changements encore et apres je pense qu'on pourra envoyer et itérer dans une autre PR si il faut :)

Merci pour ta patience 🙏

2021-10-13 12:33 UTC, tangimds commented on api/src/controllers/referent.js
> +    let data = await ReferentModel.findOne({ email });
il faudrait utiliser la variable `value` (en gros l'email qui est passé par JOI)
et donc supprimer la ligne 569 (qui ne sera plus utilisée)

2021-10-13 12:33 UTC, tangimds commented on api/src/controllers/support-center.js
> +router.get("/tags/:ticketId", passport.authenticate(["referent"], { session: false }), async (req, res) => {
je l'aurais plutot appelé `/ticket/:ticketId/tags`
qu'en penses-tu ?

2021-10-13 12:33 UTC, tangimds commented on api/src/controllers/support-center.js
> +    console.log("id", ticketId);
```suggestion
```

2021-10-13 12:33 UTC, tangimds commented on api/src/controllers/support-center.js
> +    const ticketId = req.params.ticketId;
il faut faire passer ce param dans JOI aussi, basiuquement vérifier si c'est un string et qu'il est obligatoire

2021-10-13 12:33 UTC, tangimds commented on api/src/controllers/young/index.js
> +    if (error) return res.status(400).send({ ok: false, code: ERRORS.INVALID_PARAMS, error: error.message });
pareil que pour la route referent, utiliser la valeur qui est passé par JOI

2021-10-13 12:46 UTC, SpookyUmi commented on api/src/controllers/referent.js
> +    let data = await ReferentModel.findOne({ email });
J'ai tenté en utilisant value mais ça me balance une erreur :/ Je vais retenter, j'ai peut être mal fait un truc

2021-10-13 12:46 UTC, SpookyUmi commented on api/src/controllers/support-center.js
> +router.get("/tags/:ticketId", passport.authenticate(["referent"], { session: false }), async (req, res) => {
Yep c'est mieux !

2021-10-14 09:20 UTC, tangimds approved these changes

2021-10-14 09:26 UTC, merged