Zammad sync
betagouv/service-national-universel pull request #561
Opened 2021-10-14 14:49 UTC by SpookyUmi

2021-10-15 07:56 UTC, tangimds approved these changes
yes !

je me pose une question, qui pourra etre traitée plus tard :
Que se passe-t-il si on change le mail ?
on garde tout nos tickets ?
dans les messages, on regarde le `created_by` (qui est le mail) pour savoir si le message vient de moi ou de la personne avec qui j'échange -> si on change de mail, on deveint schyzo et les messages de l'ancien mail sont considérés comme venant de l'exterieur ou zammad mets a jour les articles ?

bref, pour l'instant je pense que ca suffit comme ca.
il faudra surement refaire un sync de toute la base une fois peut etre non ?

2021-10-15 12:28 UTC, goffle requested changes

2021-10-15 12:28 UTC, goffle commented on api/src/zammad.js
> +    switch (type) {
if c'est plus clair : 

let role = ""
if(type === referent) role = ROLE.REFERENT;
if(type === responsible) role = ROLE.REFERENT;
if(type === volontaire) role = ROLE.VOLONTAIRE;

2021-10-15 12:28 UTC, goffle commented on api/src/zammad.js
> +    console.log("IN SYNC : res", res);
remove

2021-10-15 12:28 UTC, goffle commented on api/src/models/referent.js
> +  console.log(`Post -> save - begin ...`);
remove

2021-10-18 13:19 UTC, tangimds requested changes
ca ne pouvait pas marcher
`type === "responsible"` ne pouvait jamais etre vrai (on n'a pas de model qui s'appelle `responsible` )

On peut en reparler de vive voix des que tu vois ce retour @SpookyUmi

2021-10-18 13:19 UTC, tangimds commented on api/src/zammad.js
> +    }
Ici, `type` fait référence au model de l'objet.

Les structures et référents sont des documents du model `referent`.
Pour faire la distinction entre un utilisateur référent et un utilisateur structure, il faut regarder le `role` de l'`obj`
(cf [here](https://github.com/betagouv/service-national-universel/blob/ae1b4a7669d731a67daf8501bc644e45a6874837/lib/roles.js#L1-L8))

2021-10-18 14:19 UTC, merged