fix: sync info jeune avec ses applications
betagouv/service-national-universel pull request #580
Opened 2021-10-20 09:27 UTC by lucienklein

Fixes #578

2021-10-20 10:05 UTC, tangimds requested changes
en fait, je change de commande mwahahah.

Il faudrait faire une fonction plus générique, pour update une application si la mission OU le jeune change des infos (je pensais que c'était fait pour les missions mais en fait non, yes)

en gros un truc un peu comme ca 👉 https://github.com/betagouv/service-national-universel/blob/e77965561bb6995647b685f7e410f226fb0cde19/api/src/controllers/structure.js#L37-L45

En fait on l'avait fait mais pour repercuter les changements d'une structure sur ses missions.

2021-10-20 14:40 UTC, tangimds requested changes

2021-10-20 14:40 UTC, tangimds commented on api/src/controllers/young/index.js
> +    }
ducoup on vire ca non ?

2021-10-20 14:40 UTC, tangimds commented on api/src/utils/index.js
> +      application.missionDuration = mission.duration;
```suggestion
```
je texplique de vive voix, mais faut pas mettre ca

2021-10-20 14:40 UTC, tangimds commented on api/src/utils/index.js
> +async function syncInfoYoungMission({ young, mission }) {
on sync quoi ?
je proposerai plutot  `updateApplicationsWithYoungOrMission`

2021-10-21 09:06 UTC, tangimds requested changes
ok, ca marche.
j'ai peur que ca dure trop longtemps pour les gens qui ont beaucoup d'applications.

De plus, a **chaque** `put` du jeune, ca va mettre a jour **toutes** ses applications !! meme si il n'y en a pas besoin... 😨 
Par exemple, le jeune renseigne une preference ou je ne sais quoi... le call qui doit juste changer une valeur du jeune, va en fait aller chercher toutes ses applications, et les ecraser avec les memes valeurs. il faudrait mettre a jour les applications, que si il le faut

2021-10-25 09:18 UTC, tangimds requested changes
je pense que l'approche est ok, mais ca ne marche pas pour les dates

2021-10-25 09:18 UTC, tangimds commented on api/src/utils/index.js
> +    console.log(noNeedToUpdate);
pas besoin de push les consoles log
```suggestion
```

2021-10-25 09:18 UTC, tangimds commented on api/src/utils/index.js
> +    if (object[key] !== newObject[key]) {
ca ne marche malheureusement pas pour les dates de naissance.
-> je suis allé sur un profil d'un volontaire, cliqué direct sur enregistrer sans rien changer et ca a donné ca : https://prnt.sc/1xa84bi

2021-10-25 12:20 UTC, tangimds requested changes
ca sync toujours, les dates passent au travers ?
ca marche pour toi ? je teste sur ce profil par exemple `volontaire/606a13ca94727c0715973cbc/edit`

2021-10-25 12:20 UTC, tangimds commented on api/src/utils/index.js
> +    if (object[key]?.toString() !== newObject[key]?.toString()) {
hum ca ne marche toujours pas chez moi :(

https://prnt.sc/1xahzt0

2021-10-26 09:43 UTC, lucienklein commented on api/src/utils/index.js
> +    if (object[key]?.toString() !== newObject[key]?.toString()) {
C'est bon chez moi...

2021-10-29 07:55 UTC, tangimds approved these changes
💯

2021-10-29 09:19 UTC, merged