create state translation function
betagouv/service-national-universel pull request #599
Opened 2021-10-22 13:02 UTC by SpookyUmi

2021-10-25 09:37 UTC, tangimds requested changes
Ce qui est fait es cool, mais il manque a quelques endroits.
Pour certains,  ce n'est pas tres grave, on aurait pu le faire dans une autre PR, mais la les onglets des tickest ne marchent plus 😬 

la fonction `ticketStateIdByName` a changé . je ferais un CTRL+F sur cette fonction pour voir toutes les fois ou on l'utilises et mettre a jour si besoin

2021-10-25 09:37 UTC, tangimds commented on lib/translation.js
> +      return "fermé";
on mets `archivé` ducoup non ?
```suggestion
      return "archivé";
```

2021-10-26 07:20 UTC, SpookyUmi commented on lib/translation.js
> +      return "fermé";
Oh mince je viens de voir ! 
Je regarde tout ça après la réunion !

2021-11-11 09:50 UTC, tangimds requested changes
la fonction `ticketStateIdByName` ne marche plus ducoup :(

il faudrait utiliser uniquement les valeurs en anglais (nos clés) dans le code.
des qu'on veut l'afficher côté front, on le traduit, mais que au dernier moment.

Faudrait check ou on utilise les valeurs en français et les remplacer. Si tu as l'impression de tourner en rond, redis moi on regarde ensemble :)

2021-11-12 11:23 UTC, merged