fix: replace window.open
betagouv/service-national-universel pull request #743
Opened 2021-11-09 11:35 UTC by lucienklein

Fixes #740

2021-11-09 13:37 UTC, rap2hpoutre reviewed
2/3 remarques et c'est bon

2021-11-09 13:37 UTC, rap2hpoutre commented on app/src/components/drawer/index.js
> +        <a href={el.link} target="_blank" style={{ decoration: "none", borderRadius: "99999px", padding: "0" }}>
> borderRadius: "99999px"

lol.

2021-11-09 13:37 UTC, rap2hpoutre commented on app/src/scenes/inscription/Create/stepDocuments.js
> +    </a>
Pourquoi on a changé "Télécharger le formulaire à compléter" par "Télécharger le modèle obligatoire" ?

Et si c'est un PDF, il faut utiliser `download` sinon ça ne marche pas toujours. Les "<a>" c'est pour les liens HTML plutôt, il y a des navigateurs qui grognent sinon

2021-11-09 13:37 UTC, rap2hpoutre commented on app/src/scenes/militaryPreparation/components/UploadCard.js
> +          </a>
Pareil

2021-11-09 15:52 UTC, rap2hpoutre requested changes
En attente des retours

2021-11-10 11:33 UTC, tangimds commented on app/src/scenes/inscription/Create/stepDocuments.js
> +    </a>
c'est un fichier host sur clevercloud 👉  c'est une url

il n y a pas de soucis si ?

2021-11-10 12:42 UTC, merged