create ticket model
betagouv/service-national-universel pull request #793
Opened 2021-11-19 16:40 UTC by SpookyUmi

2021-12-02 14:54 UTC, arnaudambro requested changes
ça me semble correct, mais

la base de donnée est mastoc, le dump que Raph m'a filé c'est 700Mo, y'a des milliers de documents
pour tester ton script il faudra que tu te limites à quelques exemplaires seulement (pas SELECT * mais juste une dizaine ou une quinzaine ou centaine, comme tu veux)

2021-12-02 14:54 UTC, arnaudambro commented on api/src/scripts/ticketScript.js
> +        createdByUserId: message.created_by_id,
cet id il fait référence à un `userId` de notre côté ?

2021-12-02 14:54 UTC, arnaudambro commented on api/src/models/ticket.js
> +    type: mongoose.Types.ObjectId,
il faut créer un modèle pour les tags

2021-12-02 14:54 UTC, arnaudambro commented on api/src/models/ticket.js
> +    type: mongoose.Types.ObjectId,
mais ça peut venir après le test de ton script

2021-12-02 14:54 UTC, arnaudambro commented on api/src/index.js
> +require("./scripts/ticketScript");
ça on ne merge pas en production, me semble-t-il

ton script pour l'instant ne run qu'en local, c'est ça ?

2021-12-02 15:00 UTC, SpookyUmi commented on api/src/scripts/ticketScript.js
> +        createdByUserId: message.created_by_id,
Oui, mais pour l'instant pour les id des utilisateurs (que ce soit référents ou jeunes), il n'y a pas de correspondance entre l'id des users SNU et celui des users Zammad. Donc pour l'instant on va juste dump l'id tel qu'il est dans Zammad sans croiser avec nos modèles "referent" ou "young" car ça ne matchera tout simplement pas

2021-12-02 15:01 UTC, SpookyUmi commented on api/src/scripts/ticketScript.js
> +        createdByUserId: message.created_by_id,
Et pour ton commentaire plus haut, oui pour tester on va tout d'abord mettre une limite, genre `limit 5` ou `limit 10`

2021-12-02 15:08 UTC, SpookyUmi commented on api/src/models/ticket.js
> +    type: mongoose.Types.ObjectId,
Non mais t'as raison

2021-12-02 15:09 UTC, SpookyUmi commented on api/src/index.js
> +require("./scripts/ticketScript");
Oui il tourne en local puisque de toute façon la clé SSH est sur ma machine. Comme on s'était dit et comme Raph me l'a rappelé, il va falloir qu'on voit avec Lucas pour créer un autre user SSH sur une autre machine pour faire tourner ce script de manière automatisée

2021-12-07 09:15 UTC, arnaudambro commented on api/src/scripts/ticketScript.js
> +      } continue;
ça marche comme syntaxe ça ? jamais vu !
j'aurais plutôt mis
```suggestion
      } 
      continue;
```

2021-12-07 09:15 UTC, arnaudambro commented on api/src/scripts/ticketScript.js
> +    } const SNUtag = await TagModel.create({ zammadId: tag.id, name: tag.name });
pareil
```suggestion
    } 
    const SNUtag = await TagModel.create({ zammadId: tag.id, name: tag.name });
```

2021-12-07 09:37 UTC, arnaudambro requested changes
on va quand même merger cette PR
-> tu peux faire un rebase sur main ? y'a des conflits
-> retirer le démarrage auto: on va exécuter ce script quand on a besoin seulement

bueno ?

2021-12-07 10:33 UTC, SpookyUmi commented on api/src/scripts/ticketScript.js
> +      } continue;
@arnaudambro ca fonctionne, c'est comme si je mettais un else { continue } non ? Si je le mets en dessous, ca va `continue` dans tous les cas ?

2021-12-07 10:34 UTC, SpookyUmi commented on api/src/scripts/ticketScript.js
> +      } continue;
Ou alors pas besoin de le laisser sur la même ligne maybe ? Je suis jamais sûre

2021-12-07 10:34 UTC, SpookyUmi commented on api/src/scripts/ticketScript.js
> +      } continue;
Je peux re-tester avec les 2 écritures !

2021-12-14 09:30 UTC, merged