feat: changement ordre étape inscription
betagouv/service-national-universel pull request #839
Opened 2021-11-30 17:11 UTC by lucienklein

Fixes #822

2021-11-30 17:13 UTC, lucienklein commented
- [ ] Checker si c'est bien ce que tu pensais pour l'histoire du status
- [ ] Vérifier qu'on n'affiche pas ses dossiers aux référents

2021-12-08 15:26 UTC, tangimds requested changes
le drawer n'est pas dans le bon ordre 
<img width="1671" alt="Screenshot 2021-12-08 at 16 21 46" src="https://user-images.githubusercontent.com/33058720/145234459-942fc377-2c94-4c0d-aacd-49004ec412bd.png">

il manque les constantes liées à ce nouveau statut -> traduction et couleur (met ce qu'il te semble parlant)

2021-12-08 15:26 UTC, tangimds commented on app/src/scenes/inscription/Create/stepAvailability.js
> +  }, [availability]);
je ne sais pas si je suis chaud pour ca... ?
update le jeune a la volée comme ca... mais why not, ca ne demande aucune action du jeune

par contre ca ne sert a rien de repasser tout le `young`, juste le `status` suffit non ?

2021-12-08 15:26 UTC, tangimds commented on app/src/scenes/inscription/Create/stepDocuments.js
> +            const { ok, code, data } = await api.put("/young", { ...values, inscriptionStep: STEPS.DONE });
c'est pas logique, il faut supprimer une des deux (la ligne 53 ne sert a rien je pense)

2021-12-08 15:26 UTC, tangimds commented on app/src/scenes/inscription/Create/stepDocuments.js
> +        {({ values, handleChange, handleSubmit, isSubmitting, submitForm, errors, touched }) => (
pourquoi rajouter ca ?

2021-12-10 14:41 UTC, tangimds commented on app/src/scenes/inscription/Create/stepAvailability.js
> +  }, [availability]);
par exemple, j'avais un compte qui était sur `juillet 2022`
pour une raison x ou y (règles ont changé, les dossiers a changé, le séjour est blindé)
et bah on va mettre que le jeune est `NOT_ELIGIBLE` alors qu'il l'était avant. Il n'est plus eligible maintenant mais ce n'est pas grave, on ne va pas écraser...
je ne sais pas si je suis clair

2021-12-13 10:25 UTC, tangimds commented on app/src/scenes/inscription/Create/stepAvailability.js
> +  }, [availability]);
@lucienklein ☝️ 

qu'en penses-tu ?

2021-12-13 14:56 UTC, merged